<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 共和分分析 | 金融時系列解析</title>
  <meta name="description" content="10 共和分分析 | 金融時系列解析" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="10 共和分分析 | 金融時系列解析" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 共和分分析 | 金融時系列解析" />
  
  
  

<meta name="author" content="林 高樹" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="varモデル.html"/>
<link rel="next" href="多変量ボラティリティモデル.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> はじめに</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#時系列モデリング"><i class="fa fa-check"></i><b>1.1</b> 時系列モデリング</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#金融時系列データの特徴"><i class="fa fa-check"></i><b>1.2</b> 金融時系列データの特徴</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#金融時系列データの特徴-みずほ-8411-株価データの例"><i class="fa fa-check"></i>金融時系列データの特徴: みずほ (8411) 株価データの例</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#シミュレーションによるサンプルパス生成"><i class="fa fa-check"></i><b>1.3</b> シミュレーションによるサンプルパス生成</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#rにおける時系列オブジェクトクラスおよび関数の例"><i class="fa fa-check"></i><b>1.4</b> Rにおける時系列オブジェクト・クラスおよび関数の例</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#日付時間データに対するクラス"><i class="fa fa-check"></i><b>1.4.1</b> 日付・時間データに対するクラス</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#時系列データに対するクラス1-tsクラス"><i class="fa fa-check"></i><b>1.4.2</b> 時系列データに対するクラス(1): tsクラス</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#時系列データに対するクラス2-zooクラスとxtsクラス"><i class="fa fa-check"></i><b>1.4.3</b> 時系列データに対するクラス(2): zooクラスとxtsクラス</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#時系列データの分解"><i class="fa fa-check"></i><b>1.5</b> 時系列データの分解</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#トレンド抽出-平滑化-smoothing"><i class="fa fa-check"></i><b>1.5.1</b> トレンド抽出, 平滑化 (smoothing)</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#分解モデル"><i class="fa fa-check"></i><b>1.5.2</b> 分解モデル</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html"><i class="fa fa-check"></i><b>2</b> 定常性と自己相関関数</a>
<ul>
<li class="chapter" data-level="2.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#確率過程の2次特性-平均関数と自己共分散関数"><i class="fa fa-check"></i><b>2.1</b> 確率過程の2次特性: 平均関数と自己共分散関数</a></li>
<li class="chapter" data-level="2.2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#定常性-stationarity"><i class="fa fa-check"></i><b>2.2</b> 定常性 (stationarity)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#強定常性"><i class="fa fa-check"></i><b>2.2.1</b> 強定常性</a></li>
<li class="chapter" data-level="2.2.2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#弱定常性"><i class="fa fa-check"></i><b>2.2.2</b> 弱定常性</a></li>
<li class="chapter" data-level="2.2.3" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#ホワイトノイズ"><i class="fa fa-check"></i><b>2.2.3</b> ホワイトノイズ</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#標本平均と標本自己共分散関数"><i class="fa fa-check"></i><b>2.3</b> 標本平均と標本自己共分散関数</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#アンサンブル平均-vs-標本平均"><i class="fa fa-check"></i><b>2.3.1</b> アンサンブル平均 vs 標本平均</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#r操作-標本acf"><i class="fa fa-check"></i><b>2.4</b> R操作: 標本ACF</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#白色ノイズ"><i class="fa fa-check"></i><b>2.4.1</b> 白色ノイズ</a></li>
<li class="chapter" data-level="2.4.2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#ランダムウォーク"><i class="fa fa-check"></i><b>2.4.2</b> ランダムウォーク</a></li>
<li class="chapter" data-level="2.4.3" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#非定常成分を含む時系列"><i class="fa fa-check"></i><b>2.4.3</b> 非定常成分を含む時系列</a></li>
<li class="chapter" data-level="2.4.4" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#線形定常時系列モデル"><i class="fa fa-check"></i><b>2.4.4</b> 線形・定常時系列モデル</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#母acf-vs-標本acf"><i class="fa fa-check"></i><b>2.5</b> 母ACF vs 標本ACF</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="armapqモデル.html"><a href="armapqモデル.html"><i class="fa fa-check"></i><b>3</b> ARMA<span class="math inline">\((p,q)\)</span>モデル</a>
<ul>
<li class="chapter" data-level="3.1" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルとは"><i class="fa fa-check"></i><b>3.1</b> ARMA<span class="math inline">\((p,q)\)</span>モデルとは</a>
<ul>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#因果性と反転可能性"><i class="fa fa-check"></i>因果性と反転可能性</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの意義"><i class="fa fa-check"></i>ARMA<span class="math inline">\((p,q)\)</span>モデルの意義</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルによる予測"><i class="fa fa-check"></i><b>3.2</b> ARMA<span class="math inline">\((p,q)\)</span>モデルによる予測</a></li>
<li class="chapter" data-level="3.3" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの推定"><i class="fa fa-check"></i><b>3.3</b> ARMA<span class="math inline">\((p,q)\)</span>モデルの推定</a></li>
<li class="chapter" data-level="3.4" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの同定-次数の特定"><i class="fa fa-check"></i><b>3.4</b> ARMA<span class="math inline">\((p,q)\)</span>モデルの同定 (次数の特定)</a></li>
<li class="chapter" data-level="3.5" data-path="armapqモデル.html"><a href="armapqモデル.html#r操作"><i class="fa fa-check"></i><b>3.5</b> R操作</a>
<ul>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの同定-acfpacfeacfの利用"><i class="fa fa-check"></i>ARMA<span class="math inline">\((p,q)\)</span>モデルの同定 (ACF/PACF/EACFの利用)</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの推定診断"><i class="fa fa-check"></i>ARMA<span class="math inline">\((p,q)\)</span>モデルの推定・診断</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#パッケージforecastの利用"><i class="fa fa-check"></i>パッケージ{forecast}の利用</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="armapqモデル.html"><a href="armapqモデル.html#データ分析例-tsay-ch2より"><i class="fa fa-check"></i><b>3.6</b> データ分析例 (Tsay, Ch2より)</a>
<ul>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#標本acf"><i class="fa fa-check"></i>標本ACF</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#ar-ma-arma-2.42.6"><i class="fa fa-check"></i>AR, MA, ARMA (2.4–2.6)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html"><i class="fa fa-check"></i><b>4</b> ARIMA/SARIMAモデル</a>
<ul>
<li class="chapter" data-level="4.1" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#arimapdqモデルとは"><i class="fa fa-check"></i><b>4.1</b> ARIMA<span class="math inline">\((p,d,q)\)</span>モデルとは</a></li>
<li class="chapter" data-level="4.2" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#sarimapdqtimes-pdq_sモデル-周期sとは"><i class="fa fa-check"></i><b>4.2</b> SARIMA<span class="math inline">\((p,d,q)\times (P,D,Q)_s\)</span>モデル (周期<span class="math inline">\(s\)</span>)とは</a></li>
<li class="chapter" data-level="4.3" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#sarimaモデルのパス生成-パッケージsarimaの利用"><i class="fa fa-check"></i><b>4.3</b> SARIMAモデルのパス生成: パッケージ<strong>sarima</strong>の利用</a></li>
<li class="chapter" data-level="4.4" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#sarimaモデルの推定診断"><i class="fa fa-check"></i><b>4.4</b> SARIMAモデルの推定・診断</a>
<ul>
<li class="chapter" data-level="" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#パッケージforecastの利用-1"><i class="fa fa-check"></i>パッケージ<strong>forecast</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#データ分析例"><i class="fa fa-check"></i><b>4.5</b> データ分析例</a>
<ul>
<li class="chapter" data-level="" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#データセット-bonds"><i class="fa fa-check"></i>データセット: bonds</a></li>
<li class="chapter" data-level="" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#データセット-airpassengers"><i class="fa fa-check"></i>データセット: AirPassengers</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#外生的トレンドがあるケース"><i class="fa fa-check"></i><b>4.6</b> 外生的トレンドがあるケース</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html"><i class="fa fa-check"></i><b>5</b> 確率的トレンドと単位根検定</a>
<ul>
<li class="chapter" data-level="5.1" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#確率的トレンド-vs-確定的トレンド"><i class="fa fa-check"></i><b>5.1</b> 確率的トレンド vs 確定的トレンド</a></li>
<li class="chapter" data-level="5.2" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#単位根過程と見せかけの回帰"><i class="fa fa-check"></i><b>5.2</b> 単位根過程と見せかけの回帰</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#単位根過程"><i class="fa fa-check"></i><b>5.2.1</b> 単位根過程</a></li>
<li class="chapter" data-level="5.2.2" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#見せかけの回帰"><i class="fa fa-check"></i><b>5.2.2</b> 見せかけの回帰</a></li>
<li class="chapter" data-level="5.2.3" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#見せかけの回帰の判定"><i class="fa fa-check"></i><b>5.2.3</b> 見せかけの回帰の判定</a></li>
<li class="chapter" data-level="5.2.4" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#rで実行可能な主な単位根検定法"><i class="fa fa-check"></i><b>5.2.4</b> Rで実行可能な主な単位根検定法</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#augmented-dicky-fuller-adf-検定"><i class="fa fa-check"></i><b>5.3</b> Augmented Dicky-Fuller (ADF) 検定</a>
<ul>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#パッケージfunitroots"><i class="fa fa-check"></i>パッケージ<strong>fUnitRoots</strong></a></li>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#パッケージtseries"><i class="fa fa-check"></i>パッケージ<strong>tseries</strong></a></li>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#パッケージurca"><i class="fa fa-check"></i>パッケージ<strong>urca</strong></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#adf検定以外の検定法"><i class="fa fa-check"></i><b>5.4</b> ADF検定以外の検定法</a>
<ul>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#phillips-perron-pp-検定"><i class="fa fa-check"></i>Phillips-Perron (PP) 検定</a></li>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#kwiatkowski-phillips-schmidt-shin-kpss-検定"><i class="fa fa-check"></i>Kwiatkowski-Phillips-Schmidt-Shin (KPSS) 検定</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="長期記憶過程.html"><a href="長期記憶過程.html"><i class="fa fa-check"></i><b>6</b> 長期記憶過程</a>
<ul>
<li class="chapter" data-level="6.1" data-path="長期記憶過程.html"><a href="長期記憶過程.html#長期記憶過程のシミュレーション"><i class="fa fa-check"></i><b>6.1</b> 長期記憶過程のシミュレーション</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージfracdiffの利用"><i class="fa fa-check"></i>パッケージ<strong>fracdiff</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージlongmemoの利用"><i class="fa fa-check"></i>パッケージ<strong>longmemo</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="長期記憶過程.html"><a href="長期記憶過程.html#hurst指数の推定"><i class="fa fa-check"></i><b>6.2</b> Hurst指数の推定</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージpracmaの利用"><i class="fa fa-check"></i>パッケージ<strong>pracma</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージfractalの利用"><i class="fa fa-check"></i>パッケージ<strong>fractal</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデルの推定"><i class="fa fa-check"></i><b>6.3</b> ARFIMAモデルの推定</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージfracdiffの利用-1"><i class="fa fa-check"></i>パッケージ<strong>fracdiff</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージnsarfimaの利用"><i class="fa fa-check"></i>パッケージ<strong>nsarfima</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#階差次数dの代替的推定法"><i class="fa fa-check"></i>階差次数<span class="math inline">\(d\)</span>の代替的推定法</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデル-データ分析例-1"><i class="fa fa-check"></i><b>6.4</b> ARFIMAモデル: データ分析例 (1)</a></li>
<li class="chapter" data-level="6.5" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデル-データ分析例-2"><i class="fa fa-check"></i><b>6.5</b> ARFIMAモデル: データ分析例 (2)</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#最適なarfimaモデルの選択および推定"><i class="fa fa-check"></i>最適なARFIMAモデルの選択および推定</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデルによる外挿予測"><i class="fa fa-check"></i>ARFIMAモデルによる外挿予測</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="レジームスイッチングモデル.html"><a href="レジームスイッチングモデル.html"><i class="fa fa-check"></i><b>7</b> レジーム・スイッチング・モデル</a>
<ul>
<li class="chapter" data-level="7.1" data-path="レジームスイッチングモデル.html"><a href="レジームスイッチングモデル.html#自己回帰マルコフスイッチングモデル-msm-ar"><i class="fa fa-check"></i><b>7.1</b> 自己回帰マルコフ・スイッチング・モデル (MSM-AR)</a></li>
<li class="chapter" data-level="7.2" data-path="レジームスイッチングモデル.html"><a href="レジームスイッチングモデル.html#msm-arモデルの適合"><i class="fa fa-check"></i><b>7.2</b> MSM-ARモデルの適合</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="garchモデル.html"><a href="garchモデル.html"><i class="fa fa-check"></i><b>8</b> GARCHモデル</a>
<ul>
<li class="chapter" data-level="8.1" data-path="garchモデル.html"><a href="garchモデル.html#収益率データとarch効果"><i class="fa fa-check"></i><b>8.1</b> 収益率データとARCH効果</a></li>
<li class="chapter" data-level="8.2" data-path="garchモデル.html"><a href="garchモデル.html#archgarchモデル"><i class="fa fa-check"></i><b>8.2</b> ARCH/GARCHモデル</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garchpqモデル"><i class="fa fa-check"></i>GARCH(p,q)モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garchモデリング"><i class="fa fa-check"></i>GARCHモデリング</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="garchモデル.html"><a href="garchモデル.html#archgarchモデルのシミュレーション"><i class="fa fa-check"></i><b>8.3</b> ARCH/GARCHモデルのシミュレーション</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#パッケージfgarchの利用"><i class="fa fa-check"></i>パッケージ<strong>fGarch</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#archpモデル"><i class="fa fa-check"></i>ARCH(p)モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garchpqモデル-1"><i class="fa fa-check"></i>GARCH(p,q)モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#armapq-garchpqモデル"><i class="fa fa-check"></i>ARMA(p’,q’)-GARCH(p,q)モデル</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="garchモデル.html"><a href="garchモデル.html#archgarchモデルの適合"><i class="fa fa-check"></i><b>8.4</b> ARCH/GARCHモデルの適合</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#パッケージrugarchの利用"><i class="fa fa-check"></i>パッケージ<strong>rugarch</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#iarch11"><i class="fa fa-check"></i>IARCH(1,1)</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#gjr-garch11"><i class="fa fa-check"></i>GJR-GARCH(1,1)</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#aparch"><i class="fa fa-check"></i>APARCH</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="garchモデル.html"><a href="garchモデル.html#garchモデル-データ分析例-tsay-ch4"><i class="fa fa-check"></i><b>8.5</b> GARCHモデル: データ分析例 (Tsay, Ch4)</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#必要な関数やデータセットの入手"><i class="fa fa-check"></i>必要な関数やデータセットの入手</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#integrated-garch-モデル"><i class="fa fa-check"></i>Integrated GARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garch-m-モデル"><i class="fa fa-check"></i>GARCH-M モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#exponential-garch-model"><i class="fa fa-check"></i>Exponential GARCH Model</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#threshold-garch-モデル"><i class="fa fa-check"></i>Threshold GARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#asymmetric-power-arch-モデル"><i class="fa fa-check"></i>Asymmetric Power ARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#nonsymmetric-garch-モデル"><i class="fa fa-check"></i>Nonsymmetric GARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#代替的アプリーチ間の比較"><i class="fa fa-check"></i>代替的アプリーチ間の比較</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="varモデル.html"><a href="varモデル.html"><i class="fa fa-check"></i><b>9</b> VARモデル</a>
<ul>
<li class="chapter" data-level="9.1" data-path="varモデル.html"><a href="varモデル.html#varpモデルのシミュレーション"><i class="fa fa-check"></i><b>9.1</b> VAR(<span class="math inline">\(p\)</span>)モデルのシミュレーション</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#パッケージmts-varsの利用"><i class="fa fa-check"></i>パッケージ<strong>MTS</strong>, <strong>vars</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="varモデル.html"><a href="varモデル.html#varpモデルの構築"><i class="fa fa-check"></i><b>9.2</b> VAR(<span class="math inline">\(p\)</span>)モデルの構築</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varpモデルの次数同定"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>)モデルの次数同定</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varpモデルの推定"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>)モデルの推定</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varpモデル予測"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>)モデル予測</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="varモデル.html"><a href="varモデル.html#var解析"><i class="fa fa-check"></i><b>9.3</b> VAR解析</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varp-モデルの構築-復習"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>) モデルの構築 (復習)</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#グレンジャーの因果性検定"><i class="fa fa-check"></i>グレンジャーの因果性検定</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#インパルス応答"><i class="fa fa-check"></i>インパルス応答</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#予測誤差分散分解-forecast-error-variance-decomposition"><i class="fa fa-check"></i>予測誤差分散分解 (forecast error variance decomposition)</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="varモデル.html"><a href="varモデル.html#var解析-データ分析例"><i class="fa fa-check"></i><b>9.4</b> VAR解析 (データ分析例)</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#事例1-ソフトバンク9434-vs-ソフトバンクグループ9984"><i class="fa fa-check"></i>事例1: ソフトバンク(9434) vs ソフトバンクグループ(9984)</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#事例2-米英日3株式市場-sp500-ftse-日経平均"><i class="fa fa-check"></i>事例2: 米英日3株式市場 (S&amp;P500, FTSE, 日経平均)</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="varモデル.html"><a href="varモデル.html#補足-分散共分散行列のコレスキー分解"><i class="fa fa-check"></i><b>9.5</b> 補足: 分散共分散行列のコレスキー分解</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="共和分分析.html"><a href="共和分分析.html"><i class="fa fa-check"></i><b>10</b> 共和分分析</a>
<ul>
<li class="chapter" data-level="10.1" data-path="共和分分析.html"><a href="共和分分析.html#見せかけの回帰-再掲"><i class="fa fa-check"></i><b>10.1</b> 見せかけの回帰 (再掲)</a>
<ul>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#durbin-watson検定"><i class="fa fa-check"></i>Durbin-Watson検定</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#rで実行可能な主な単位根検定法-1"><i class="fa fa-check"></i>Rで実行可能な主な単位根検定法</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="共和分分析.html"><a href="共和分分析.html#共和分分析-1"><i class="fa fa-check"></i><b>10.2</b> 共和分分析</a>
<ul>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#englegrangerの方法-philips-ouliaris検定"><i class="fa fa-check"></i>Engle–Grangerの方法 (Philips-Ouliaris検定)</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#johansenの方法"><i class="fa fa-check"></i>Johansenの方法</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="共和分分析.html"><a href="共和分分析.html#誤差修正モデル-データ分析例-tsay-mts-ch5"><i class="fa fa-check"></i><b>10.3</b> 誤差修正モデル: データ分析例 (Tsay, MTS, Ch5)</a>
<ul>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#共和分検定"><i class="fa fa-check"></i>共和分検定</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#johansenの方法-1"><i class="fa fa-check"></i>Johansenの方法</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#誤差修正モデル-ecm-の推定"><i class="fa fa-check"></i>誤差修正モデル (ECM) の推定</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html"><i class="fa fa-check"></i><b>11</b> 多変量ボラティリティ・モデル</a>
<ul>
<li class="chapter" data-level="11.1" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#ボラティリティスピルオーバー-volatility-spillover"><i class="fa fa-check"></i><b>11.1</b> ボラティリティ・スピルオーバー (volatility spillover)</a></li>
<li class="chapter" data-level="11.2" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#多変量garchモデル-データ分析例-tsay-mts-ch.7"><i class="fa fa-check"></i><b>11.2</b> 多変量GARCHモデル: データ分析例 (Tsay, MTS, Ch.7)</a>
<ul>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#多変量時系列データの条件付不均一分散性の検定"><i class="fa fa-check"></i>多変量時系列データの条件付不均一分散性の検定</a></li>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#指数加重移動平均法-ewma"><i class="fa fa-check"></i>指数加重移動平均法 (EWMA)</a></li>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#bekk1-1モデル"><i class="fa fa-check"></i>BEKK(1, 1)モデル</a></li>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#cholesky分解を利用したボラティリティモデリングおよび推定"><i class="fa fa-check"></i>Cholesky分解を利用したボラティリティ・モデリングおよび推定</a></li>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#dcc-dynamic-conditional-correlation-モデル"><i class="fa fa-check"></i>DCC (Dynamic Conditional Correlation) モデル</a></li>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#go-garchモデル"><i class="fa fa-check"></i>GO-GARCHモデル</a></li>
<li class="chapter" data-level="" data-path="多変量ボラティリティモデル.html"><a href="多変量ボラティリティモデル.html#コピュラに基づくアプローチ"><i class="fa fa-check"></i>コピュラに基づくアプローチ</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="動的線形モデル.html"><a href="動的線形モデル.html"><i class="fa fa-check"></i><b>12</b> 動的線形モデル</a>
<ul>
<li class="chapter" data-level="12.1" data-path="動的線形モデル.html"><a href="動的線形モデル.html#局所水準-local-level-モデル"><i class="fa fa-check"></i><b>12.1</b> 局所水準 (local level) モデル</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#フィルタリング"><i class="fa fa-check"></i>フィルタリング</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#スムージング-平滑化"><i class="fa fa-check"></i>スムージング (平滑化)</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#状態予測"><i class="fa fa-check"></i>状態予測</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#モデル診断-1"><i class="fa fa-check"></i>モデル診断</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#モデルパラメータの推定"><i class="fa fa-check"></i>モデル・パラメータの推定</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="動的線形モデル.html"><a href="動的線形モデル.html#local-level-plus-seasonal-componentモデル"><i class="fa fa-check"></i><b>12.2</b> local level plus seasonal componentモデル</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#状態予測-1"><i class="fa fa-check"></i>状態予測</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="動的線形モデル.html"><a href="動的線形モデル.html#動的回帰モデル"><i class="fa fa-check"></i><b>12.3</b> 動的回帰モデル</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#スムージング"><i class="fa fa-check"></i>スムージング</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="動的線形モデル.html"><a href="動的線形モデル.html#sur-seemingly-unrelated-regression-モデル-3.3.3"><i class="fa fa-check"></i><b>12.4</b> SUR (Seemingly Unrelated Regression) モデル (3.3.3)</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#参考文献"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html"><i class="fa fa-check"></i><b>13</b> 高頻度データ分析</a>
<ul>
<li class="chapter" data-level="13.1" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#ボラティリティ推定"><i class="fa fa-check"></i><b>13.1</b> ボラティリティ推定</a>
<ul>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#データセット1-topix指数データ"><i class="fa fa-check"></i>データセット1: TOPIX指数データ</a></li>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#実現ボラティリティの計算"><i class="fa fa-check"></i>実現ボラティリティの計算</a></li>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#parkinsonボラティリティの計算"><i class="fa fa-check"></i>Parkinsonボラティリティの計算</a></li>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#har-rvモデルによる予測"><i class="fa fa-check"></i>HAR-RVモデルによる予測</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#共分散相関の推定"><i class="fa fa-check"></i><b>13.2</b> 共分散・相関の推定</a>
<ul>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#データセット2-株価指数先物データ"><i class="fa fa-check"></i>データセット2: 株価指数先物データ</a></li>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#共分散相関の推定-1"><i class="fa fa-check"></i>共分散・相関の推定</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#acdモデル"><i class="fa fa-check"></i><b>13.3</b> ACDモデル</a>
<ul>
<li class="chapter" data-level="" data-path="高頻度データ分析.html"><a href="高頻度データ分析.html#補足-等間隔データを作成するための方法"><i class="fa fa-check"></i>補足: 等間隔データを作成するための方法</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix 参考文献</b></span></li>
<li class="chapter" data-level="A" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html"><i class="fa fa-check"></i><b>A</b> バブル (生成・崩壊) 検出</a>
<ul>
<li class="chapter" data-level="A.1" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#検定法に関する最近のレビュー論文"><i class="fa fa-check"></i><b>A.1</b> 検定法に関する最近のレビュー論文</a></li>
<li class="chapter" data-level="A.2" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#supreme-adf検定sadf-pwy-2011-generalized-supreme-adf-検定gsadf-psy-2015"><i class="fa fa-check"></i><b>A.2</b> Supreme ADF検定/SADF (PWY, 2011), Generalized supreme ADF 検定/GSADF (PSY, 2015)</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#数理ファイナンス-jarrow-protterら"><i class="fa fa-check"></i><b>A.2.1</b> 数理ファイナンス (Jarrow, Protterら)</a></li>
<li class="chapter" data-level="A.2.2" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#経済物理学-sornetteら"><i class="fa fa-check"></i><b>A.2.2</b> 経済物理学 (Sornetteら)</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#実証分析"><i class="fa fa-check"></i><b>A.3</b> 実証分析</a>
<ul>
<li class="chapter" data-level="" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#株式市場の例"><i class="fa fa-check"></i>株式市場の例</a></li>
<li class="chapter" data-level="" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#暗号資産市場の例"><i class="fa fa-check"></i>暗号資産市場の例</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html"><i class="fa fa-check"></i><b>B</b> 長期記憶過程</a>
<ul>
<li class="chapter" data-level="B.1" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#理論概説"><i class="fa fa-check"></i><b>B.1</b> 理論・概説</a></li>
<li class="chapter" data-level="B.2" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#株式市場"><i class="fa fa-check"></i><b>B.2</b> 株式市場</a></li>
<li class="chapter" data-level="B.3" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#外国為替市場"><i class="fa fa-check"></i><b>B.3</b> 外国為替市場</a></li>
<li class="chapter" data-level="B.4" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#コモディティ暗号資産"><i class="fa fa-check"></i><b>B.4</b> コモディティ・暗号資産</a></li>
<li class="chapter" data-level="B.5" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#vix"><i class="fa fa-check"></i><b>B.5</b> VIX</a></li>
<li class="chapter" data-level="B.6" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#高頻度データ-ボラティリティ-注文フロー等"><i class="fa fa-check"></i><b>B.6</b> 高頻度データ (ボラティリティ, 注文フロー等)</a></li>
<li class="chapter" data-level="B.7" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#長期記憶性の発生要因-非長期記憶モデルによる近似"><i class="fa fa-check"></i><b>B.7</b> 長期記憶性の発生要因, 非長期記憶モデルによる近似</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html"><i class="fa fa-check"></i><b>C</b> Markov switching/ regime switchingモデル</a>
<ul>
<li class="chapter" data-level="C.1" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#理論概説-1"><i class="fa fa-check"></i><b>C.1</b> 理論・概説</a></li>
<li class="chapter" data-level="C.2" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#株式市場-1"><i class="fa fa-check"></i><b>C.2</b> 株式市場</a></li>
<li class="chapter" data-level="C.3" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#金利債券市場"><i class="fa fa-check"></i><b>C.3</b> 金利・債券市場</a></li>
<li class="chapter" data-level="C.4" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#外国為替市場-1"><i class="fa fa-check"></i><b>C.4</b> 外国為替市場</a></li>
<li class="chapter" data-level="C.5" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#アセットアロケーション"><i class="fa fa-check"></i><b>C.5</b> アセット・アロケーション</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html"><i class="fa fa-check"></i><b>D</b> ARCH/GARCHモデル</a>
<ul>
<li class="chapter" data-level="D.1" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#概説"><i class="fa fa-check"></i><b>D.1</b> 概説</a></li>
<li class="chapter" data-level="D.2" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#arch-model"><i class="fa fa-check"></i><b>D.2</b> ARCH model</a></li>
<li class="chapter" data-level="D.3" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#garch-model"><i class="fa fa-check"></i><b>D.3</b> GARCH model</a></li>
<li class="chapter" data-level="D.4" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#arch-m-model"><i class="fa fa-check"></i><b>D.4</b> ARCH-M Model</a></li>
<li class="chapter" data-level="D.5" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#gjr-model"><i class="fa fa-check"></i><b>D.5</b> GJR model</a></li>
<li class="chapter" data-level="D.6" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#aparch-model"><i class="fa fa-check"></i><b>D.6</b> APARCH model</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html"><i class="fa fa-check"></i><b>E</b> 共和分/ 誤差修正モデル</a>
<ul>
<li class="chapter" data-level="E.1" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html#株式市場とマクロ変数-国際株式市場間の分析"><i class="fa fa-check"></i><b>E.1</b> 株式市場とマクロ変数, 国際株式市場間の分析</a></li>
<li class="chapter" data-level="E.2" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html#個別株式の複数取引所株価間の分析"><i class="fa fa-check"></i><b>E.2</b> 個別株式の複数取引所株価間の分析</a></li>
<li class="chapter" data-level="E.3" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html#高頻度データ-bidask価格-の分析"><i class="fa fa-check"></i><b>E.3</b> 高頻度データ (bid/ask価格) の分析</a></li>
<li class="chapter" data-level="E.4" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html#統計的アービトラージ-ペアトレード"><i class="fa fa-check"></i><b>E.4</b> 統計的アービトラージ / ペアトレード</a></li>
<li class="chapter" data-level="E.5" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html#国際株式市場間のヘッジ"><i class="fa fa-check"></i><b>E.5</b> 国際株式市場間のヘッジ</a></li>
<li class="chapter" data-level="E.6" data-path="共和分-誤差修正モデル.html"><a href="共和分-誤差修正モデル.html#クレジットスプレッド-株式-cds-債券-の分析"><i class="fa fa-check"></i><b>E.6</b> クレジット・スプレッド (株式, CDS, 債券) の分析</a></li>
</ul></li>
<li class="chapter" data-level="F" data-path="今後の学習のために.html"><a href="今後の学習のために.html"><i class="fa fa-check"></i><b>F</b> 今後の学習のために</a>
<ul>
<li class="chapter" data-level="F.1" data-path="今後の学習のために.html"><a href="今後の学習のために.html#ai機械学習と時系列解析"><i class="fa fa-check"></i><b>F.1</b> AI/機械学習と時系列解析</a></li>
<li class="chapter" data-level="F.2" data-path="今後の学習のために.html"><a href="今後の学習のために.html#カテゴリーデータや整数値データ等に対する時系列解析"><i class="fa fa-check"></i><b>F.2</b> カテゴリーデータや整数値データ等に対する時系列解析</a></li>
<li class="chapter" data-level="F.3" data-path="今後の学習のために.html"><a href="今後の学習のために.html#状態空間モデル動的線形モデル"><i class="fa fa-check"></i><b>F.3</b> 状態空間モデル・動的線形モデル</a></li>
<li class="chapter" data-level="F.4" data-path="今後の学習のために.html"><a href="今後の学習のために.html#その他"><i class="fa fa-check"></i><b>F.4</b> その他</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">金融時系列解析</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="共和分分析" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> 共和分分析<a href="共和分分析.html#共和分分析" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>共和分 (cointegration) と誤差修正モデル (error correction model, ECM) は,
非定常な時系列データを扱う際に重要な概念・手法である.</p>
<p>長期的な均衡関係と短期的な修正のプロセスを同時にモデル化する枠組みを提供し,
経済・金融分野で広く応用されている.</p>
<p>例として, 長短金利, 関連する商品価格のペア (例, ガソリン vs 原油), 家計の消費と所得, 為替レートと物価指数 (購買力平価説), …など.</p>
<p>個々には非定常だが, 連動して動く時系列に関する経済理論の実証分析に有用である.</p>
<p>2003年, Grangerは共和分に関する研究によりノーベル経済学賞を受賞した (ARCHを提案したEngleと同時受賞).</p>
<div id="共和分分析の手順" class="section level4 unnumbered hasAnchor">
<h4>共和分分析の手順<a href="共和分分析.html#共和分分析の手順" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>概ね以下のような流れで行われる (幾つかの要素は前後するか繰り返し行われることがある).</p>
<ul>
<li><strong>ステップ1：単位根検定</strong>
<ul>
<li>単位根検定 (Augmented Dickey-Fuller検定など) を用いて, 各時系列が非定常であるかを検定する</li>
<li>変数が同じ次数（通常 <span class="math inline">\(I(1)\)</span>）の和分過程であることを確認する.</li>
<li>変数の和分の次数が異なる場合は, 次数を揃えるか, 別のアプローチを検討する</li>
<li>※) 単位根検定に際しては, 適切な確定項（定数項と線形トレンド) やラグ次数の選択を行う (時系列プロットやACFのコレログラム, AIC/BIC等の情報量基準等を利用)</li>
</ul></li>
<li><strong>ステップ2：共和分検定</strong>
<ul>
<li>適切な検定方法を選択する：
<ul>
<li>(共和分関係が一つの場合) Engle-Granger検定, Philips-Ouliaris検定</li>
<li>(共和分関係が複数あることが推察される場合) Johansen検定</li>
</ul></li>
<li>確定項（定数項と線形トレンド) やラグ次数について適切なモデル仕様を特定する</li>
<li>共和分検定を実行し, 共和分関係の有無 (数) を決定する</li>
</ul></li>
<li><strong>ステップ3：ECMモデルの推定</strong>
<ul>
<li>誤差修正モデル (ECM) を推定する
<ul>
<li>長期的 (均衡) 関係 (共和分ベクトル) の推定</li>
<li>短期的な調整スピードの推定</li>
</ul></li>
</ul></li>
<li><strong>ステップ4: モデル診断</strong>
<ul>
<li>共和分方程式の残差 (誤差) をチェック (ステップ2の中でも)</li>
<li>ECMの残差をチェック (自己相関, 多変量ARCH効果, 正規性等)</li>
<li>パラメータの安定性をチェック</li>
<li>必要に応じてステップ1–3に戻る</li>
</ul></li>
<li><strong>ステップ5: モデルの解釈</strong>
<ul>
<li>推定されたモデルを解釈する. 予想や直感に反しないか?</li>
<li>含意・洞察を引き出す</li>
</ul></li>
</ul>
<!-- 多変量にまとめたVAR($p$)に対するAIC/BIC -->
<ul>
<li><strong>モデリング上の留意点</strong>
<ul>
<li>モデルの仕様
<ul>
<li>確定項（定数, トレンド）の選択は検定統計量の分布 (→ 検定結果) に影響</li>
<li>ラグ長の選択も重要</li>
</ul></li>
<li>検定の前提条件
<ul>
<li>データ生成に構造的な変化がないか</li>
<li>サンプル・サイズは十分大きいか, 等</li>
</ul></li>
</ul></li>
</ul>
<!--    (Johansen検定の信頼性) -->
</div>
<div id="共和分ecmの応用上の留意点" class="section level4 unnumbered hasAnchor">
<h4>共和分・ECMの応用上の留意点<a href="共和分分析.html#共和分ecmの応用上の留意点" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>共和分・ECMの方法論を実践する場合には, 時間軸の不明瞭さに注意を払う必要がある.</p>
<ul>
<li>共和分における「長期的」均衡は, 実際にどの程度の期間がかかって実現されるかについて提示しない.</li>
<li>ECMにおける「短期的」修正は, 単位時間あたりに不均衡が修正される割合 (スピード) を示すだけで, 実際に均衡水準まで修正される保証はない</li>
</ul>
<!-- コミュニケーションと意思決定のギャップ：
    - 現実世界での意思決定には、より具体的なタイミングや大きさの感覚が必要となることが多い。ECMは政策立案者や管理者に、介入の効果がどれくらいの期間で現れるかについて不確実性を残す可能性がある。
- **モデル破綻のリスク**：
  - 当然ながら, マクロ経済経済の変化, 政策転換, 技術革新等があれば, 一度有効であった共和分関係は失われる可能性大 共和分による「平均回帰」への過信は, 事業戦略や政策のずれを生じる可能性
  - 共分散関係を前提にした戦略を実践する場合には, 変数やラグ長など, 継続的な見直し作業が必要
-->
</div>
<div id="見せかけの回帰-再掲" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> 見せかけの回帰 (再掲)<a href="共和分分析.html#見せかけの回帰-再掲" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>-「5.2 単位根検定と見せかけの回帰」の内容 (再掲)
<!--
- 参考: 福地・伊藤, 10.1
--></p>
<p>単位根過程<span class="math inline">\(y_{t}\)</span>を, 定数と<span class="math inline">\(y_{t}\)</span>と``関係’’ (共和分関係) のない単位根過程<span class="math inline">\(x_{t}\)</span>に対して回帰すると, <span class="math inline">\(x_{t}\)</span>と<span class="math inline">\(y_{t}\)</span>の間に有意な関係があり, 回帰の説明力が高いように見える現象が生じることが知られている.
これを, <strong>見せかけの回帰 (spurious regression)</strong> と呼ぶ.</p>
<div class="sourceCode" id="cb808"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb808-1"><a href="共和分分析.html#cb808-1" tabindex="-1"></a>tlen <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb808-2"><a href="共和分分析.html#cb808-2" tabindex="-1"></a>seedv <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb808-3"><a href="共和分分析.html#cb808-3" tabindex="-1"></a><span class="fu">set.seed</span>(seedv)</span>
<span id="cb808-4"><a href="共和分分析.html#cb808-4" tabindex="-1"></a>w1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(tlen)</span>
<span id="cb808-5"><a href="共和分分析.html#cb808-5" tabindex="-1"></a>w2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(tlen)</span>
<span id="cb808-6"><a href="共和分分析.html#cb808-6" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(w1)</span>
<span id="cb808-7"><a href="共和分分析.html#cb808-7" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(w2)</span>
<span id="cb808-8"><a href="共和分分析.html#cb808-8" tabindex="-1"></a><span class="fu">matplot</span>(<span class="fu">cbind</span>(x,y), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/spur_reg_15-1.png" width="672" /></p>
<div class="sourceCode" id="cb809"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb809-1"><a href="共和分分析.html#cb809-1" tabindex="-1"></a>reslm <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb809-2"><a href="共和分分析.html#cb809-2" tabindex="-1"></a><span class="fu">summary</span>(reslm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.0778 -3.6190  0.0812  3.9438  8.6039 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  0.13230    0.55381   0.239   0.8114  
## x            0.16810    0.06713   2.504   0.0128 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.284 on 298 degrees of freedom
## Multiple R-squared:  0.02061,    Adjusted R-squared:  0.01733 
## F-statistic: 6.272 on 1 and 298 DF,  p-value: 0.0128</code></pre>
<div class="sourceCode" id="cb811"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb811-1"><a href="共和分分析.html#cb811-1" tabindex="-1"></a><span class="fu">plot</span>(x, y); <span class="fu">abline</span>(reslm, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/spur_reg_15-2.png" width="672" /></p>
<ul>
<li>残差に自己相関が残ることの確認</li>
</ul>
<div class="sourceCode" id="cb812"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb812-1"><a href="共和分分析.html#cb812-1" tabindex="-1"></a>reslm_resid <span class="ot">=</span> <span class="fu">resid</span>(reslm)</span>
<span id="cb812-2"><a href="共和分分析.html#cb812-2" tabindex="-1"></a><span class="fu">plot</span>(reslm_resid, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<div class="sourceCode" id="cb813"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb813-1"><a href="共和分分析.html#cb813-1" tabindex="-1"></a><span class="fu">acf</span>(reslm_resid)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<div id="durbin-watson検定" class="section level3 unnumbered hasAnchor">
<h3>Durbin-Watson検定<a href="共和分分析.html#durbin-watson検定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Durbin-Watson検定 (簡便法)
<ul>
<li>回帰残差の系列相関の有無を検定</li>
<li><span class="math inline">\(DW \approx 2(1-\rho)\)</span></li>
<li><span class="math inline">\(0&lt;DW&lt;4\)</span>. 無相関 <span class="math inline">\(\Leftrightarrow DW=2\)</span></li>
<li>見せかけの回帰の場合. DWが小さい傾向 (正の系列相関)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb814"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb814-1"><a href="共和分分析.html#cb814-1" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode" id="cb818"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb818-1"><a href="共和分分析.html#cb818-1" tabindex="-1"></a><span class="fu">dwtest</span>(reslm)</span></code></pre></div>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  reslm
## DW = 0.060411, p-value &lt; 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<ul>
<li>代替法: Engle-Granger検定</li>
</ul>
</div>
<div id="rで実行可能な主な単位根検定法-1" class="section level3 unnumbered hasAnchor">
<h3>Rで実行可能な主な単位根検定法<a href="共和分分析.html#rで実行可能な主な単位根検定法-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>ADF検定: <strong>tseries</strong>内, <code>adf.test()</code>; <strong>fUnitRoots</strong>内, <code>unitrootTest()</code>, <code>adfTest()</code></li>
<li>Phillips-Perron(PP)検定: <strong>urca</strong>内, <code>ur.pp()</code>; <strong>tseries</strong>内, <code>pp.test()</code>
<ul>
<li>PP検定は, 沖本, pp.118–120参照</li>
</ul></li>
<li>KPSS検定: <strong>urca</strong>内, <code>ur.kpss()</code>; <strong>tseries</strong>内, <code>kpss.test()</code>
<ul>
<li>KPSS検定は, 福地・伊藤, pp.139–140参照</li>
</ul></li>
<li>その他の検定法: <strong>fUnitRoots</strong>内, <code>urersTest()</code> (Elliott-Rothenberg-Stock検定), <code>urspTest()</code> (Schmidt-Phillips検定), <code>urzaTest()</code> (Zivot-Andrews), 等</li>
</ul>
</div>
</div>
<div id="共和分分析-1" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> 共和分分析<a href="共和分分析.html#共和分分析-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>共和分分析の代表的な方法として,
OLS回帰の残差をベースにしたEngle-Grangerの方法と,
VARモデル (および多変量解析の一種である正準相関分析) をベースにしたJohansenの方法がある.</p>
<p>手順としては, 共和分関係を調べたい各変数が非定常であるかどうかを
単位根検定を使って確認することから始まる.
各変数が全て非定常である (通常は, <span class="math inline">\(I(1)\)</span>) ことを確認した後,
変数間の共和分関係の有無やその本数を共和分検定法を使って調べる.
検定結果と共に, 共和分関係を記述する共和分ベクトルの推定値が得られる.</p>
<!---
- Engle–Granger (EG) 二段階法：共和分関係が想定される変数同士の回帰式の残差の定常性を調べることで共和分関係の有無を判断. 共和分ベクトルは回帰係数の推定値から直ちに得られる
- Johansen検定：VARモデルに基づき, 潜在的に複数ある共和分関係の個数を検定し, 同時に共和分ベクトルを推定する方法
- Phillips–Ouliaris検定：EG法を改良した方法
--->
<p>以下では, 沖本 (問題6.3, p.144) の設定を例に取り, 4系列 <span class="math inline">\({\bf y}_t=(y_{1,t},y_{2,t},y_{3,t},y_{4,t})&#39;\)</span> に対する共和分分析を行う</p>
<ul>
<li><span class="math inline">\(w_{1,t},w_{2,t}\)</span>は, 互いに独立な単位根過程</li>
<li><span class="math inline">\(u_{1,t},u_{2,t},u_{3,t},u_{4,t}\)</span>は互いに独立な定常過程. <span class="math inline">\(w_{1,t},w_{2,t}\)</span>とも独立</li>
</ul>
<p><span class="math display">\[
\left\{
\begin{split}
y_{1,t} &amp;= w_{1,t}+u_{1,t}    \\
y_{2,t} &amp;= 2 w_{1,t} + u_{1,t}  \\
y_{3,t} &amp;= w_{2,t} + u_{3,t}    \\
y_{4,t} &amp;= w_{1,t}+ 2 w_{2,t} + u_{4,t}
\end{split}
\right.
\]</span></p>
<p>この時, 直ちに線形独立な共和分ベクトル <span class="math inline">\(\beta_1 = (1,-0.5,0,0)\)</span>, <span class="math inline">\(\beta_2 = (1,0,2,-1)\)</span> が得られる. 任意の共和分ベクトルは<span class="math inline">\(\beta_1,\beta_2\)</span>の線形和で表現される.</p>
<p>以下では, Rを使って, 正規乱数によりサンプルパスを生成する (長さ=300)</p>
<div class="sourceCode" id="cb820"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb820-1"><a href="共和分分析.html#cb820-1" tabindex="-1"></a>tlen <span class="ot">&lt;-</span> <span class="dv">300</span> <span class="co"># 任意に変更可</span></span>
<span id="cb820-2"><a href="共和分分析.html#cb820-2" tabindex="-1"></a>seedv <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># 任意に変更可</span></span>
<span id="cb820-3"><a href="共和分分析.html#cb820-3" tabindex="-1"></a><span class="fu">set.seed</span>(seedv)</span>
<span id="cb820-4"><a href="共和分分析.html#cb820-4" tabindex="-1"></a>w1 <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">rnorm</span>(tlen))</span>
<span id="cb820-5"><a href="共和分分析.html#cb820-5" tabindex="-1"></a>w2 <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">rnorm</span>(tlen))</span>
<span id="cb820-6"><a href="共和分分析.html#cb820-6" tabindex="-1"></a>u1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(tlen); u2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(tlen)</span>
<span id="cb820-7"><a href="共和分分析.html#cb820-7" tabindex="-1"></a>u3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(tlen); u4 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(tlen)</span>
<span id="cb820-8"><a href="共和分分析.html#cb820-8" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb820-9"><a href="共和分分析.html#cb820-9" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> w1 <span class="sc">+</span> u1</span>
<span id="cb820-10"><a href="共和分分析.html#cb820-10" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> w1 <span class="sc">+</span> u2</span>
<span id="cb820-11"><a href="共和分分析.html#cb820-11" tabindex="-1"></a>y3 <span class="ot">&lt;-</span> w2 <span class="sc">+</span> u3</span>
<span id="cb820-12"><a href="共和分分析.html#cb820-12" tabindex="-1"></a>y4 <span class="ot">&lt;-</span> w1 <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> w2 <span class="sc">+</span> u4</span>
<span id="cb820-13"><a href="共和分分析.html#cb820-13" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb820-14"><a href="共和分分析.html#cb820-14" tabindex="-1"></a><span class="co"># beta1 = (1, -0.5, 0, 0)</span></span>
<span id="cb820-15"><a href="共和分分析.html#cb820-15" tabindex="-1"></a><span class="co"># beta2 = (1, 0, 2, -1)</span></span>
<span id="cb820-16"><a href="共和分分析.html#cb820-16" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb820-17"><a href="共和分分析.html#cb820-17" tabindex="-1"></a>ymat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(y1, y2, y3, y4)</span>
<span id="cb820-18"><a href="共和分分析.html#cb820-18" tabindex="-1"></a><span class="fu">matplot</span>(ymat, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>まず, 各成分が単位根過程 <span class="math inline">\(I(1)\)</span> であることを確認する</p>
<div class="sourceCode" id="cb821"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb821-1"><a href="共和分分析.html#cb821-1" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(y1)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -0.1277
##   P VALUE:
##     0.5756 
## 
## Description:
##  Sun Feb  2 15:37:16 2025 by user:</code></pre>
<div class="sourceCode" id="cb823"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb823-1"><a href="共和分分析.html#cb823-1" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(y2)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: 0.1048
##   P VALUE:
##     0.6497 
## 
## Description:
##  Sun Feb  2 15:37:16 2025 by user:</code></pre>
<div class="sourceCode" id="cb825"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb825-1"><a href="共和分分析.html#cb825-1" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(y3)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -0.1246
##   P VALUE:
##     0.5766 
## 
## Description:
##  Sun Feb  2 15:37:16 2025 by user:</code></pre>
<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb827-1"><a href="共和分分析.html#cb827-1" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(y4)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -0.7516
##   P VALUE:
##     0.3768 
## 
## Description:
##  Sun Feb  2 15:37:16 2025 by user:</code></pre>
<div id="englegrangerの方法-philips-ouliaris検定" class="section level3 unnumbered hasAnchor">
<h3>Engle–Grangerの方法 (Philips-Ouliaris検定)<a href="共和分分析.html#englegrangerの方法-philips-ouliaris検定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>共和分検定の方法の一つであるPhilips-Ouliaris検定は,
共和分関係が想定される非定常な時系列同士のOLS回帰の残差の定常性を調べることで, これらの間の (一つの) 共和分関係の有無を判断するEngle–Grangerの検定法を改良したものである.</p>
<!--
TH122724 (執筆中)
### Engle-Grangerの2段階法 {-}

Engle and Granger (87) により提案された最も古典的な共和分検定方法の一つで, 以下の2ステップからなる.

(1) まず, 共和分関係を調べたい系列が非定常である ($I(1)$過程) ことを
単位根検定法を用いて確認する. 

(2) 時系列 $y_t$ と $x_t$ に対して, 以下の回帰を行う (ここでは説明変数は1つと仮定)：

\[
y_t = \alpha + \beta x_t + u_t.
\]

得られた残差系列$\hat{u}_t = y_t - \hat{\beta}_0 - \hat{\beta}_1 x_t$に対して 単位根検定を行い, 定常性をチェックする.
もし これが定常 ($I(0)$) と判断されれば, $y_t$ と $x_t$ は共和分関係にあると結論付けられる (回帰係数として推定値が使われることから通常の単位根検定とは異なる棄却域を持つ).

第1ステップで共和分関係が確認されたら, 第2ステップとして、次の回帰が行われる.
すなわち, $\Delta y_t$に対して, $\Delta x_t$ と 第1ステップの回帰残差の
ラグ $\hat{u}_{t-1}$ を回帰し, 係数$\alpha$の有意性を調べる.
\[
\Delta y_t = b \Delta x_t + \alpha \hat{u}_{t-1} + \epsilon_t.
\]
$y_t$ と $x_t$の間に共和分関係がなければ, $\alpha = 0$となる
--->
<p>Philips-Ouliaris検定はRパッケージの<strong>urca</strong>に含まれる関数<code>ca.po()</code>で実行
することができる.</p>
<pre><code>- urca::ca.po()
  - demean (使用するランダムウォーク・モデルのトレンドの指定): &quot;none&quot;, &quot;const&quot;(定数項), &quot;trend&quot;(定数項+時間トレンド)
  - type (検定種類): &quot;Pu&quot;(デフォルト), &quot;Pz&quot;</code></pre>
<div class="sourceCode" id="cb830"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb830-1"><a href="共和分分析.html#cb830-1" tabindex="-1"></a><span class="fu">library</span>(urca)</span>
<span id="cb830-2"><a href="共和分分析.html#cb830-2" tabindex="-1"></a>test_po <span class="ot">&lt;-</span> <span class="fu">ca.po</span>(ymat[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">demean =</span> <span class="st">&quot;const&quot;</span>)</span>
<span id="cb830-3"><a href="共和分分析.html#cb830-3" tabindex="-1"></a><span class="fu">summary</span>(test_po)</span></code></pre></div>
<pre><code>## 
## ######################################## 
## # Phillips and Ouliaris Unit Root Test # 
## ######################################## 
## 
## Test of type Pu 
## detrending of series with constant only 
## 
## 
## Call:
## lm(formula = z[, 1] ~ z[, -1])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.6576 -0.7442 -0.0535  0.7229  3.7571 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.552717   0.180515  -3.062   0.0024 ** 
## z[, -1]      0.485335   0.004978  97.500   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.114 on 298 degrees of freedom
## Multiple R-squared:  0.9696, Adjusted R-squared:  0.9695 
## F-statistic:  9506 on 1 and 298 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: 250.2856 
## 
## Critical values of Pu are:
##                   10pct   5pct    1pct
## critical values 27.8536 33.713 48.0021</code></pre>
<ul>
<li>→ 帰無仮説棄却. y1とy2には共和分関係あり
生成された時系列データによる係数の推定値は0.495997,
すなわち, 推定された共和分ベクトルは<span class="math inline">\((1, -0.50)\)</span>である (小数点以下第三位を四捨五入)</li>
</ul>
<p>実際, 真のモデルは, <span class="math inline">\(2 y_{1,t} - y_{2,t}  = 2 u_{1,t} - u_{t,2} \sim I(0)\)</span>, すなわち,
理論的には, 2変数<span class="math inline">\((y_{1,t}, y_{2,t})\)</span>は, <span class="math inline">\((1, -0.5)\)</span>の共和分ベクトルとする共和分関係にあった</p>
<p>念のために残差の自己相関を確認する.</p>
<div class="sourceCode" id="cb832"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb832-1"><a href="共和分分析.html#cb832-1" tabindex="-1"></a><span class="co"># 残差診断</span></span>
<span id="cb832-2"><a href="共和分分析.html#cb832-2" tabindex="-1"></a><span class="fu">plot</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb833"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb833-1"><a href="共和分分析.html#cb833-1" tabindex="-1"></a><span class="fu">acf</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<div class="sourceCode" id="cb834"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb834-1"><a href="共和分分析.html#cb834-1" tabindex="-1"></a><span class="fu">Box.test</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## 
##  Box-Pierce test
## 
## data:  test_po@testreg$residuals
## X-squared = 1.9295, df = 1, p-value = 0.1648</code></pre>
<p>次に<span class="math inline">\(y_{1,t}, y_{3,t}\)</span>の関係性を調べる.</p>
<div class="sourceCode" id="cb836"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb836-1"><a href="共和分分析.html#cb836-1" tabindex="-1"></a>test_po <span class="ot">&lt;-</span> <span class="fu">ca.po</span>(ymat[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)], <span class="at">demean =</span> <span class="st">&quot;const&quot;</span>)</span>
<span id="cb836-2"><a href="共和分分析.html#cb836-2" tabindex="-1"></a><span class="fu">summary</span>(test_po)</span></code></pre></div>
<pre><code>## 
## ######################################## 
## # Phillips and Ouliaris Unit Root Test # 
## ######################################## 
## 
## Test of type Pu 
## detrending of series with constant only 
## 
## 
## Call:
## lm(formula = z[, 1] ~ z[, -1])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.706  -3.851   1.099   4.190  11.736 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -5.79847    1.11523  -5.199 3.72e-07 ***
## z[, -1]     -0.63880    0.06101 -10.470  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.463 on 298 degrees of freedom
## Multiple R-squared:  0.2689, Adjusted R-squared:  0.2665 
## F-statistic: 109.6 on 1 and 298 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: 17.1324 
## 
## Critical values of Pu are:
##                   10pct   5pct    1pct
## critical values 27.8536 33.713 48.0021</code></pre>
<ul>
<li>–&gt; 1%有意水準では帰無仮説棄却されず (y1とy3には共和分関係なし)
しかし, 5%水準では棄却 (y1とy3には共和分関係あり)</li>
</ul>
<div class="sourceCode" id="cb838"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb838-1"><a href="共和分分析.html#cb838-1" tabindex="-1"></a><span class="co"># 残差診断</span></span>
<span id="cb838-2"><a href="共和分分析.html#cb838-2" tabindex="-1"></a><span class="fu">plot</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb839"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb839-1"><a href="共和分分析.html#cb839-1" tabindex="-1"></a><span class="fu">acf</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb840-1"><a href="共和分分析.html#cb840-1" tabindex="-1"></a><span class="fu">Box.test</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## 
##  Box-Pierce test
## 
## data:  test_po@testreg$residuals
## X-squared = 256.9, df = 1, p-value &lt; 2.2e-16</code></pre>
<ul>
<li>–&gt; 残差に強い相関がある. 見せかけの回帰が生じていたことを示唆</li>
</ul>
<p>実際, 真のモデルでは, <span class="math inline">\(y_{1,t}\)</span>と<span class="math inline">\(y_{2,t}\)</span>は独立であったことから,
両者間の回帰の有意性は見せかけの回帰現象であった</p>
<p>この例は, <code>ca.po()</code>の出力のみで判断するのでは間違った判断をくだす
可能性もあることを示している. 残差系列の自己相関を調べるなど 見せかけの回帰が生じていないかを同時にチェックすることがのぞましい.</p>
<p>念のため, 線形トレンドを指定した場合を実行</p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="共和分分析.html#cb842-1" tabindex="-1"></a>test_po <span class="ot">&lt;-</span> <span class="fu">ca.po</span>(ymat[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)], <span class="at">demean =</span> <span class="st">&quot;trend&quot;</span>)</span>
<span id="cb842-2"><a href="共和分分析.html#cb842-2" tabindex="-1"></a><span class="fu">summary</span>(test_po)</span></code></pre></div>
<pre><code>## 
## ######################################## 
## # Phillips and Ouliaris Unit Root Test # 
## ######################################## 
## 
## Test of type Pu 
## detrending of series with constant and linear trend 
## 
## 
## Call:
## lm(formula = z[, 1] ~ z[, -1] + trd)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.4928 -2.2329  0.0158  2.3622  8.2619 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -5.127606   0.683837  -7.498 7.51e-13 ***
## z[, -1]     -0.192680   0.042395  -4.545 8.01e-06 ***
## trd         -0.056427   0.002531 -22.296  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.347 on 297 degrees of freedom
## Multiple R-squared:  0.7266, Adjusted R-squared:  0.7247 
## F-statistic: 394.6 on 2 and 297 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: 57.3364 
## 
## Critical values of Pu are:
##                   10pct    5pct    1pct
## critical values 41.2488 48.8439 65.1714</code></pre>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="共和分分析.html#cb844-1" tabindex="-1"></a><span class="co"># 残差診断</span></span>
<span id="cb844-2"><a href="共和分分析.html#cb844-2" tabindex="-1"></a><span class="fu">plot</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="共和分分析.html#cb845-1" tabindex="-1"></a><span class="fu">acf</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="095-coint_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb846-1"><a href="共和分分析.html#cb846-1" tabindex="-1"></a><span class="fu">Box.test</span>(test_po<span class="sc">@</span>testreg<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## 
##  Box-Pierce test
## 
## data:  test_po@testreg$residuals
## X-squared = 217.59, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>すなわち, 先に行った<code>demean = "const"</code>と同じ結論が得られる</p>
</div>
<div id="johansenの方法" class="section level3 unnumbered hasAnchor">
<h3>Johansenの方法<a href="共和分分析.html#johansenの方法" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Johansen (88) によって提案されたVARモデルに基づく手法で,
複数の時系列間に存在し得る共和分関係の数やベクトルを同時に推定できる</p>
<p>前提条件として, 観測時系列がGaussian VAR(<span class="math inline">\(p\)</span>)に従うことを想定する.</p>
<p>上記のEngle-Granger等の回帰ベースのアプローチとは異なり,
目的変数・説明変数を区別しない対称的なアプローチである.
Johansen検定は, 理論的にはもとのVAR(<span class="math inline">\(p\)</span>)モデルを誤差修正モデル (ECM)
表現する際に得られる係数行列<span class="math inline">\(\Pi\)</span>の性質を用いて行われる検定方法である.
最大固有値検定とトレース検定の2種類がある.</p>
<p>Rパッケージ<strong>urca</strong>内の関数<code>ca.jo()</code>により実行することができる.</p>
<p>上で生成したデータ行列<code>ymat</code>は, レベル変数でVAR(<span class="math inline">\(p\)</span>)のラグ<span class="math inline">\(p=1\)</span>を持っている.
一方, 確定項は持っていなかった.</p>
<p>確認のため, 最適な次数<span class="math inline">\(p\)</span>の大きさを情報量基準を使って選択させると,
次のようになる:</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb848-1"><a href="共和分分析.html#cb848-1" tabindex="-1"></a><span class="co"># library(vars)</span></span>
<span id="cb848-2"><a href="共和分分析.html#cb848-2" tabindex="-1"></a>vars<span class="sc">::</span><span class="fu">VARselect</span>(ymat)</span></code></pre></div>
<pre><code>## $selection
## AIC(n)  HQ(n)  SC(n) FPE(n) 
##      1      1      1      1 
## 
## $criteria
##                1         2         3         4         5         6         7
## AIC(n)  4.210712  4.255809  4.318613  4.384505  4.459940  4.527443  4.599661
## HQ(n)   4.312115  4.438333  4.582259  4.729273  4.885831  5.034455  5.187795
## SC(n)   4.463807  4.711380  4.976661  5.245029  5.522940  5.792919  6.067613
## FPE(n) 67.405451 70.519454 75.102470 80.241682 86.570243 92.680559 99.717711
##                 8          9         10
## AIC(n)   4.643317   4.687902   4.743021
## HQ(n)    5.312574   5.438280   5.574522
## SC(n)    6.313746   6.560806   6.818402
## FPE(n) 104.300641 109.234243 115.659305</code></pre>
<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb850-1"><a href="共和分分析.html#cb850-1" tabindex="-1"></a><span class="co"># library(MTS)</span></span>
<span id="cb850-2"><a href="共和分分析.html#cb850-2" tabindex="-1"></a>MTS<span class="sc">::</span><span class="fu">VARorder</span>(ymat)</span></code></pre></div>
<pre><code>## selected order: aic =  1 
## selected order: bic =  1 
## selected order: hq =  1 
## Summary table:  
##        p    AIC    BIC     HQ      M(p) p-value
##  [1,]  0 9.5143 9.5143 9.5143    0.0000  0.0000
##  [2,]  1 4.1487 4.3462 4.2277 1540.4422  0.0000
##  [3,]  2 4.1932 4.5882 4.3513   17.2556  0.3692
##  [4,]  3 4.2538 4.8464 4.4909   12.5987  0.7018
##  [5,]  4 4.3220 5.1122 4.6382   10.3463  0.8479
##  [6,]  5 4.3937 5.3814 4.7890    9.2848  0.9012
##  [7,]  6 4.4566 5.6419 4.9310   11.4398  0.7816
##  [8,]  7 4.5251 5.9078 5.0785    9.8422  0.8747
##  [9,]  8 4.5610 6.1413 5.1934   17.9336  0.3278
## [10,]  9 4.6057 6.3835 5.3172   15.4564  0.4915
## [11,] 10 4.6583 6.6336 5.4488   13.2842  0.6519
## [12,] 11 4.7242 6.8971 5.5938    9.8390  0.8749
## [13,] 12 4.7830 7.1534 5.7317   11.3701  0.7861
## [14,] 13 4.8310 7.3989 5.8587   13.7028  0.6208</code></pre>
<div class="sourceCode" id="cb852"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb852-1"><a href="共和分分析.html#cb852-1" tabindex="-1"></a><span class="co"># MTS::VARorderI(ymat) # 観測データとしてt=p+1,...,Tを使用して情報量基準を計算</span></span></code></pre></div>
<div id="最大固有値検定" class="section level4 unnumbered hasAnchor">
<h4>(1) 最大固有値検定<a href="共和分分析.html#最大固有値検定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><span class="math inline">\(H_0\)</span>: 共和分ランク<span class="math inline">\(=r\)</span>以下, <span class="math inline">\(H_1\)</span>: 共和分ランク<span class="math inline">\(=r+1\)</span></li>
</ul>
<pre><code>- urca::ca.jo():
  - type (検定の種類):   ‘eigen’(最大固有値検定) or ‘trace’(トレース検定)
  - ecdet (トレンド種類): ‘none’(切片項なし), ‘const’(定数項あり),‘trend’(トレンド項あり)
  - K (時系列(レベル変数)のVAR表現におけるラグ次数) (デフォルト=2)
  - spec (VECMの定式化の2つの方法の一つを選択): &quot;longrun&quot;(デフォルト), or &quot;transitory&quot;
  - season (季節ダミー): データの頻度を指定(例, 四半期の場合は4)</code></pre>
<!--
- $y_{1,t}$ vs $y_{2,t}$

- -> $r=0$棄却. $r=1$採択
  - -> $r=1$棄却されず　(TH: 変数=2, 最大次数=1 なのでr=1の検定は不要なはず!)
  - -> 共和分ベクトルの個数$=1$


- $y_{1,t}$ vs $y_{3,t}$

- -> 共和分ベクトルの個数 = 0
  - -> 共和分関係の有無はシステムに含まれる (分析対象の) 変数に依存する

-->
<ul>
<li>全変数に対して実行
レベル変数に対するラグ次数(<span class="math inline">\(p\)</span>)は引数<code>K</code>で指定する.
真の次数は<span class="math inline">\(p=1\)</span>であるがそのまま<code>K=1</code>と
<code>ca.jo()</code>に与えるとエラーを生じるため,
デフォルト (<code>K=2</code>) のままにしておく.</li>
</ul>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="共和分分析.html#cb854-1" tabindex="-1"></a>result_e1 <span class="ot">&lt;-</span> <span class="fu">ca.jo</span>(ymat, <span class="at">ecdet =</span> <span class="st">&quot;none&quot;</span>, <span class="at">type =</span> <span class="st">&quot;eigen&quot;</span>, <span class="at">spec =</span> <span class="st">&quot;longrun&quot;</span>)</span>
<span id="cb854-2"><a href="共和分分析.html#cb854-2" tabindex="-1"></a><span class="fu">summary</span>(result_e1)</span></code></pre></div>
<pre><code>## 
## ###################### 
## # Johansen-Procedure # 
## ###################### 
## 
## Test type: maximal eigenvalue statistic (lambda max) , with linear trend 
## 
## Eigenvalues (lambda):
## [1] 0.39399267 0.35373609 0.04001843 0.01669478
## 
## Values of teststatistic and critical values of test:
## 
##            test 10pct  5pct  1pct
## r &lt;= 3 |   5.02  6.50  8.18 11.65
## r &lt;= 2 |  12.17 12.91 14.90 19.19
## r &lt;= 1 | 130.09 18.90 21.07 25.75
## r = 0  | 149.26 24.78 27.14 32.14
## 
## Eigenvectors, normalised to first column:
## (These are the cointegration relations)
## 
##            y1.l2      y2.l2       y3.l2     y4.l2
## y1.l2  1.0000000  1.0000000  1.00000000  1.000000
## y2.l2 -0.6347789 -0.1341194  0.74761830 24.357249
## y3.l2 -0.5785340  1.4100169 -0.01803175 -6.710469
## y4.l2  0.2788528 -0.6893143 -1.62504044 48.535783
## 
## Weights W:
## (This is the loading matrix)
## 
##            y1.l2        y2.l2       y3.l2         y4.l2
## y1.d -0.51186630 -0.320181456 -0.00621887 -2.424265e-04
## y2.d  0.63903190  0.008777047 -0.01134031 -4.269731e-04
## y3.d  0.44326372 -0.453798733  0.01223929 -9.786591e-05
## y4.d -0.06251362  0.124762555  0.01714466 -5.047995e-04</code></pre>
<ul>
<li><span class="math inline">\(r=0\)</span>棄却. <span class="math inline">\(r \le 1\)</span>棄却, <span class="math inline">\(r \le 2\)</span>棄却されず.
<ul>
<li>→ 共和分ベクトルの個数<span class="math inline">\(=2\)</span></li>
</ul></li>
</ul>
<div id="トレース検定" class="section level5 unnumbered hasAnchor">
<h5>(2) トレース検定<a href="共和分分析.html#トレース検定" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ul>
<li><span class="math inline">\(H_0\)</span>: 共和分ランク<span class="math inline">\(=r\)</span>以下, <span class="math inline">\(H_1\)</span>: 共和分ランク<span class="math inline">\(=m\)</span> (原系列は定常)</li>
</ul>
<div class="sourceCode" id="cb856"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb856-1"><a href="共和分分析.html#cb856-1" tabindex="-1"></a>result_t1 <span class="ot">&lt;-</span> <span class="fu">ca.jo</span>(ymat, <span class="at">ecdet =</span> <span class="st">&quot;none&quot;</span>, <span class="at">type =</span> <span class="st">&quot;trace&quot;</span>, <span class="at">spec =</span> <span class="st">&quot;longrun&quot;</span>)</span>
<span id="cb856-2"><a href="共和分分析.html#cb856-2" tabindex="-1"></a><span class="co">#result_t1 &lt;- ca.jo(ymat, ecdet = &quot;const&quot;, type = &quot;trace&quot;, spec = &quot;longrun&quot;)</span></span>
<span id="cb856-3"><a href="共和分分析.html#cb856-3" tabindex="-1"></a><span class="fu">summary</span>(result_t1)</span></code></pre></div>
<pre><code>## 
## ###################### 
## # Johansen-Procedure # 
## ###################### 
## 
## Test type: trace statistic , with linear trend 
## 
## Eigenvalues (lambda):
## [1] 0.39399267 0.35373609 0.04001843 0.01669478
## 
## Values of teststatistic and critical values of test:
## 
##            test 10pct  5pct  1pct
## r &lt;= 3 |   5.02  6.50  8.18 11.65
## r &lt;= 2 |  17.19 15.66 17.95 23.52
## r &lt;= 1 | 147.28 28.71 31.52 37.22
## r = 0  | 296.54 45.23 48.28 55.43
## 
## Eigenvectors, normalised to first column:
## (These are the cointegration relations)
## 
##            y1.l2      y2.l2       y3.l2     y4.l2
## y1.l2  1.0000000  1.0000000  1.00000000  1.000000
## y2.l2 -0.6347789 -0.1341194  0.74761830 24.357249
## y3.l2 -0.5785340  1.4100169 -0.01803175 -6.710469
## y4.l2  0.2788528 -0.6893143 -1.62504044 48.535783
## 
## Weights W:
## (This is the loading matrix)
## 
##            y1.l2        y2.l2       y3.l2         y4.l2
## y1.d -0.51186630 -0.320181456 -0.00621887 -2.424265e-04
## y2.d  0.63903190  0.008777047 -0.01134031 -4.269731e-04
## y3.d  0.44326372 -0.453798733  0.01223929 -9.786591e-05
## y4.d -0.06251362  0.124762555  0.01714466 -5.047995e-04</code></pre>
<ul>
<li><span class="math inline">\(r=0\)</span>棄却. <span class="math inline">\(r \le 1\)</span>棄却, <span class="math inline">\(r \le 2\)</span>棄却されず.
<ul>
<li>→ 共和分ベクトルの個数<span class="math inline">\(=2\)</span></li>
</ul></li>
<li>共和分ベクトルをウェイトとする<span class="math inline">\(Yt\)</span>の各成分の線形和計算
<ul>
<li>→ 定常性の確認</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb858"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb858-1"><a href="共和分分析.html#cb858-1" tabindex="-1"></a>coint_resid <span class="ot">&lt;-</span> ymat <span class="sc">%*%</span> <span class="fu">summary</span>(result_t1)<span class="sc">@</span>V</span>
<span id="cb858-2"><a href="共和分分析.html#cb858-2" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(coint_resid[, <span class="dv">1</span>])</span></code></pre></div>
<pre><code>## Warning in fUnitRoots::adfTest(coint_resid[, 1]): p-value smaller than printed
## p-value</code></pre>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -10.3616
##   P VALUE:
##     0.01 
## 
## Description:
##  Sun Feb  2 15:37:17 2025 by user:</code></pre>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb861-1"><a href="共和分分析.html#cb861-1" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(coint_resid[, <span class="dv">2</span>])</span></code></pre></div>
<pre><code>## Warning in fUnitRoots::adfTest(coint_resid[, 2]): p-value smaller than printed
## p-value</code></pre>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -12.4858
##   P VALUE:
##     0.01 
## 
## Description:
##  Sun Feb  2 15:37:17 2025 by user:</code></pre>
<div class="sourceCode" id="cb864"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb864-1"><a href="共和分分析.html#cb864-1" tabindex="-1"></a><span class="do">##fUnitRoots::adfTest(coint_resid[, 3])</span></span>
<span id="cb864-2"><a href="共和分分析.html#cb864-2" tabindex="-1"></a><span class="do">##fUnitRoots::adfTest(coint_resid[, 4])</span></span></code></pre></div>
<ul>
<li>共和分行列 (共和分ベクトル) の最尤推定値</li>
</ul>
<div class="sourceCode" id="cb865"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb865-1"><a href="共和分分析.html#cb865-1" tabindex="-1"></a>beta_mat <span class="ot">&lt;-</span> <span class="fu">summary</span>(result_t1)<span class="sc">@</span>V</span></code></pre></div>
<p>真のモデルより, 共和分ランク (共和分ベクトルの数) <span class="math inline">\(r=2\)</span>,
共和分ベクトルは, <span class="math inline">\(\beta_1 = (1, -0.5, 0, 0)&#39;\)</span>,
<span class="math inline">\(\beta_2 = (1, 0, 2, -1)\)</span>である.
さらにこれらの任意の線形結合で
作られるベクトルも共和分ベクトルとなる.
上で得られた<code>beta_mat</code>は <span class="math inline">\(\beta_1,\beta_2\)</span>の推定値の線形結合に
なっている.</p>
<!--
THメモ122624: 理論的に固有ベクトル (beta_mat) を計算できれば,
理論的な線形結合の重みも計算できるはず

summary(result_t1)@Vは直行行列になっていない!!
-->
<p>Johansen検定は, モデル特定 (ラグ長, 定数項やトレンド項の扱い) に敏感
であることから, <code>ca.jo</code>のパラメータには, 本来木目の細かい指定が求められる.
注) 残念ながら, <strong>ucra</strong>マニュアルはそれほど親切とは言えない.</p>
</div>
</div>
<div id="補足-vecmにおける確定項の入り方について" class="section level4 unnumbered hasAnchor">
<h4>補足: VECMにおける確定項の入り方について<span class="math inline">\(^{*}\)</span><a href="共和分分析.html#補足-vecmにおける確定項の入り方について" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>レベル変数に対するVAR(<span class="math inline">\(p\)</span>)モデルは, 定数項 (切片項) や線形トレンド,
季節性ダミー変数などを含んだモデルなどに対する共和分分析/ECMの方法が
研究されている.</p>
<p>VAR/ECMにおける定数項と線形トレンドの扱いは, Johansen (1991)
によって整理されている.
(福地・伊藤本の10.7.3の説明も参照のこと)</p>
<p>定数や線形トレンドの, 長期的共和分関係 (<span class="math inline">\(\beta\)</span>に関する式),
および短期的VAR方程式 (差分系列に対するECM) への入り方で,
5つに分類される.</p>
<!--
以下は, 定数 (切片項) と線形トレンドがVAR/ECMにどのように入るかについて整理した, Johansen (1988, 1995) の共和分フレームワークにおける5つのケースの概要である. 

それぞれのケース は、定数やトレンドがVAR (レベル変数について) /ECM (差分変数について) に含まれるかどうか（そしてどのように含まれるか）で分けられる.
- 長期的共和分関係（$\beta$の張る空間）
- 短期的VAR方程式（差分系列に対するECM）

"制約付き" とは項が共和分関係にのみ現れること,
"制約なし" とは項が (差分系列に対する) 短期的な方程式に自由に現れることを指す
-->
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th><strong>ケース</strong></th>
<th><strong>ECM 表現</strong></th>
<th><strong>説明</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1: 確定項一切なし</td>
<td><span class="math inline">\(\Delta \mathbf{Y}_t = \alpha\,\beta^\top \mathbf{Y}_{t-1} + \sum_{i=1}^{p-1} \Gamma_i \Delta \mathbf{Y}_{t-i} + \varepsilon_t\)</span></td>
<td>共和分関係は定数項なし (ゼロの回りで均衡) </br> レベル変数に線形トレンドなし</td>
</tr>
<tr class="even">
<td>2: 制約付き定数項</td>
<td><span class="math inline">\(\Delta \mathbf{Y}_t = \alpha(\beta^\top \mathbf{Y}_{t-1} + \beta_0) + \sum_{i=1}^{p-1} \Gamma_i \Delta \mathbf{Y}_{t-i}+ \varepsilon_t\)</span></td>
<td>定数項は共和分関係に制限 </br> 短期方程式に定数項なし (レベル変数に線形トレンドなし)</td>
</tr>
<tr class="odd">
<td>3: 制約なし定数項</td>
<td><span class="math inline">\(\Delta \mathbf{Y}_t = c + \alpha(\beta^\top \mathbf{Y}_{t-1} + \beta_0) + \Gamma \Delta \mathbf{Y}_{t-1} + \cdots + \varepsilon_t\)</span></td>
<td>レベル変数に線形トレンド </br> 共和分関係に定数項 </br> 多くの経済・金融時系列におけるアプローチ</td>
</tr>
<tr class="even">
<td>4: 制約付き線形トレンド</td>
<td><span class="math inline">\(\Delta \mathbf{Y}_t = c + \alpha(\beta^\top \mathbf{Y}_{t-1} + \beta_0 + \beta_1\,t) + \sum_{i=1}^{p-1} \Gamma_i \Delta \mathbf{Y}_{t-i} + \varepsilon_t\)</span></td>
<td>線形トレンドは共和分関係に制限 (長期的均衡関係に定数項と線形トレンド) </br> レベル変数に線形トレンド</td>
</tr>
<tr class="odd">
<td>5: 短期方程式に線形トレンドあり</td>
<td><span class="math inline">\(\Delta \mathbf{Y}_t = c + \Phi\,t + \alpha(\beta^\top \mathbf{Y}_{t-1} + \beta_0 + \beta_1\,t) + \sum_{i=1}^{p-1} \Gamma_i \Delta \mathbf{Y}_{t-i} + \varepsilon_t\)</span></td>
<td>レベル変数に2次トレンド (強いトレンドの可能性)</td>
</tr>
</tbody>
</table>
</div>
<div id="補足-関数ca.joの使い方について" class="section level4 unnumbered hasAnchor">
<h4>補足: 関数<code>ca.jo()</code>の使い方について<a href="共和分分析.html#補足-関数ca.joの使い方について" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>出所: <strong>urca</strong>マニュアル</p>
<div id="引数specの選択" class="section level5 unnumbered hasAnchor">
<h5><strong>引数<code>spec</code></strong>の選択<a href="共和分分析.html#引数specの選択" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p><code>spec</code>はVECMモデルの形状を特定する引数である</p>
<ul>
<li>選択肢: “longrun”, “transitory”</li>
</ul>
<p>以下のような一般的なVARモデル
<span class="math display">\[
\mathbf{Y}_t = \boldsymbol{\Pi}_1 \mathbf{Y}_{t-1} + \cdots + \boldsymbol{\Pi}_p \mathbf{Y}_{t-p} + \boldsymbol{\mu} + \boldsymbol{\Phi} \boldsymbol{D}_t + \mathbf{\varepsilon}_t
\]</span>
を考える.</p>
<ul>
<li><p><code>spec = "longrun"</code> (デフォルト) の場合
次の形式のVECM仕様に対する推論を行う.
<span class="math display">\[
\Delta \mathbf{Y}_t = \boldsymbol{\Gamma}_1 \Delta \mathbf{Y}_{t-1} + \cdots + \boldsymbol{\Gamma}_{p-1} \Delta \mathbf{Y}_{t-p+1} + \boldsymbol{\Pi} \mathbf{Y}_{t-p} + \boldsymbol{\mu} + \boldsymbol{\Phi} \boldsymbol{D}_t + \mathbf{\varepsilon}_t,
\]</span>
ここで,
<span class="math display">\[
\boldsymbol{\Gamma}_i = - (\boldsymbol{I} - \boldsymbol{\Pi}_1 - \cdots - \boldsymbol{\Gamma}_i) \, (i=1,...,p-1), \quad
\boldsymbol{\Pi} = - (\boldsymbol{I} - \boldsymbol{\Pi}_1 - \cdots - \boldsymbol{\Gamma}_p).
\]</span>
<span class="math inline">\(\boldsymbol{\Gamma}_i\)</span>は累積の長期的インパクトを含む係数である.</p></li>
<li><p><code>spec = "transitory"</code>の場合
次の形式のVECM仕様に対する推論を行う.
<span class="math display">\[
\Delta \mathbf{Y}_t = \boldsymbol{\Gamma}_1 \Delta \mathbf{Y}_{t-1} + \cdots + \boldsymbol{\Gamma}_{p-1} \Delta \mathbf{Y}_{t-p+1} + \boldsymbol{\Pi} \mathbf{Y}_{t-1} + \boldsymbol{\mu} + \boldsymbol{\Phi} \boldsymbol{D}_t + \mathbf{\varepsilon}_t,
\]</span>
ここで,
<span class="math display">\[
\boldsymbol{\Gamma}_i = - (\boldsymbol{\Pi}_{i+1} + \cdots + \boldsymbol{\Gamma}_i) \, (i=1,...,p-1), \quad
\boldsymbol{\Pi} = - (\boldsymbol{I} - \boldsymbol{\Pi}_1 - \cdots - \boldsymbol{\Gamma}_p).
\]</span>
<span class="math inline">\(\boldsymbol{\Gamma}_i\)</span>は一時的なインパクトを測る係数である.</p></li>
</ul>
<p>なお, <span class="math inline">\(\boldsymbol{\mu}\)</span> は確定項を, <span class="math inline">\(\boldsymbol{D}_t\)</span>はダミー変数項を表す.
どちらの仕様においても, <span class="math inline">\(\boldsymbol{\Pi}\)</span> に対する推論 (解釈も) 同じである.</p>
<!--
##### **引数`ecdet`**: "none", "const", "trend"の選択

共和分関係に含まれる確定的トレンド項の種類を指定する. 項なし ("none"), 定数のみ ("const"), または, 定数+線形トレンド ("trend")


引数`season`は, 季節ダミー変数を与える際に, 季節性の頻度 (frequency) を指定する. 一方, `dumvar`はダミー変数がある場合に, データ行列 (行の大きさ$=$標本サイズ$n$) で与える.

-->

</div>
</div>
</div>
</div>
<div id="誤差修正モデル-データ分析例-tsay-mts-ch5" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> 誤差修正モデル: データ分析例 (Tsay, MTS, Ch5)<a href="共和分分析.html#誤差修正モデル-データ分析例-tsay-mts-ch5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>共和分 (cointegration)は非定常系列同士が長期的な均衡関係を有することを捉える概念であるが,
誤差修正モデルは, その共和分関係があるもとで, 変数間の長期的均衡からの乖離を考慮
し, 短期の動的な修正のプロセスを記述するモデルである.
誤差修正モデルによって, 一つのモデルの中で長期的均衡関係と短期的な動学的修正を統合的に記述することができる.</p>
<p>理論上は, 「Grangerの表現定理」によれば,
多変量時系列<span class="math inline">\(\mathbf{y}_t ∼ I(1)\)</span> の成分間に共和分関係があることと,
<span class="math inline">\(\mathbf{y}_t\)</span> に対し (Π のランクを持つ) VECM (ベクトル誤差修正モデル) 表現が存在する
ことは同値である.</p>
<p>したがって, データ分析の手順としては, 前節で述べたように
多変量時系列の間に共和分関係の存在を確かめた上で,
誤差修正モデルを推定すれば良いことが分かる.</p>
<p>ここでは, 誤差修正モデルの推定について, 教科書MTSに沿って
Rコードと実行結果の要点を記載する.</p>
<p>パッケージは, 上で使用した<strong>urca</strong>と合わせて, Tsayが作成した<strong>MTS</strong>も使用する.
具体的には, <strong>urca</strong>の関数<code>ca.jo()</code>によってJohansenの共和分検定を行った後に,
<strong>MTS</strong>の関数<code>ECMvar1()</code>, <code>ECMrefvar1()</code>, <code>ECMvar()</code>を使ってECMを推定する.</p>
<p>教科書では, 単位根検定からECM推定までの作業フローが解説されている. 次数<span class="math inline">\(p\)</span>の選択 や確定項の有無に関する判断 (どのタイミングでどのような理由によって) についても言及しているので参考にすると良い.</p>
<p>以下, Rコードや出力結果に関する解説は省略する. 必要に応じて教科書の当該箇所を参照のこと.</p>
<ul>
<li>出所: Tsay, MTS, Ch5より抜粋（適宜, 補足説明挿入, または修正)
<ul>
<li><a href="https://faculty.chicagobooth.edu/ruey-s-tsay/research/multivariate-time-series-analysis-with-r-and-financial-applications" class="uri">https://faculty.chicagobooth.edu/ruey-s-tsay/research/multivariate-time-series-analysis-with-r-and-financial-applications</a></li>
</ul></li>
</ul>
<div id="共和分検定" class="section level3 unnumbered hasAnchor">
<h3>共和分検定<a href="共和分分析.html#共和分検定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Tsay, 5.9, pp.310–</li>
</ul>
<div class="sourceCode" id="cb866"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb866-1"><a href="共和分分析.html#cb866-1" tabindex="-1"></a><span class="fu">require</span>(fUnitRoots) <span class="co"># adfTest</span></span></code></pre></div>
<pre><code>## Loading required package: fUnitRoots</code></pre>
<div class="sourceCode" id="cb868"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb868-1"><a href="共和分分析.html#cb868-1" tabindex="-1"></a><span class="fu">require</span>(urca)       <span class="co"># ca.jo</span></span></code></pre></div>
<pre><code>## Loading required package: urca</code></pre>
<pre><code>## 
## Attaching package: &#39;urca&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:fUnitRoots&#39;:
## 
##     punitroot, qunitroot, unitrootTable</code></pre>
<div class="sourceCode" id="cb872"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb872-1"><a href="共和分分析.html#cb872-1" tabindex="-1"></a><span class="fu">require</span>(MTS)        <span class="co"># VARorder()</span></span></code></pre></div>
<pre><code>## Loading required package: MTS</code></pre>
<div id="分析に使用するデータ" class="section level4 unnumbered hasAnchor">
<h4>分析に使用するデータ<a href="共和分分析.html#分析に使用するデータ" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>月次社債イールド, 1954.7–2005.3</li>
<li>FRB St. Louisのデータ</li>
<li>系列(Aaa, Baa)が2変量VAR(<span class="math inline">\(p\)</span>)モデルに従うと仮定し. 次数<span class="math inline">\(p\)</span>を決定:</li>
</ul>
<div class="sourceCode" id="cb874"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb874-1"><a href="共和分分析.html#cb874-1" tabindex="-1"></a>ifl <span class="ot">&lt;-</span> <span class="fu">file.path</span>(dir_MTS, <span class="st">&quot;m-bnd.txt&quot;</span>)  <span class="co"># dir_MTS: m-bnd.txtを格納しているディレクトリ</span></span>
<span id="cb874-2"><a href="共和分分析.html#cb874-2" tabindex="-1"></a>da <span class="ot">&lt;-</span> <span class="fu">read.table</span>(ifl)</span>
<span id="cb874-3"><a href="共和分分析.html#cb874-3" tabindex="-1"></a><span class="fu">head</span>(da)</span></code></pre></div>
<pre><code>##     V1 V2 V3   V4   V5
## 1 1954  7  1 2.89 3.50
## 2 1954  8  1 2.87 3.49
## 3 1954  9  1 2.89 3.47
## 4 1954 10  1 2.87 3.46
## 5 1954 11  1 2.89 3.45
## 6 1954 12  1 2.90 3.45</code></pre>
<div class="sourceCode" id="cb876"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb876-1"><a href="共和分分析.html#cb876-1" tabindex="-1"></a>bnd <span class="ot">&lt;-</span> da[, <span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb876-2"><a href="共和分分析.html#cb876-2" tabindex="-1"></a><span class="fu">colnames</span>(bnd) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Aaa&quot;</span>, <span class="st">&quot;Baa&quot;</span>)</span>
<span id="cb876-3"><a href="共和分分析.html#cb876-3" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> MTS<span class="sc">::</span><span class="fu">VARorder</span>(bnd)        <span class="co"># original function, now in &#39;MTS&#39;</span></span></code></pre></div>
<pre><code>## selected order: aic =  11 
## selected order: bic =  3 
## selected order: hq =  3 
## Summary table:  
##        p     AIC     BIC      HQ      M(p) p-value
##  [1,]  0 -0.5697 -0.5697 -0.5697    0.0000  0.0000
##  [2,]  1 -7.8664 -7.8374 -7.8551 4331.0806  0.0000
##  [3,]  2 -8.1844 -8.1264 -8.1618  195.5266  0.0000
##  [4,]  3 -8.2589 -8.1720 -8.2251   51.6109  0.0000
##  [5,]  4 -8.2552 -8.1393 -8.2101    5.5112  0.2387
##  [6,]  5 -8.2481 -8.1032 -8.1917    3.5073  0.4768
##  [7,]  6 -8.2751 -8.1013 -8.2075   23.4161  0.0001
##  [8,]  7 -8.2803 -8.0775 -8.2014   10.6262  0.0311
##  [9,]  8 -8.2826 -8.0507 -8.1924    8.9080  0.0634
## [10,]  9 -8.2784 -8.0176 -8.1769    5.1613  0.2711
## [11,] 10 -8.2775 -7.9877 -8.1648    7.0457  0.1335
## [12,] 11 -8.2840 -7.9652 -8.1600   11.2224  0.0242
## [13,] 12 -8.2812 -7.9334 -8.1459    5.8956  0.2071
## [14,] 13 -8.2716 -7.8949 -8.1251    2.0355  0.7292</code></pre>
<ul>
<li>→ BIC, HQ(Nannan-Quinn情報量規準), <span class="math inline">\(p=3\)</span>を選択</li>
</ul>
<p>次に,</p>
<ul>
<li>各系列の単位根検定 (ADF検定)
<ul>
<li><span class="math inline">\(H_0\)</span>: 単位根有り</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb878"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb878-1"><a href="共和分分析.html#cb878-1" tabindex="-1"></a><span class="fu">pacf</span>(bnd[, <span class="dv">1</span>])</span></code></pre></div>
<p><img src="097-cointECM_files/figure-html/adf-1.png" width="672" /></p>
<div class="sourceCode" id="cb879"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb879-1"><a href="共和分分析.html#cb879-1" tabindex="-1"></a><span class="fu">pacf</span>(bnd[, <span class="dv">2</span>])</span></code></pre></div>
<p><img src="097-cointECM_files/figure-html/adf-2.png" width="672" /></p>
<div class="sourceCode" id="cb880"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb880-1"><a href="共和分分析.html#cb880-1" tabindex="-1"></a><span class="co"># または,</span></span>
<span id="cb880-2"><a href="共和分分析.html#cb880-2" tabindex="-1"></a><span class="co"># ar(bnd[, 1])      # --&gt; AIC, p = 3</span></span>
<span id="cb880-3"><a href="共和分分析.html#cb880-3" tabindex="-1"></a><span class="co"># ar(bnd[, 2])      # --&gt; AIC, p = 2</span></span>
<span id="cb880-4"><a href="共和分分析.html#cb880-4" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb880-5"><a href="共和分分析.html#cb880-5" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(bnd[, <span class="dv">1</span>], <span class="at">lags =</span> <span class="dv">3</span>, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 3
##   STATISTIC:
##     Dickey-Fuller: -1.7007
##   P VALUE:
##     0.425 
## 
## Description:
##  Sun Feb  2 15:37:19 2025 by user:</code></pre>
<div class="sourceCode" id="cb882"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb882-1"><a href="共和分分析.html#cb882-1" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(bnd[, <span class="dv">2</span>], <span class="at">lags =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 2
##   STATISTIC:
##     Dickey-Fuller: -1.6221
##   P VALUE:
##     0.4544 
## 
## Description:
##  Sun Feb  2 15:37:19 2025 by user:</code></pre>
<ul>
<li>–&gt; Aaa, Baa系列のADF検定、棄却されない (H0: 単位根非定常)</li>
</ul>
<div class="sourceCode" id="cb884"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb884-1"><a href="共和分分析.html#cb884-1" tabindex="-1"></a><span class="fu">matplot</span>(bnd, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="097-cointECM_files/figure-html/adf2-1.png" width="672" /></p>
<div class="sourceCode" id="cb885"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb885-1"><a href="共和分分析.html#cb885-1" tabindex="-1"></a><span class="co"># Tsay本の内容に沿って, 以下を挿入</span></span>
<span id="cb885-2"><a href="共和分分析.html#cb885-2" tabindex="-1"></a><span class="fu">apply</span>(<span class="fu">apply</span>(bnd, <span class="dv">2</span>, diff), <span class="dv">2</span>, mean)<span class="sc">/</span></span>
<span id="cb885-3"><a href="共和分分析.html#cb885-3" tabindex="-1"></a>  <span class="fu">apply</span>(<span class="fu">apply</span>(bnd, <span class="dv">2</span>, diff), <span class="dv">2</span>, sd)</span></code></pre></div>
<pre><code>##        Aaa        Baa 
## 0.01862195 0.02077461</code></pre>
<div class="sourceCode" id="cb887"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb887-1"><a href="共和分分析.html#cb887-1" tabindex="-1"></a><span class="co">#apply(apply(bnd, 2, diff), 2, fBasics::stdev)</span></span></code></pre></div>
<ul>
<li>階階差列の平均値ベクトルは, ゼロから有意に離れていない → 共和分検定に, 定数項入れない (Tsay, p.310)</li>
<li>共和分検定におけるトレンドの指定. Tsay, p.304を参照</li>
</ul>
</div>
</div>
<div id="johansenの方法-1" class="section level3 unnumbered hasAnchor">
<h3>Johansenの方法<a href="共和分分析.html#johansenの方法-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Johansenの方法 → 共和分関係の検定, 共和分ベクトルや共和分ランク(個数)の推定</li>
</ul>
<div id="最大固有値法" class="section level4 unnumbered hasAnchor">
<h4>最大固有値法<a href="共和分分析.html#最大固有値法" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><span class="math inline">\(H_0\)</span>: 多くても<span class="math inline">\(r\)</span>個の共和分関係しか存在しない vs <span class="math inline">\(H_1\)</span>: <span class="math inline">\((r+1)\)</span>個の共和分関係が存在する</li>
<li>(<span class="math inline">\(H_0\)</span>: 共和分ランク<span class="math inline">\(=r\)</span> vs <span class="math inline">\(H_1\)</span>: 共和分ランク<span class="math inline">\(=r+1\)</span>)</li>
</ul>
<pre><code>- urca::ca.jp関数
  - x: 共和分を調べたいデータ行列 (原系列)
  - type: 検定方法の種類. &#39;eigen&#39;(最大固有値法), &#39;trace&#39; (トレース法)
  - ecdet: トレンド指定. &#39;none&#39; (なし), &#39;const&#39; (定数項有), &#39;trend&#39; (線形トレンド有)
    - $\Delta {\bf y}_t = {\bf \mu}_0 + {\bf \mu}_1 t+\cdots$
    - (→ 共和分関係にも定数項や線形トレンドが含まれる)
  - K: 系列(水準)のVARラグ次数
  - spec: VECMの特定化. &quot;longrun&quot; ($ {\bf Γ}_i , 長期的(累積)インパクト), &quot;transitory&quot; ((${\bf Γ}_i$,  一時的インパクト)
)</code></pre>
<div class="sourceCode" id="cb889"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb889-1"><a href="共和分分析.html#cb889-1" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> urca<span class="sc">::</span><span class="fu">ca.jo</span>(bnd, <span class="at">K =</span> <span class="dv">2</span>, <span class="at">ecdet =</span> <span class="fu">c</span>(<span class="st">&quot;none&quot;</span>))        <span class="co"># spec = &quot;longrun&quot; (デフォルト)</span></span>
<span id="cb889-2"><a href="共和分分析.html#cb889-2" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<pre><code>## 
## ###################### 
## # Johansen-Procedure # 
## ###################### 
## 
## Test type: maximal eigenvalue statistic (lambda max) , with linear trend 
## 
## Eigenvalues (lambda):
## [1] 0.054773196 0.004665298
## 
## Values of teststatistic and critical values of test:
## 
##           test 10pct  5pct  1pct
## r &lt;= 1 |  2.84  6.50  8.18 11.65
## r = 0  | 34.19 12.91 14.90 19.19
## 
## Eigenvectors, normalised to first column:
## (These are the cointegration relations)
## 
##            Aaa.l2    Baa.l2
## Aaa.l2  1.0000000  1.000000
## Baa.l2 -0.8856789 -2.723912
## 
## Weights W:
## (This is the loading matrix)
## 
##            Aaa.l2      Baa.l2
## Aaa.d -0.04696894 0.002477064
## Baa.d  0.04046524 0.002139536</code></pre>
<ul>
<li>→ <span class="math inline">\(r=0\)</span>は棄却. <span class="math inline">\(r=1\)</span>は棄却されず</li>
<li>→ <span class="math inline">\(r=1\)</span> (共和分有. 共和分ベクトルの個数 (<span class="math inline">\(\Pi\)</span> 行列のランク))</li>
</ul>
<div class="sourceCode" id="cb891"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb891-1"><a href="共和分分析.html#cb891-1" tabindex="-1"></a><span class="co">#m3 &lt;- urca::ca.jo(bnd, K = 2, ecdet = c(&quot;none&quot;), spec = c(&quot;transitory&quot;))</span></span>
<span id="cb891-2"><a href="共和分分析.html#cb891-2" tabindex="-1"></a><span class="co">#summary(m3)</span></span>
<span id="cb891-3"><a href="共和分分析.html#cb891-3" tabindex="-1"></a><span class="co"># 定数項有のケース</span></span>
<span id="cb891-4"><a href="共和分分析.html#cb891-4" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> urca<span class="sc">::</span><span class="fu">ca.jo</span>(bnd, <span class="at">K =</span> <span class="dv">2</span>, <span class="at">ecdet =</span> <span class="fu">c</span>(<span class="st">&quot;const&quot;</span>), <span class="at">spec =</span> <span class="fu">c</span>(<span class="st">&quot;longrun&quot;</span>))</span>
<span id="cb891-5"><a href="共和分分析.html#cb891-5" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
<pre><code>## 
## ###################### 
## # Johansen-Procedure # 
## ###################### 
## 
## Test type: maximal eigenvalue statistic (lambda max) , without linear trend and constant in cointegration 
## 
## Eigenvalues (lambda):
## [1] 5.477346e-02 4.878009e-03 6.935308e-21
## 
## Values of teststatistic and critical values of test:
## 
##           test 10pct  5pct  1pct
## r &lt;= 1 |  2.97  7.52  9.24 12.97
## r = 0  | 34.19 13.75 15.67 20.20
## 
## Eigenvectors, normalised to first column:
## (These are the cointegration relations)
## 
##                Aaa.l2    Baa.l2   constant
## Aaa.l2    1.000000000  1.000000   1.000000
## Baa.l2   -0.885675435 -2.701784  -3.315369
## constant -0.003491742 16.399576 -13.776952
## 
## Weights W:
## (This is the loading matrix)
## 
##            Aaa.l2      Baa.l2      constant
## Aaa.d -0.04699903 0.002507156  2.325397e-18
## Baa.d  0.04043910 0.002165681 -1.589823e-18</code></pre>
</div>
<div id="トレース法" class="section level4 unnumbered hasAnchor">
<h4>トレース法<a href="共和分分析.html#トレース法" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><span class="math inline">\(H_0\)</span>: 多くても<span class="math inline">\(r\)</span>個の共和分関係しか存在しない vs <span class="math inline">\(H_1\)</span>: 全ての変数が定常</li>
<li>(<span class="math inline">\(H_0\)</span>: 共和分ランク<span class="math inline">\(=r\)</span> vs <span class="math inline">\(H_1\)</span>: 共和分ランク<span class="math inline">\(=m\)</span> (原系列は定常))</li>
</ul>
<div class="sourceCode" id="cb893"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb893-1"><a href="共和分分析.html#cb893-1" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> urca<span class="sc">::</span><span class="fu">ca.jo</span>(bnd, <span class="at">K =</span> <span class="dv">2</span>, <span class="at">ecdet =</span> <span class="fu">c</span>(<span class="st">&quot;none&quot;</span>), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;trace&quot;</span>), <span class="at">spec =</span> <span class="fu">c</span>(<span class="st">&quot;transitory&quot;</span>))</span>
<span id="cb893-2"><a href="共和分分析.html#cb893-2" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code></pre></div>
<pre><code>## 
## ###################### 
## # Johansen-Procedure # 
## ###################### 
## 
## Test type: trace statistic , with linear trend 
## 
## Eigenvalues (lambda):
## [1] 0.054773196 0.004665298
## 
## Values of teststatistic and critical values of test:
## 
##           test 10pct  5pct  1pct
## r &lt;= 1 |  2.84  6.50  8.18 11.65
## r = 0  | 37.03 15.66 17.95 23.52
## 
## Eigenvectors, normalised to first column:
## (These are the cointegration relations)
## 
##            Aaa.l1    Baa.l1
## Aaa.l1  1.0000000  1.000000
## Baa.l1 -0.8856789 -2.723912
## 
## Weights W:
## (This is the loading matrix)
## 
##            Aaa.l1      Baa.l1
## Aaa.d -0.04696894 0.002477064
## Baa.d  0.04046524 0.002139536</code></pre>
<ul>
<li>→ <span class="math inline">\(r=0\)</span>は棄却. <span class="math inline">\(r=1\)</span>は棄却されず</li>
<li>→ <span class="math inline">\(r=1\)</span> (同)</li>
</ul>
<div class="sourceCode" id="cb895"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb895-1"><a href="共和分分析.html#cb895-1" tabindex="-1"></a>(coint_vec <span class="ot">&lt;-</span> <span class="fu">summary</span>(m4)<span class="sc">@</span>V)</span></code></pre></div>
<pre><code>##            Aaa.l1    Baa.l1
## Aaa.l1  1.0000000  1.000000
## Baa.l1 -0.8856789 -2.723912</code></pre>
<ul>
<li><p>→ 共和分ベクトル: <span class="math inline">\((1, -0.886)\)</span></p></li>
<li><p>得られた``cointegration’’系列 <span class="math inline">\(w_t=1 \cdot Aaa_t - 0.886 \cdot Baa_t\)</span>に対して単位根検定</p></li>
</ul>
<div class="sourceCode" id="cb897"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb897-1"><a href="共和分分析.html#cb897-1" tabindex="-1"></a><span class="co"># wt &lt;- bnd[, 1] - 0.886 * bnd[, 2]</span></span>
<span id="cb897-2"><a href="共和分分析.html#cb897-2" tabindex="-1"></a>wt <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(bnd) <span class="sc">%*%</span> coint_vec[, <span class="dv">1</span>]</span>
<span id="cb897-3"><a href="共和分分析.html#cb897-3" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb897-4"><a href="共和分分析.html#cb897-4" tabindex="-1"></a>fUnitRoots<span class="sc">::</span><span class="fu">adfTest</span>(wt, <span class="at">lags =</span> <span class="dv">3</span>, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in fUnitRoots::adfTest(wt, lags = 3, type = &quot;c&quot;): p-value smaller than
## printed p-value</code></pre>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 3
##   STATISTIC:
##     Dickey-Fuller: -4.6052
##   P VALUE:
##     0.01 
## 
## Description:
##  Sun Feb  2 15:37:19 2025 by user:</code></pre>
<ul>
<li>→ <span class="math inline">\(p\)</span>値<span class="math inline">\(=0.01\)</span> (単位根無)</li>
</ul>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="共和分分析.html#cb900-1" tabindex="-1"></a><span class="fu">plot</span>(wt, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="097-cointECM_files/figure-html/cointvec3-1.png" width="672" /></p>
<ul>
<li>→ “定常時系列の特徴を示す”</li>
</ul>
</div>
</div>
<div id="誤差修正モデル-ecm-の推定" class="section level3 unnumbered hasAnchor">
<h3>誤差修正モデル (ECM) の推定<a href="共和分分析.html#誤差修正モデル-ecm-の推定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>前提: VARモデルの次数<span class="math inline">\(p\)</span>,共和分ベクトルの数は既知 (上で得られた)</li>
</ul>
<div id="ecmのols推定" class="section level4 unnumbered hasAnchor">
<h4>ECMのOLS推定<a href="共和分分析.html#ecmのols推定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>共和分ベクトル<span class="math inline">\(\beta_t\)</span>が既知の場合:</li>
<li>上で得られた ``cointegrating系列’’wt=bnd[,1]-0.886*bnd[,2]
を所与として <span class="math inline">\((p=3, r=1)\)</span>, ECMをOLS推定</li>
</ul>
<pre><code>- MTS::ECMvar1(x, p, wt=wt, include.const = FALSE, fixed = NULL, output = TRUE)
  - ECM VAR(p)モデルのOLS推定 (wtが既知の場合)
  - x: (Txk), k次元共和分VAR過程
  - wt: (Txm), m次元共和分過程
  - include.const: 定数項の有無 (デフォルト=F)</code></pre>
<div class="sourceCode" id="cb902"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb902-1"><a href="共和分分析.html#cb902-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> MTS<span class="sc">::</span><span class="fu">ECMvar1</span>(bnd, <span class="dv">3</span>, wt) <span class="do">## Given the co-integrated vector</span></span></code></pre></div>
<pre><code>## alpha:  
##           Aaa    Baa
## [1,] -0.00122 0.0634
## standard error 
##        [,1]   [,2]
## [1,] 0.0347 0.0306
## AR coefficient matrix 
## AR( 1 )-matrix 
##       Aaa      Baa
## Aaa 0.452 -0.00149
## Baa 0.293  0.20380
## standard error 
##        [,1]   [,2]
## [1,] 0.0879 0.1008
## [2,] 0.0774 0.0887
## AR( 2 )-matrix 
##        Aaa    Baa
## Aaa -0.300 0.0535
## Baa -0.151 0.0274
## standard error 
##        [,1]   [,2]
## [1,] 0.0860 0.0940
## [2,] 0.0757 0.0827
## ----- 
## Residuals cov-mtx: 
##           Aaa        Baa
## Aaa 0.0400851 0.03167180
## Baa 0.0316718 0.03105888
##        
## det(sse) =  0.0002418953 
## AIC =  -8.294165 
## BIC =  -8.221721</code></pre>
<div class="sourceCode" id="cb904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb904-1"><a href="共和分分析.html#cb904-1" tabindex="-1"></a>m1<span class="sc">$</span>coef <span class="co"># 表示の向きに注意 (xmtx調整行列, 左辺の各成分が列方向に, 右辺のARラグ項が行方向に)</span></span></code></pre></div>
<pre><code>##               Aaa         Baa
## xmtx -0.001217005  0.06339082
## Aaa   0.451993390  0.29303941
## Baa  -0.001491101  0.20379673
## Aaa  -0.299907502 -0.15075817
## Baa   0.053499341  0.02742606</code></pre>
<div class="sourceCode" id="cb906"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb906-1"><a href="共和分分析.html#cb906-1" tabindex="-1"></a>m1<span class="sc">$</span>secoef   <span class="co"># 同</span></span></code></pre></div>
<pre><code>##            [,1]       [,2]
## [1,] 0.03471368 0.03055639
## [2,] 0.08790257 0.07737541
## [3,] 0.10080919 0.08873634
## [4,] 0.08600254 0.07570293
## [5,] 0.09396739 0.08271391</code></pre>
<div class="sourceCode" id="cb908"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb908-1"><a href="共和分分析.html#cb908-1" tabindex="-1"></a>m1<span class="sc">$</span>coef <span class="sc">/</span> m1<span class="sc">$</span>secoef <span class="co"># 同</span></span></code></pre></div>
<pre><code>##              Aaa        Baa
## xmtx -0.03505836  2.0745518
## Aaa   5.14198170  3.7872419
## Baa  -0.01479132  2.2966546
## Aaa  -3.48719367 -1.9914443
## Baa   0.56933946  0.3315773</code></pre>
<ul>
<li>推定されたECM (<span class="math inline">\(w_t=\beta&#39;{\bf y}_t=(1,- 0.886){\bf y}_t\)</span>)
<span class="math display">\[ \Delta {\bf y}_t = \left[\begin{array}{r}
    -0.001 \\ 0.064
  \end{array}\right] w_t  +
  \left[\begin{array}{rr}
    0.452 &amp; -0.001 \\ 0.293 &amp; 0.204
  \end{array} \right] \Delta {\bf y}_{t-1}
  \]</span>
<span class="math display">\[
      +\left[\begin{array}{rr}
    -0.300 &amp; 0.054 \\ -0.151 &amp; 0.028
  \end{array} \right] \Delta {\bf y}_{t-2} + \epsilon_t,\quad
  \hat{\Sigma}= \frac{1}{100} \left[\begin{array}{rr}
    4.01 &amp; 3.17 \\ 3.17 &amp; 3.11
  \end{array} \right]
  \]</span></li>
</ul>
</div>
<div id="ols推定されたecmの修正" class="section level4 unnumbered hasAnchor">
<h4>OLS推定されたECMの修正<a href="共和分分析.html#ols推定されたecmの修正" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>ECMの修正 (パラメータ数削減)
<ul>
<li>有意でない係数を0に置く</li>
</ul></li>
</ul>
<pre><code>- MTS::refECMvar1(m1, thres = 1)
  - ECM VAR(p)モデルの制約付きOLS推定 (wtが既知の場合)
  - thres: t-ratioの閾値(デフォルト=1)
  - |t-ratio| &lt; thres の推定係数を0に置き換える</code></pre>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb911-1"><a href="共和分分析.html#cb911-1" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> MTS<span class="sc">::</span><span class="fu">refECMvar1</span>(m1) <span class="do">####### Refine the model fit</span></span></code></pre></div>
<pre><code>## Equation:  1  npar =  2 
## Equation:  2  npar =  4 
## alpha:  
##      [,1]   [,2]
## [1,]    0 0.0625
## standard error 
##      [,1]   [,2]
## [1,]    1 0.0304
## AR coefficient matrix 
## AR( 1 )-matrix 
##       [,1]  [,2]
## [1,] 0.448 0.000
## [2,] 0.286 0.212
## standard error 
##        [,1]   [,2]
## [1,] 0.0393 1.0000
## [2,] 0.0746 0.0855
## AR( 2 )-matrix 
##        [,1] [,2]
## [1,] -0.256    0
## [2,] -0.129    0
## standard error 
##        [,1] [,2]
## [1,] 0.0393    1
## [2,] 0.0382    1
## ----- 
## Residuals cov-mtx: 
##            [,1]       [,2]
## [1,] 0.04010853 0.03168277
## [2,] 0.03168277 0.03106450
##        
## det(sse) =  0.0002421536 
## AIC =  -8.306234 
## BIC =  -8.262768</code></pre>
<ul>
<li>推定されたECM (修正後)
<span class="math display">\[ \Delta {\bf y}_t = \left[\begin{array}{r}
    0.000 \\ 0.063
  \end{array}\right] w_t  +
  \left[\begin{array}{rr}
    0.448 &amp; 0.000 \\ 0.286 &amp; 0.212
  \end{array} \right] \Delta {\bf y}_{t-1}
  \]</span>
<span class="math display">\[
      +\left[\begin{array}{rr}
    -0.256 &amp; 0.000 \\ -0.129 &amp; 0.000
  \end{array} \right] \Delta {\bf y}_{t-2} + \epsilon_t,\quad
  \hat{\Sigma}= \frac{1}{100} \left[\begin{array}{rr}
    4.01 &amp; 3.17 \\ 3.17 &amp; 3.11
  \end{array} \right]
  \]</span></li>
</ul>
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb913-1"><a href="共和分分析.html#cb913-1" tabindex="-1"></a><span class="co"># pacf(m2$residuals)</span></span>
<span id="cb913-2"><a href="共和分分析.html#cb913-2" tabindex="-1"></a><span class="co"># --&gt; model checking, 若干の系列相関, 相互相関有り(教科書の記述と齟齬?)</span></span>
<span id="cb913-3"><a href="共和分分析.html#cb913-3" tabindex="-1"></a><span class="co"># --&gt; alpha(1,1)=0 &lt;-- Aaa系列の1階階差系列は定常</span></span>
<span id="cb913-4"><a href="共和分分析.html#cb913-4" tabindex="-1"></a>m2<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##            [,1]        [,2]
## [1,]  0.0000000  0.06250339
## [2,]  0.4484522  0.28620026
## [3,]  0.0000000  0.21172072
## [4,] -0.2559947 -0.12908889
## [5,]  0.0000000  0.00000000</code></pre>
<div class="sourceCode" id="cb915"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb915-1"><a href="共和分分析.html#cb915-1" tabindex="-1"></a>m2<span class="sc">$</span>secoef</span></code></pre></div>
<pre><code>##            [,1]       [,2]
## [1,] 1.00000000 0.03044171
## [2,] 0.03929053 0.07458234
## [3,] 1.00000000 0.08546551
## [4,] 0.03930742 0.03821387
## [5,] 1.00000000 1.00000000</code></pre>
<div class="sourceCode" id="cb917"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb917-1"><a href="共和分分析.html#cb917-1" tabindex="-1"></a>m2<span class="sc">$</span>coef <span class="sc">/</span> m1<span class="sc">$</span>secoef</span></code></pre></div>
<pre><code>##           [,1]      [,2]
## [1,]  0.000000  2.045509
## [2,]  5.101696  3.698853
## [3,]  0.000000  2.385953
## [4,] -2.976594 -1.705203
## [5,]  0.000000  0.000000</code></pre>
</div>
<div id="ecmのqml推定" class="section level4 unnumbered hasAnchor">
<h4>ECMのQML推定<a href="共和分分析.html#ecmのqml推定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>共和分ベクトル<span class="math inline">\(\beta_t\)</span>が未知の場合:
<ul>
<li>仮定:イノベーション系列 <span class="math inline">\({\epsilon_t}\)</span> がGaussian</li>
</ul></li>
</ul>
<pre><code>- MTS::ECMvar(x,p,ibeta)
  - ECM VAR(p)モデルのQML推定 (wtが未知の場合)
  - ibeta: co-integrating matrix初期値
  - alpha: alpha行列の初期値 (デフォルト=NULL)</code></pre>
<div class="sourceCode" id="cb920"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb920-1"><a href="共和分分析.html#cb920-1" tabindex="-1"></a><span class="co"># beta &lt;- c(1, -0.886) </span><span class="al">###</span><span class="co"> Initial value of co-integration</span></span>
<span id="cb920-2"><a href="共和分分析.html#cb920-2" tabindex="-1"></a>beta <span class="ot">&lt;-</span> coint_vec[, <span class="dv">1</span>]</span>
<span id="cb920-3"><a href="共和分分析.html#cb920-3" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> MTS<span class="sc">::</span><span class="fu">ECMvar</span>(bnd, <span class="at">p =</span> <span class="dv">3</span>, <span class="at">ibeta =</span> beta, <span class="at">include.const =</span> F) <span class="do">#### Joint estimation</span></span></code></pre></div>
<pre><code>## Order p:  3  Co-integrating rank:  1 
## Number of parameters:  11 
## initial estimates:  -0.001217005 0.06339082 -0.8856789 0.4519934 -0.001491101 -0.2999075 0.05349934 0.2930394 0.2037967 -0.1507582 0.02742606 
## Par. Lower-bounds:  -0.05328753 0.01755623 -0.9464619 0.3201395 -0.1527049 -0.4289113 -0.08745174 0.1769763 0.07069222 -0.2643126 -0.09664481 
## Par. Upper-bounds:  0.05085352 0.1092254 -0.8248958 0.5838472 0.1497227 -0.1709037 0.1944504 0.4091025 0.3369012 -0.03720378 0.1514969 
## Final   Estimates:  -0.0007839214 0.0637811 -0.8865273 0.4518197 -0.001408246 -0.3000951 0.05359282 0.2928489 0.203917 -0.1509735 0.02759872 
## 
## Coefficient(s):
##          Estimate  Std. Error  t value Pr(&gt;|t|)    
##        -0.0007839   0.0346658   -0.023 0.981958    
##         0.0637811   0.0305205    2.090 0.036638 *  
## Baa.l1 -0.8865273   0.0055000 -161.187  &lt; 2e-16 ***
##         0.4518197   0.0884438    5.109 3.25e-07 ***
##        -0.0014082   0.1013908   -0.014 0.988918    
##        -0.3000951   0.0859973   -3.490 0.000484 ***
##         0.0535928   0.0939314    0.571 0.568303    
##         0.2928489   0.0777471    3.767 0.000165 ***
##         0.2039170   0.0891346    2.288 0.022153 *  
##        -0.1509735   0.0756992   -1.994 0.046110 *  
##         0.0275987   0.0826788    0.334 0.738526    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## alpha:  
##           [,1]
## [1,] -0.000784
## [2,]  0.063781
## standard error 
##        [,1]
## [1,] 0.0347
## [2,] 0.0305
## beta:  
##        [,1]
## [1,]  1.000
## [2,] -0.887
## standard error 
##        [,1]
## [1,] 1.0000
## [2,] 0.0055
## AR coefficient matrix 
## AR( 1 )-matrix 
##       [,1]     [,2]
## [1,] 0.452 -0.00141
## [2,] 0.293  0.20392
## standard error 
##        [,1]   [,2]
## [1,] 0.0884 0.1014
## [2,] 0.0777 0.0891
## AR( 2 )-matrix 
##        [,1]   [,2]
## [1,] -0.300 0.0536
## [2,] -0.151 0.0276
## standard error 
##        [,1]   [,2]
## [1,] 0.0860 0.0939
## [2,] 0.0757 0.0827
## ----- 
## Residuals cov-mtx: 
##           Aaa        Baa
## Aaa 0.0399535 0.03156630
## Baa 0.0315663 0.03095427
##        
## det(sse) =  0.0002403005 
## AIC =  -8.297496 
## BIC =  -8.217807</code></pre>
<div class="sourceCode" id="cb922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb922-1"><a href="共和分分析.html#cb922-1" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb922-2"><a href="共和分分析.html#cb922-2" tabindex="-1"></a>m3<span class="sc">$</span>ncoint       <span class="co"># 共和分ベクトル数</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb924"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb924-1"><a href="共和分分析.html#cb924-1" tabindex="-1"></a>m3<span class="sc">$</span>alpha        <span class="co"># 調整行列</span></span></code></pre></div>
<pre><code>##               [,1]
## [1,] -0.0007839214
## [2,]  0.0637811002</code></pre>
<div class="sourceCode" id="cb926"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb926-1"><a href="共和分分析.html#cb926-1" tabindex="-1"></a>m3<span class="sc">$</span>beta     <span class="co"># 共和分行列</span></span></code></pre></div>
<pre><code>##            [,1]
## [1,]  1.0000000
## [2,] -0.8865273</code></pre>
<div class="sourceCode" id="cb928"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb928-1"><a href="共和分分析.html#cb928-1" tabindex="-1"></a>m3<span class="sc">$</span>Phip</span></code></pre></div>
<pre><code>##              [,1]        [,2]
## [1,]  0.451819715  0.29284889
## [2,] -0.001408246  0.20391696
## [3,] -0.300095060 -0.15097350
## [4,]  0.053592821  0.02759872</code></pre>
<div class="sourceCode" id="cb930"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb930-1"><a href="共和分分析.html#cb930-1" tabindex="-1"></a>m3<span class="sc">$</span>se.Phip</span></code></pre></div>
<pre><code>##            [,1]       [,2]
## [1,] 0.08844376 0.07774707
## [2,] 0.10139081 0.08913462
## [3,] 0.08599728 0.07569917
## [4,] 0.09393137 0.08267879</code></pre>
<ul>
<li><p>推定されたECM (修正後)
<span class="math display">\[ \Delta {\bf y}_t = \left[\begin{array}{r}
    -0.001 \\ 0.064
  \end{array}\right] [1,-0.887] {\bf y}_t  +
  \left[\begin{array}{rr}
    0.452 &amp; -0.001 \\ 0.293 &amp; 0.204
  \end{array} \right] \Delta {\bf y}_{t-1}
  \]</span>
<span class="math display">\[
      +\left[\begin{array}{rr}
    -0.300 &amp; 0.054 \\ -0.151 &amp; 0.028
  \end{array} \right] \Delta {\bf y}_{t-2} + \epsilon_t,\quad
  \hat{\Sigma}= \frac{1}{100} \left[\begin{array}{rr}
    4.00 &amp; 3.16 \\ 3.16 &amp; 3.10
  \end{array} \right]
  \]</span></p></li>
<li><p>→ 初期モデル(m1)と近い結果</p></li>
<li><p>``サンプルサイズが比較的大きい一方で低次元であり, 驚くことでない’’</p></li>
<li><p>(補足): <span class="math inline">\(w_t=1 \cdot Aaa_t - 0.887 \cdot Baa_t\)</span>が定常過程</p>
<ul>
<li><span class="math inline">\(w_t&gt;0\)</span> → Aaa_tのイールドが相対高, Baa_tが相対安　→ スプレッド”縮小”時</li>
<li>→ <span class="math inline">\({\bf y}_t\)</span>への影響; <span class="math inline">\([-0.001,0.064]&#39;w_t\)</span>
<ul>
<li>翌月のAaa_tイールドを<span class="math inline">\(0.001\cdot w_t\)</span>押し下げる</li>
<li>翌月のBaa_tイールドを<span class="math inline">\(0.064\cdot w_t\)</span>押し上げる</li>
<li>→ 翌月のスプレッドが”拡大”する方向に作用</li>
</ul></li>
</ul></li>
</ul>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="varモデル.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="多変量ボラティリティモデル.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
