<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 確率的トレンドと単位根検定 | 金融時系列解析</title>
  <meta name="description" content="5 確率的トレンドと単位根検定 | 金融時系列解析" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="5 確率的トレンドと単位根検定 | 金融時系列解析" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 確率的トレンドと単位根検定 | 金融時系列解析" />
  
  
  

<meta name="author" content="林 高樹" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="arimasarimaモデル.html"/>
<link rel="next" href="長期記憶過程.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> はじめに</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#時系列モデリング"><i class="fa fa-check"></i><b>1.1</b> 時系列モデリング</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#金融時系列データの特徴"><i class="fa fa-check"></i><b>1.2</b> 金融時系列データの特徴</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#金融時系列データの特徴-みずほ-8411-株価データの例"><i class="fa fa-check"></i>金融時系列データの特徴: みずほ (8411) 株価データの例</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#シミュレーションによるサンプルパス生成"><i class="fa fa-check"></i><b>1.3</b> シミュレーションによるサンプルパス生成</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#rにおける時系列オブジェクトクラスおよび関数の例"><i class="fa fa-check"></i><b>1.4</b> Rにおける時系列オブジェクト・クラスおよび関数の例</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#日付時間データに対するクラス"><i class="fa fa-check"></i><b>1.4.1</b> 日付・時間データに対するクラス</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#時系列データに対するクラス1-tsクラス"><i class="fa fa-check"></i><b>1.4.2</b> 時系列データに対するクラス(1): tsクラス</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#時系列データに対するクラス2-zooクラスとxtsクラス"><i class="fa fa-check"></i><b>1.4.3</b> 時系列データに対するクラス(2): zooクラスとxtsクラス</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#時系列データの分解"><i class="fa fa-check"></i><b>1.5</b> 時系列データの分解</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#トレンド抽出-平滑化-smoothing"><i class="fa fa-check"></i><b>1.5.1</b> トレンド抽出, 平滑化 (smoothing)</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#分解モデル"><i class="fa fa-check"></i><b>1.5.2</b> 分解モデル</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html"><i class="fa fa-check"></i><b>2</b> 定常性と自己相関関数</a>
<ul>
<li class="chapter" data-level="2.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#確率過程の2次特性-平均関数と自己共分散関数"><i class="fa fa-check"></i><b>2.1</b> 確率過程の2次特性: 平均関数と自己共分散関数</a></li>
<li class="chapter" data-level="2.2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#定常性-stationarity"><i class="fa fa-check"></i><b>2.2</b> 定常性 (stationarity)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#強定常性"><i class="fa fa-check"></i><b>2.2.1</b> 強定常性</a></li>
<li class="chapter" data-level="2.2.2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#弱定常性"><i class="fa fa-check"></i><b>2.2.2</b> 弱定常性</a></li>
<li class="chapter" data-level="2.2.3" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#ホワイトノイズ"><i class="fa fa-check"></i><b>2.2.3</b> ホワイトノイズ</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#標本平均と標本自己共分散関数"><i class="fa fa-check"></i><b>2.3</b> 標本平均と標本自己共分散関数</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#アンサンブル平均-vs-標本平均"><i class="fa fa-check"></i><b>2.3.1</b> アンサンブル平均 vs 標本平均</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#r操作-標本acf"><i class="fa fa-check"></i><b>2.4</b> R操作: 標本ACF</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#白色ノイズ"><i class="fa fa-check"></i><b>2.4.1</b> 白色ノイズ</a></li>
<li class="chapter" data-level="2.4.2" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#ランダムウォーク"><i class="fa fa-check"></i><b>2.4.2</b> ランダムウォーク</a></li>
<li class="chapter" data-level="2.4.3" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#非定常成分を含む時系列"><i class="fa fa-check"></i><b>2.4.3</b> 非定常成分を含む時系列</a></li>
<li class="chapter" data-level="2.4.4" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#線形定常時系列モデル"><i class="fa fa-check"></i><b>2.4.4</b> 線形・定常時系列モデル</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="定常性と自己相関関数.html"><a href="定常性と自己相関関数.html#母acf-vs-標本acf"><i class="fa fa-check"></i><b>2.5</b> 母ACF vs 標本ACF</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="armapqモデル.html"><a href="armapqモデル.html"><i class="fa fa-check"></i><b>3</b> ARMA<span class="math inline">\((p,q)\)</span>モデル</a>
<ul>
<li class="chapter" data-level="3.1" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルとは"><i class="fa fa-check"></i><b>3.1</b> ARMA<span class="math inline">\((p,q)\)</span>モデルとは</a>
<ul>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#因果性と反転可能性"><i class="fa fa-check"></i>因果性と反転可能性</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの意義"><i class="fa fa-check"></i>ARMA<span class="math inline">\((p,q)\)</span>モデルの意義</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルによる予測"><i class="fa fa-check"></i><b>3.2</b> ARMA<span class="math inline">\((p,q)\)</span>モデルによる予測</a></li>
<li class="chapter" data-level="3.3" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの推定"><i class="fa fa-check"></i><b>3.3</b> ARMA<span class="math inline">\((p,q)\)</span>モデルの推定</a></li>
<li class="chapter" data-level="3.4" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの同定-次数の特定"><i class="fa fa-check"></i><b>3.4</b> ARMA<span class="math inline">\((p,q)\)</span>モデルの同定 (次数の特定)</a></li>
<li class="chapter" data-level="3.5" data-path="armapqモデル.html"><a href="armapqモデル.html#r操作"><i class="fa fa-check"></i><b>3.5</b> R操作</a>
<ul>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの同定-acfpacfeacfの利用"><i class="fa fa-check"></i>ARMA<span class="math inline">\((p,q)\)</span>モデルの同定 (ACF/PACF/EACFの利用)</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#armapqモデルの推定診断"><i class="fa fa-check"></i>ARMA<span class="math inline">\((p,q)\)</span>モデルの推定・診断</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#パッケージforecastの利用"><i class="fa fa-check"></i>パッケージ{forecast}の利用</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="armapqモデル.html"><a href="armapqモデル.html#データ分析例-tsay-ch2より"><i class="fa fa-check"></i><b>3.6</b> データ分析例 (Tsay, Ch2より)</a>
<ul>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#標本acf"><i class="fa fa-check"></i>標本ACF</a></li>
<li class="chapter" data-level="" data-path="armapqモデル.html"><a href="armapqモデル.html#ar-ma-arma-2.42.6"><i class="fa fa-check"></i>AR, MA, ARMA (2.4–2.6)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html"><i class="fa fa-check"></i><b>4</b> ARIMA/SARIMAモデル</a>
<ul>
<li class="chapter" data-level="4.1" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#arimapdqモデルとは"><i class="fa fa-check"></i><b>4.1</b> ARIMA<span class="math inline">\((p,d,q)\)</span>モデルとは</a></li>
<li class="chapter" data-level="4.2" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#sarimapdqtimes-pdq_sモデル-周期sとは"><i class="fa fa-check"></i><b>4.2</b> SARIMA<span class="math inline">\((p,d,q)\times (P,D,Q)_s\)</span>モデル (周期<span class="math inline">\(s\)</span>)とは</a></li>
<li class="chapter" data-level="4.3" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#sarimaモデルのパス生成-パッケージsarimaの利用"><i class="fa fa-check"></i><b>4.3</b> SARIMAモデルのパス生成: パッケージ<strong>sarima</strong>の利用</a></li>
<li class="chapter" data-level="4.4" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#sarimaモデルの推定診断"><i class="fa fa-check"></i><b>4.4</b> SARIMAモデルの推定・診断</a>
<ul>
<li class="chapter" data-level="" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#パッケージforecastの利用-1"><i class="fa fa-check"></i>パッケージ<strong>forecast</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#データ分析例"><i class="fa fa-check"></i><b>4.5</b> データ分析例</a>
<ul>
<li class="chapter" data-level="" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#データセット-bonds"><i class="fa fa-check"></i>データセット: bonds</a></li>
<li class="chapter" data-level="" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#データセット-airpassengers"><i class="fa fa-check"></i>データセット: AirPassengers</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="arimasarimaモデル.html"><a href="arimasarimaモデル.html#外生変数があるケース"><i class="fa fa-check"></i><b>4.6</b> 外生変数があるケース</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html"><i class="fa fa-check"></i><b>5</b> 確率的トレンドと単位根検定</a>
<ul>
<li class="chapter" data-level="5.1" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#確率的トレンド-vs-確定的トレンド"><i class="fa fa-check"></i><b>5.1</b> 確率的トレンド vs 確定的トレンド</a></li>
<li class="chapter" data-level="5.2" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#単位根過程と見せかけの回帰"><i class="fa fa-check"></i><b>5.2</b> 単位根過程と見せかけの回帰</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#単位根過程"><i class="fa fa-check"></i><b>5.2.1</b> 単位根過程</a></li>
<li class="chapter" data-level="5.2.2" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#見せかけの回帰"><i class="fa fa-check"></i><b>5.2.2</b> 見せかけの回帰</a></li>
<li class="chapter" data-level="5.2.3" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#見せかけの回帰の判定"><i class="fa fa-check"></i><b>5.2.3</b> 見せかけの回帰の判定</a></li>
<li class="chapter" data-level="5.2.4" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#rで実行可能な主な単位根検定法"><i class="fa fa-check"></i><b>5.2.4</b> Rで実行可能な主な単位根検定法</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#augmented-dicky-fuller-adf-検定"><i class="fa fa-check"></i><b>5.3</b> Augmented Dicky-Fuller (ADF) 検定</a>
<ul>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#パッケージfunitroots"><i class="fa fa-check"></i>パッケージ<strong>fUnitRoots</strong></a></li>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#パッケージtseries"><i class="fa fa-check"></i>パッケージ<strong>tseries</strong></a></li>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#パッケージurca"><i class="fa fa-check"></i>パッケージ<strong>urca</strong></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#adf検定以外の検定法"><i class="fa fa-check"></i><b>5.4</b> ADF検定以外の検定法</a>
<ul>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#phillips-perron-pp-検定"><i class="fa fa-check"></i>Phillips-Perron (PP) 検定</a></li>
<li class="chapter" data-level="" data-path="確率的トレンドと単位根検定.html"><a href="確率的トレンドと単位根検定.html#kwiatkowski-phillips-schmidt-shin-kpss-検定"><i class="fa fa-check"></i>Kwiatkowski-Phillips-Schmidt-Shin (KPSS) 検定</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="長期記憶過程.html"><a href="長期記憶過程.html"><i class="fa fa-check"></i><b>6</b> 長期記憶過程</a>
<ul>
<li class="chapter" data-level="6.1" data-path="長期記憶過程.html"><a href="長期記憶過程.html#長期記憶過程のシミュレーション"><i class="fa fa-check"></i><b>6.1</b> 長期記憶過程のシミュレーション</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージfracdiffの利用"><i class="fa fa-check"></i>パッケージ<strong>fracdiff</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージlongmemoの利用"><i class="fa fa-check"></i>パッケージ<strong>longmemo</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="長期記憶過程.html"><a href="長期記憶過程.html#hurst指数の推定"><i class="fa fa-check"></i><b>6.2</b> Hurst指数の推定</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージpracmaの利用"><i class="fa fa-check"></i>パッケージ<strong>pracma</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージfractalの利用"><i class="fa fa-check"></i>パッケージ<strong>fractal</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデルの推定"><i class="fa fa-check"></i><b>6.3</b> ARFIMAモデルの推定</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージfracdiffの利用-1"><i class="fa fa-check"></i>パッケージ<strong>fracdiff</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#パッケージnsarfimaの利用"><i class="fa fa-check"></i>パッケージ<strong>nsarfima</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#階差次数dの代替的推定法"><i class="fa fa-check"></i>階差次数<span class="math inline">\(d\)</span>の代替的推定法</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデル-データ分析例-1"><i class="fa fa-check"></i><b>6.4</b> ARFIMAモデル: データ分析例 (1)</a></li>
<li class="chapter" data-level="6.5" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデル-データ分析例-2"><i class="fa fa-check"></i><b>6.5</b> ARFIMAモデル: データ分析例 (2)</a>
<ul>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#最適なarfimaモデルの選択および推定"><i class="fa fa-check"></i>最適なARFIMAモデルの選択および推定</a></li>
<li class="chapter" data-level="" data-path="長期記憶過程.html"><a href="長期記憶過程.html#arfimaモデルによる外挿予測"><i class="fa fa-check"></i>ARFIMAモデルによる外挿予測</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="レジームスイッチングモデル.html"><a href="レジームスイッチングモデル.html"><i class="fa fa-check"></i><b>7</b> レジーム・スイッチング・モデル</a>
<ul>
<li class="chapter" data-level="7.1" data-path="レジームスイッチングモデル.html"><a href="レジームスイッチングモデル.html#自己回帰マルコフスイッチングモデル-msm-ar"><i class="fa fa-check"></i><b>7.1</b> 自己回帰マルコフ・スイッチング・モデル (MSM-AR)</a></li>
<li class="chapter" data-level="7.2" data-path="レジームスイッチングモデル.html"><a href="レジームスイッチングモデル.html#パッケージnhmsarの利用"><i class="fa fa-check"></i><b>7.2</b> パッケージ<strong>NHMSAR</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="garchモデル.html"><a href="garchモデル.html"><i class="fa fa-check"></i><b>8</b> GARCHモデル</a>
<ul>
<li class="chapter" data-level="8.1" data-path="garchモデル.html"><a href="garchモデル.html#収益率データとarch効果"><i class="fa fa-check"></i><b>8.1</b> 収益率データとARCH効果</a></li>
<li class="chapter" data-level="8.2" data-path="garchモデル.html"><a href="garchモデル.html#archgarchモデル"><i class="fa fa-check"></i><b>8.2</b> ARCH/GARCHモデル</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garchpqモデル"><i class="fa fa-check"></i>GARCH(p,q)モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garchモデリング"><i class="fa fa-check"></i>GARCHモデリング</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="garchモデル.html"><a href="garchモデル.html#archgarchモデルのシミュレーション"><i class="fa fa-check"></i><b>8.3</b> ARCH/GARCHモデルのシミュレーション</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#パッケージfgarchの利用"><i class="fa fa-check"></i>パッケージ<strong>fGarch</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#archpモデル"><i class="fa fa-check"></i>ARCH(p)モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garchpqモデル-1"><i class="fa fa-check"></i>GARCH(p,q)モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#armapq-garchpqモデル"><i class="fa fa-check"></i>ARMA(p’,q’)-GARCH(p,q)モデル</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="garchモデル.html"><a href="garchモデル.html#archgarchモデルの適合"><i class="fa fa-check"></i><b>8.4</b> ARCH/GARCHモデルの適合</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#パッケージrugarchの利用"><i class="fa fa-check"></i>パッケージ<strong>rugarch</strong>の利用</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#iarch11"><i class="fa fa-check"></i>IARCH(1,1)</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#gjr-garch11"><i class="fa fa-check"></i>GJR-GARCH(1,1)</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#aparch"><i class="fa fa-check"></i>APARCH</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="garchモデル.html"><a href="garchモデル.html#garchモデル-データ分析例-tsay-ch4"><i class="fa fa-check"></i><b>8.5</b> GARCHモデル: データ分析例 (Tsay, Ch4)</a>
<ul>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#必要な関数やデータセットの入手"><i class="fa fa-check"></i>必要な関数やデータセットの入手</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#integrated-garch-モデル"><i class="fa fa-check"></i>Integrated GARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#garch-m-モデル"><i class="fa fa-check"></i>GARCH-M モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#exponential-garch-model"><i class="fa fa-check"></i>Exponential GARCH Model</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#threshold-garch-モデル"><i class="fa fa-check"></i>Threshold GARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#asymmetric-power-arch-モデル"><i class="fa fa-check"></i>Asymmetric Power ARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#nonsymmetric-garch-モデル"><i class="fa fa-check"></i>Nonsymmetric GARCH モデル</a></li>
<li class="chapter" data-level="" data-path="garchモデル.html"><a href="garchモデル.html#代替的アプリーチ間の比較"><i class="fa fa-check"></i>代替的アプリーチ間の比較</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="varモデル.html"><a href="varモデル.html"><i class="fa fa-check"></i><b>9</b> VARモデル</a>
<ul>
<li class="chapter" data-level="9.1" data-path="varモデル.html"><a href="varモデル.html#varpモデルのシミュレーション"><i class="fa fa-check"></i><b>9.1</b> VAR(<span class="math inline">\(p\)</span>)モデルのシミュレーション</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#パッケージmts-varsの利用"><i class="fa fa-check"></i>パッケージ<strong>MTS</strong>, <strong>vars</strong>の利用</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="varモデル.html"><a href="varモデル.html#varpモデルの構築"><i class="fa fa-check"></i><b>9.2</b> VAR(<span class="math inline">\(p\)</span>)モデルの構築</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varpモデルの次数同定"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>)モデルの次数同定</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varpモデルの推定"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>)モデルの推定</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varpモデル予測"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>)モデル予測</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="varモデル.html"><a href="varモデル.html#var解析"><i class="fa fa-check"></i><b>9.3</b> VAR解析</a>
<ul>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#varp-モデルの構築-復習"><i class="fa fa-check"></i>VAR(<span class="math inline">\(p\)</span>) モデルの構築 (復習)</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#グレンジャーの因果性検定"><i class="fa fa-check"></i>グレンジャーの因果性検定</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#インパルス応答"><i class="fa fa-check"></i>インパルス応答</a></li>
<li class="chapter" data-level="" data-path="varモデル.html"><a href="varモデル.html#予測誤差分散分解-forecast-error-variance-decomposition"><i class="fa fa-check"></i>予測誤差分散分解 (forecast error variance decomposition)</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="varモデル.html"><a href="varモデル.html#補足-分散共分散行列のコレスキー分解"><i class="fa fa-check"></i><b>9.4</b> 補足: 分散共分散行列のコレスキー分解</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="共和分分析.html"><a href="共和分分析.html"><i class="fa fa-check"></i><b>10</b> 共和分分析</a>
<ul>
<li class="chapter" data-level="10.1" data-path="共和分分析.html"><a href="共和分分析.html#見せかけの回帰-再掲"><i class="fa fa-check"></i><b>10.1</b> 見せかけの回帰 (再掲)</a>
<ul>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#durbin-watson検定"><i class="fa fa-check"></i>Durbin-Watson検定</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#rで実行可能な主な単位根検定法-1"><i class="fa fa-check"></i>Rで実行可能な主な単位根検定法</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="共和分分析.html"><a href="共和分分析.html#共和分分析-1"><i class="fa fa-check"></i><b>10.2</b> 共和分分析</a>
<ul>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#englegrangerの方法-philips-ouliaris検定"><i class="fa fa-check"></i>Engle–Grangerの方法 (Philips-Ouliaris検定)</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#johansenの方法"><i class="fa fa-check"></i>Johansenの方法</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="共和分分析.html"><a href="共和分分析.html#誤差修正モデル-データ分析例-tsay-mts-ch5"><i class="fa fa-check"></i><b>10.3</b> 誤差修正モデル: データ分析例 (Tsay, MTS, Ch5)</a>
<ul>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#共和分検定"><i class="fa fa-check"></i>共和分検定</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#johansenの方法-1"><i class="fa fa-check"></i>Johansenの方法</a></li>
<li class="chapter" data-level="" data-path="共和分分析.html"><a href="共和分分析.html#誤差修正モデル-ecm-の推定"><i class="fa fa-check"></i>誤差修正モデル (ECM) の推定</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="動的線形モデル.html"><a href="動的線形モデル.html"><i class="fa fa-check"></i><b>11</b> 動的線形モデル</a>
<ul>
<li class="chapter" data-level="11.1" data-path="動的線形モデル.html"><a href="動的線形モデル.html#局所水準-local-level-モデル"><i class="fa fa-check"></i><b>11.1</b> 局所水準 (local level) モデル</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#フィルタリング"><i class="fa fa-check"></i>フィルタリング</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#スムージング-平滑化"><i class="fa fa-check"></i>スムージング (平滑化)</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#状態予測"><i class="fa fa-check"></i>状態予測</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#モデル診断-1"><i class="fa fa-check"></i>モデル診断</a></li>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#モデルパラメータの推定"><i class="fa fa-check"></i>モデル・パラメータの推定</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="動的線形モデル.html"><a href="動的線形モデル.html#local-level-plus-seasonal-componentモデル"><i class="fa fa-check"></i><b>11.2</b> local level plus seasonal componentモデル</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#状態予測-1"><i class="fa fa-check"></i>状態予測</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="動的線形モデル.html"><a href="動的線形モデル.html#動的回帰モデル"><i class="fa fa-check"></i><b>11.3</b> 動的回帰モデル</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#スムージング"><i class="fa fa-check"></i>スムージング</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="動的線形モデル.html"><a href="動的線形モデル.html#sur-seemingly-unrelated-regression-モデル-3.3.3"><i class="fa fa-check"></i><b>11.4</b> SUR (Seemingly Unrelated Regression) モデル (3.3.3)</a>
<ul>
<li class="chapter" data-level="" data-path="動的線形モデル.html"><a href="動的線形モデル.html#参考文献"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix 参考文献</b></span></li>
<li class="chapter" data-level="A" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html"><i class="fa fa-check"></i><b>A</b> バブル (生成・崩壊) 検出</a>
<ul>
<li class="chapter" data-level="A.1" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#検定法に関する最近のレビュー論文"><i class="fa fa-check"></i><b>A.1</b> 検定法に関する最近のレビュー論文</a></li>
<li class="chapter" data-level="A.2" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#supreme-adf検定sadf-pwy-2011-generalized-supreme-adf-検定gsadf-psy-2015"><i class="fa fa-check"></i><b>A.2</b> Supreme ADF検定/SADF (PWY, 2011), Generalized supreme ADF 検定/GSADF (PSY, 2015)</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#数理ファイナンス-jarrow-protterら"><i class="fa fa-check"></i><b>A.2.1</b> 数理ファイナンス (Jarrow, Protterら)</a></li>
<li class="chapter" data-level="A.2.2" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#経済物理学-sornetteら"><i class="fa fa-check"></i><b>A.2.2</b> 経済物理学 (Sornetteら)</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#実証分析"><i class="fa fa-check"></i><b>A.3</b> 実証分析</a>
<ul>
<li class="chapter" data-level="" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#株式市場の例"><i class="fa fa-check"></i>株式市場の例</a></li>
<li class="chapter" data-level="" data-path="バブル-生成崩壊-検出.html"><a href="バブル-生成崩壊-検出.html#暗号資産市場の例"><i class="fa fa-check"></i>暗号資産市場の例</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html"><i class="fa fa-check"></i><b>B</b> 長期記憶過程</a>
<ul>
<li class="chapter" data-level="B.1" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#理論概説"><i class="fa fa-check"></i><b>B.1</b> 理論・概説</a></li>
<li class="chapter" data-level="B.2" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#株式市場"><i class="fa fa-check"></i><b>B.2</b> 株式市場</a></li>
<li class="chapter" data-level="B.3" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#外国為替市場"><i class="fa fa-check"></i><b>B.3</b> 外国為替市場</a></li>
<li class="chapter" data-level="B.4" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#コモディティ暗号資産"><i class="fa fa-check"></i><b>B.4</b> コモディティ・暗号資産</a></li>
<li class="chapter" data-level="B.5" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#vix"><i class="fa fa-check"></i><b>B.5</b> VIX</a></li>
<li class="chapter" data-level="B.6" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#高頻度データ-ボラティリティ-注文フロー等"><i class="fa fa-check"></i><b>B.6</b> 高頻度データ (ボラティリティ, 注文フロー等)</a></li>
<li class="chapter" data-level="B.7" data-path="長期記憶過程-1.html"><a href="長期記憶過程-1.html#長期記憶性の発生要因-非長期記憶モデルによる近似"><i class="fa fa-check"></i><b>B.7</b> 長期記憶性の発生要因, 非長期記憶モデルによる近似</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html"><i class="fa fa-check"></i><b>C</b> Markov switching/ regime switchingモデル</a>
<ul>
<li class="chapter" data-level="C.1" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#理論概説-1"><i class="fa fa-check"></i><b>C.1</b> 理論・概説</a></li>
<li class="chapter" data-level="C.2" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#株式市場-1"><i class="fa fa-check"></i><b>C.2</b> 株式市場</a></li>
<li class="chapter" data-level="C.3" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#金利債券市場"><i class="fa fa-check"></i><b>C.3</b> 金利・債券市場</a></li>
<li class="chapter" data-level="C.4" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#外国為替市場-1"><i class="fa fa-check"></i><b>C.4</b> 外国為替市場</a></li>
<li class="chapter" data-level="C.5" data-path="markov-switching-regime-switchingモデル.html"><a href="markov-switching-regime-switchingモデル.html#アセットアロケーション"><i class="fa fa-check"></i><b>C.5</b> アセット・アロケーション</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html"><i class="fa fa-check"></i><b>D</b> ARCH/GARCHモデル</a>
<ul>
<li class="chapter" data-level="D.1" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#概説"><i class="fa fa-check"></i><b>D.1</b> 概説</a></li>
<li class="chapter" data-level="D.2" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#arch-model"><i class="fa fa-check"></i><b>D.2</b> ARCH model</a></li>
<li class="chapter" data-level="D.3" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#garch-model"><i class="fa fa-check"></i><b>D.3</b> GARCH model</a></li>
<li class="chapter" data-level="D.4" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#arch-m-model"><i class="fa fa-check"></i><b>D.4</b> ARCH-M Model</a></li>
<li class="chapter" data-level="D.5" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#gjr-model"><i class="fa fa-check"></i><b>D.5</b> GJR model</a></li>
<li class="chapter" data-level="D.6" data-path="archgarchモデル-1.html"><a href="archgarchモデル-1.html#aparch-model"><i class="fa fa-check"></i><b>D.6</b> APARCH model</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">金融時系列解析</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="確率的トレンドと単位根検定" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> 確率的トレンドと単位根検定<a href="確率的トレンドと単位根検定.html#確率的トレンドと単位根検定" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>次のような定数項付きのランダムウォークを考える:
<span class="math display">\[
X_t = \beta + X_{t-1}  +Z_t, \quad \{Z_t\} \sim WN(0,\sigma^2).
\]</span>
いま, 定数項<span class="math inline">\(\beta \ne 0\)</span>であれば, バイアス有りランダムウォークとも呼ばれる.
時点<span class="math inline">\(t=0\)</span>において初期値<span class="math inline">\(X_0=\alpha\)</span>からスタートしたとすると,
再帰的代入によって,
<span class="math display">\[
X_t  = \alpha + \beta \cdot t + \eta_t
\]</span>
のように書ける. ただし, <span class="math inline">\(\eta_t = \sum_{s=1}^{t} Z_s\)</span>と定義した (<span class="math inline">\(\sum_{s=1}^{0}=0\)</span>と表記). すなわち, 定数項<span class="math inline">\(\beta\)</span>は時点が1ステップ進むことに<span class="math inline">\(X_t\)</span>の期待値が変化する量 (直線の傾き) を, 初期値<span class="math inline">\(\alpha\)</span>は<span class="math inline">\(t=0\)</span>における<span class="math inline">\(X_t\)</span>の期待値の値 (定数項) を表し, 全体として, <span class="math inline">\(\alpha + \beta \cdot t\)</span>は<span class="math inline">\(X_t\)</span>の確定的な線形トレンドを構成している.
一方, 右辺第3項 <span class="math inline">\(\eta_t\)</span>は, (定数項なし, 初期値0スタートの) ランダムウォークであり,
<span class="math inline">\(I(1)\)</span>, あるいは<span class="math inline">\(ARIMA(0,1,0)\)</span>と表記される確定過程のクラスの代表例である. 第3項<span class="math inline">\(\eta_t\)</span>は, それ自体が<strong>確率的トレンド</strong>を形成する.</p>
<p>以上のように, 定数項付き (<span class="math inline">\(\beta \ne 0\)</span>) のランダムウォークは, 線形トレンド部分と確率的トレンド部分を同時に持っている.
一方, 定数項なし (<span class="math inline">\(\beta = 0\)</span>) のランダムウォークは, 線形トレンド (傾き) を持たず確率的トレンドのみを持つが,
初期値(<span class="math inline">\(X_0=\alpha\)</span>)の値だけ<span class="math inline">\(y\)</span>軸方向にシフト (定数項) する.</p>
<p>次に, この定数項付きのランダムウォークを一般化して「確率的トレンド」モデルとして定義し, 一方, 第3項<span class="math inline">\(\eta_t\)</span>が (ランダムウォークせず) 確率的トレンドを持たないような「確定的トレンド」モデルとの比較を行う.</p>
<div id="確率的トレンド-vs-確定的トレンド" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> 確率的トレンド vs 確定的トレンド<a href="確率的トレンドと単位根検定.html#確率的トレンド-vs-確定的トレンド" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>-「確定的 (線形) トレンド (deterministic (linear) trend)」モデル
<span class="math display">\[
X_{t}={\color{olive}\alpha}+\beta\cdot t+\eta_{t},
\quad \{\eta_{t}\}\sim\mathrm{ARMA}(p,q)
\]</span></p>
<p>-「確率的トレンド (stochastic trend)」モデル
<span class="math display">\[
X_{t}={\color{olive}\alpha}+\beta\cdot t+\eta_{t},
\quad \{\eta_{t}\}\sim\mathrm{ARIMA}(p,1,q)
\]</span></p>
<p>より正確には, この「確率的トレンド」モデルは,
「確定的トレンド」を表す項<span class="math inline">\(\alpha+\beta\cdot t\)</span>と
文字通り「確率的トレンド」をもたらす項<span class="math inline">\(\eta_t\)</span>の
二つの成分が重なり合って生成されている.</p>
<p>例えば, <span class="math inline">\(\alpha=0,\beta=0.05,\phi(z)=1-\phi_{1}z\)</span> において, 順に, <span class="math inline">\(\phi_{1}=1,0.98, 0.95\)</span>の場合について,
同一の乱数を用いて一本のサンプルパスを生成した場合を図示する. <!--
(テクニカルな注: 厳密には, いずれのケースも初期値$X_0=0$からシミュレーションをスタートしているため, 確定的トレンドの二つのケースは, 事象 $\{X_0=0\}$の条件の下での定常性を有する確率過程のサンプルパスである. 一方, 確率的トレンドのケースは初期値の設定有無によらず常に非定常である.)
-->
シミュレーションでは, 便宜上 <span class="math inline">\(X_0=0\)</span> (あるいは, <span class="math inline">\(\eta_0=0\)</span>) を初期値として与え, その後の値を再帰的に生成した.
この場合, 初期時点付近の観測値は, 確定的トレンドのケースにおいては, 定常分布からの逸脱を含む過渡状態となるが, 十分大きな <span class="math inline">\(t\)</span> に対しては, トレンドを除いたプロセス <span class="math inline">\(\{X_t - \alpha - \beta \cdot t\}\)</span> は定常 ARMA 過程の分布に漸近的に近づく. 一方, 確率的トレンドのケースは初期値の設定有無によらず常に非定常である.</p>
<p><img src="042-unitroot_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>これらの「確定的な(線形トレンド)」モデルと「確率的トレンド」モデルは, モデルの形状は類似しているが,
<!-- 見かけ上は区別がしにくいケースが多いが,--> 時系列的な性質は大きく異なる.
特に, 確率的トレンドを持つ場合は, 時間と共に観測時系列の
分散は増大していく一方, それを持たない場合には, 時間を通じて
定常 (分散は一定) であるという違いがある.</p>
<p>ある時系列データが, (より正確にはその背後にある確率過程が) 確率的トレンドを持つか否かを定量的に評価する方法が
<strong>単位根検定 (unit root test) </strong>である.</p>
<!--
通常, 私達が手にする実際の時系列データは, それを生成した"真"の確率過程について分からない.
そのような中で, その背後の確率過程が持っているのが
確定的トレンドなのか, 確率的トレンドなのかを
目視により判断するのは容易ではない.
-->
<p>「確率的トレンド」モデルは,
確定的トレンド部分と確率的トレンド部分を同時に
持っていたが,
私達が手にする実際の時系列データが見かけ上トレンドを
持っている時, それを確定的トレンドの部分と
確率的トレンドの部分に仕分けするのは容易ではない.</p>
<p>単位根検定を実施する際に,
厄介なことに, 確定的線形トレンドを構成するパラメータ
切片項 (定数) <span class="math inline">\(\alpha\)</span>, 傾き <span class="math inline">\(\beta\)</span>の有無によって,
単位根検定を行う際の理論的な評価の計算方法が変わる
ため, 検定結果がパラメータに関する仮定に依存する
という課題が存在している.
(正確には, 単位根帰無仮説の下で, 検定統計量が
従う漸近的な確率分布が異なることによって,
それより計算される帰無仮説の棄却点が異なる)</p>
<p>例えば, より具体的には, 主要な単位根検定法であるADF検定
(その特別な場合のDF検定)においては, 確定的線形トレンドについて,</p>
<ol style="list-style-type: decimal">
<li>トレンドが存在しない (<span class="math inline">\(\alpha=\beta=0\)</span>),</li>
<li>定数項のみ存在する (<span class="math inline">\(\beta=0\)</span>, <span class="math inline">\(\alpha\)</span>に制約なし),</li>
<li>定数項および傾きが存在する (<span class="math inline">\(\alpha,\beta\)</span>に制約なし),</li>
</ol>
<p>の3ケースについて, 同一の検定統計量が異なる棄却域を持つため,
検定を実施するにあたり確定的トレンドがどのケースに
当てはまるのかを予め指定する必要がある.
ところが, <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>が
あるか否かは事前に分からない, あるいは, 上の例を見てもデータからは判断が難しいことも多い (グレイの点線がないものとしてプロットを目視してみよう).
<!-- PP検定, KPSS検定では, どうやら, level, trendしかない...
alpha=beta=0は, 本質的にbeta=0のケースに含まれる??
alpha!=0とは, X_tの値が全体にalphaだけシフトするのみ--></p>
<p>さらに, 単位根検定は十分な標本サイズの下で行うことが前提となっている.
(正確には, 棄却点の評価を行うのに必要な帰無仮説の下での
検定統計量の従う確率分布は, 標本サイズを十分大きくとった場合,
すなわち, 漸近分布として得られる)</p>
<p>実践において, ある時系列が単位根過程かどうか判断するには,
単位根検定を行うのと並行して, その時系列が
それ自体に対して取引が行われているような
資産価格系列かどうか, すなわち, ランダムウォークするか
(トレンドが予測できないような挙動を持つかどうか),
あるいは, ある一定水準 (長期的な均衡値) の周りで
平均回帰的 (mean reversion) な性質を持つ系列かどうか
など, 対象に関する前提知識や経験を活かすことが
重要である.</p>
</div>
<div id="単位根過程と見せかけの回帰" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> 単位根過程と見せかけの回帰<a href="確率的トレンドと単位根検定.html#単位根過程と見せかけの回帰" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="単位根過程" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> 単位根過程<a href="確率的トレンドと単位根検定.html#単位根過程" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>ランダムウォークモデル (I(1))のパス生成</li>
</ul>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="確率的トレンドと単位根検定.html#cb336-1" tabindex="-1"></a><span class="co"># require(sarima)</span></span>
<span id="cb336-2"><a href="確率的トレンドと単位根検定.html#cb336-2" tabindex="-1"></a>Tlen <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb336-3"><a href="確率的トレンドと単位根検定.html#cb336-3" tabindex="-1"></a>Seedv <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb336-4"><a href="確率的トレンドと単位根検定.html#cb336-4" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb336-5"><a href="確率的トレンドと単位根検定.html#cb336-5" tabindex="-1"></a><span class="fu">set.seed</span>(Seedv)</span>
<span id="cb336-6"><a href="確率的トレンドと単位根検定.html#cb336-6" tabindex="-1"></a><span class="co"># x &lt;- sim_sarima(n = Tlen, model = list(iorder = 1, sigma2 = 1)) # (1-B)X_t = e_t (random walk)</span></span>
<span id="cb336-7"><a href="確率的トレンドと単位根検定.html#cb336-7" tabindex="-1"></a><span class="co"># y &lt;- sim_sarima(n = Tlen, model = list(iorder = 1, sigma2 = 1))</span></span>
<span id="cb336-8"><a href="確率的トレンドと単位根検定.html#cb336-8" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n =</span> Tlen, <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)))</span>
<span id="cb336-9"><a href="確率的トレンドと単位根検定.html#cb336-9" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n =</span> Tlen, <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)))</span>
<span id="cb336-10"><a href="確率的トレンドと単位根検定.html#cb336-10" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb336-11"><a href="確率的トレンドと単位根検定.html#cb336-11" tabindex="-1"></a><span class="co"># par(mfrow=c(1,2))</span></span>
<span id="cb336-12"><a href="確率的トレンドと単位根検定.html#cb336-12" tabindex="-1"></a><span class="co"># acf(x)   # 自己相関(ACF)</span></span>
<span id="cb336-13"><a href="確率的トレンドと単位根検定.html#cb336-13" tabindex="-1"></a><span class="co"># pacf(x)   # 偏自己相関(PACF)</span></span>
<span id="cb336-14"><a href="確率的トレンドと単位根検定.html#cb336-14" tabindex="-1"></a><span class="co"># matplot(cbind(x, y), type = &quot;l&quot;)</span></span>
<span id="cb336-15"><a href="確率的トレンドと単位根検定.html#cb336-15" tabindex="-1"></a><span class="fu">ts.plot</span>(<span class="fu">cbind</span>(x, y), <span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/sim_path-1.png" width="672" /></p>
</div>
<div id="見せかけの回帰" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> 見せかけの回帰<a href="確率的トレンドと単位根検定.html#見せかけの回帰" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="確率的トレンドと単位根検定.html#cb337-1" tabindex="-1"></a>reslm <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb337-2"><a href="確率的トレンドと単位根検定.html#cb337-2" tabindex="-1"></a><span class="fu">summary</span>(reslm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.049 -2.862  1.383  3.172  5.519 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.42205    0.68668   0.615     0.54    
## x           -0.51303    0.09909  -5.178 1.18e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.752 on 99 degrees of freedom
## Multiple R-squared:  0.2131, Adjusted R-squared:  0.2051 
## F-statistic: 26.81 on 1 and 99 DF,  p-value: 1.182e-06</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="確率的トレンドと単位根検定.html#cb339-1" tabindex="-1"></a><span class="fu">plot</span>(x, y)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/spur_reg-1.png" width="672" /></p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="確率的トレンドと単位根検定.html#cb340-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">as.numeric</span>(x), <span class="fu">as.numeric</span>(y))</span>
<span id="cb340-2"><a href="確率的トレンドと単位根検定.html#cb340-2" tabindex="-1"></a><span class="fu">abline</span>(reslm)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/spur_reg-2.png" width="672" /></p>
</div>
<div id="見せかけの回帰の判定" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> 見せかけの回帰の判定<a href="確率的トレンドと単位根検定.html#見せかけの回帰の判定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="確率的トレンドと単位根検定.html#cb341-1" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="確率的トレンドと単位根検定.html#cb345-1" tabindex="-1"></a><span class="fu">dwtest</span>(reslm)</span></code></pre></div>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  reslm
## DW = 0.080227, p-value &lt; 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<ul>
<li>Durbin-Watson検定 (簡便法)
<ul>
<li>回帰残差の系列相関の有無を検定</li>
<li><span class="math inline">\(DW \approx 2(1-\rho)\)</span></li>
<li><span class="math inline">\(0&lt;DW&lt;4\)</span>. 無相関 <span class="math inline">\(\Leftrightarrow DW=2\)</span></li>
<li>見せかけの回帰の場合. DWが小さい傾向 (正の系列相関)</li>
</ul></li>
<li>代替法: Engle-Granger検定</li>
<li>「見せかけの回帰」への対処法については後日扱う.</li>
</ul>
</div>
<div id="rで実行可能な主な単位根検定法" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Rで実行可能な主な単位根検定法<a href="確率的トレンドと単位根検定.html#rで実行可能な主な単位根検定法" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Rでは単位根検定を実行するための多くの関数が用意されている.
引数の指定方法や出力表示などの仕様が異なるので,
色々実行して自分が使いやすいと感じるものを選ぶと良いだろう.</p>
<ul>
<li>ADF検定: <strong>tseries</strong>内, <code>adf.test()</code>; <strong>fUnitRoots</strong>内, <code>unitrootTest()</code>, <code>adfTest()</code></li>
<li>Phillips-Perron(PP)検定: <strong>urca</strong>内, <code>ur.pp()</code>; <strong>tseries</strong>内, <code>pp.test()</code>
<ul>
<li>PP検定は, 沖本, pp.118–120参照</li>
</ul></li>
<li>KPSS検定: <strong>urca</strong>内, <code>ur.kpss()</code>; <strong>tseries</strong>内, <code>kpss.test()</code>
<ul>
<li>KPSS検定は, 福地・伊藤, pp.139–140参照</li>
</ul></li>
<li>その他の検定法: <strong>fUnitRoots</strong>内, <code>urersTest()</code> (Elliott-Rothenberg-Stock検定), <code>urspTest()</code> (Schmidt-Phillips検定), <code>urzaTest()</code> (Zivot-Andrews), 等</li>
</ul>
</div>
</div>
<div id="augmented-dicky-fuller-adf-検定" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Augmented Dicky-Fuller (ADF) 検定<a href="確率的トレンドと単位根検定.html#augmented-dicky-fuller-adf-検定" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>単位根検定としてもっとも良く用いられるのが Augmented Dicky-Fuller (ADF) 検定である.</p>
<p>ADF検定は, 時系列<span class="math inline">\(\{X_t\}\)</span>が, 確定的トレンド (線形トレンド) にAR(<span class="math inline">\(p\)</span>)に従う誤差を伴って観測されたと想定する:
<span class="math display">\[
X_{t}=\alpha+\beta\cdot t+\eta_{t},\quad\eta_{t}=\phi_{1}\eta_{t-1}+\cdots+\phi_{p}\eta_{t-p}+Z_{t}\quad Z_{t}\sim IID(0,\sigma^{2})\qquad(\eta_{0}=0)
\]</span>
これを次式のように変形する:
<span class="math display">\[
\Delta X_{t}=a+bt+\kappa X_{t-1}+\sum_{j=1}^{p-1}\delta_{j}\Delta X_{t-j}+Z_{t}
\]</span>
但し, <span class="math inline">\(\kappa=-(1-\sum_{j=1}^{p}\phi_{j}), \,a=-\kappa\alpha+\beta\sum_{j=1}^{p}j\phi_{j},\, b=-\kappa\beta.\)</span></p>
<p>ADF検定は, この<span class="math inline">\(\{\Delta X_t\}\)</span>に対する回帰式 (“ADF回帰モデル”) の<span class="math inline">\(X_{t-1}\)</span>の係数の大きさに基づいて単位根検定を行う.</p>
<ul>
<li><span class="math inline">\(H_{0}:\kappa=0\)</span> (単位根あり) vs. <span class="math inline">\(H_{1}:\kappa&lt;0\)</span> (単位根なし)</li>
<li>ADF (Augmented DF) 検定統計量: <span class="math inline">\(X_{t-1}\)</span>の回帰係数<span class="math inline">\(\kappa\)</span>の最小二乗推定量 <span class="math inline">\(\hat{\kappa}\)</span>に対して,
<span class="math display">\[
ADF=\frac{\hat{\kappa}}{s.e.(\hat{\kappa})}
\]</span></li>
</ul>
<p>ADF統計量は <span class="math inline">\(\hat{\kappa}\)</span>の“<span class="math inline">\(t\)</span>値”にほかならず,
この値が, 0から下方に (負の方向に) 乖離するほど, 単位根帰無仮説が棄却されやすい, すなわち, (単位根を持たない) トレンド定常モデルである可能性が高いと言える.</p>
<!--- SASマニュアル, p.244, 3つの検定法を紹介 -->
<!--- wikiでは, tau検定のみ紹介 -->
<!---
ADF (Augmented DF) 検定には, 回帰係数 ($\kappa$の$最小二乗推定量 $\hat{\kappa}$) に基づくもの (“$\rho$テスト”とも呼ばれる)と, $\hat{\kappa}$の$t$値に基づくもの (“$\tau$テスト”), さらに, $F$ 検定がある.

通常, “ADF検定”と言うときは, 二番目のもの, すなわち, 以下のように計算される“ADF検定統計量”
\[
ADF=\frac{\hat{\kappa}}{s.e.(\hat{\kappa})}
\]
をベースにした検定を指すことが多いようである.
--->
<!---
“$\rho$テスト”“normailized bias test”
-->
<p>ADF検定は, (その特別な場合であるDickey-Fuller検定と同様に) 確定的トレンドの有無により, 3つのモデル, 具体的には, (i) 定数項も1次トレンドも存在しない場合 (<span class="math inline">\(a=0,b=0\)</span>), (ii) 定数項のみ存在する場合 (<span class="math inline">\(b=0, a\)</span>制約なし), (iii) 定数項も1次トレンドも存在する場合 (<span class="math inline">\(a,b\)</span> 制約なし)
の3つのケースがあり, 各々のケースにより検定統計量が帰無仮説の下で従う (漸近的) 検定分布が異なるため, 検定結果が異なる可能性のあることに注意が必要である.</p>
<p>ADF統計量は, “<span class="math inline">\(t\)</span>値”の形をしているものの, いずれのケースにおいても, 帰無仮説の下で, <span class="math inline">\(t\)</span>分布には (漸近的にも) 従わない.</p>
<p>なお, オリジナルのDicky and Fuller (81) にもある通り,
ADF検定には, このADF統計量に基づく検定 (“<span class="math inline">\(\tau\)</span>検定”) のほか, “<span class="math inline">\(\rho\)</span>統計量” (または, “正則化されたバイアス (normalized bias) 統計量”)
<span class="math display">\[
Z=T \hat{\kappa}
\]</span>
に基づく“<span class="math inline">\(\rho\)</span>検定” (<span class="math inline">\(T\)</span>はサンプルサイズ),
さらに, 単位根とトレンドの有無を同時に検定する, “<span class="math inline">\(F\)</span>値” (“<span class="math inline">\(\phi\)</span>統計量”) に基づく“<span class="math inline">\(F\)</span>検定”がある
(同様に, 帰無仮説の下で, <span class="math inline">\(F\)</span>分布には (漸近的にも) 従わない).</p>
<p>ADF検定の実行前に, この <span class="math inline">\(\{\Delta X_t\}\)</span> 式におけるラグ次数 (<span class="math inline">\(p-1\)</span>) の大きさを決める必要がある.
手動によるアプローチ, 例えば, 十分大きな <span class="math inline">\(p\)</span> から値を順次小さくしていき, 係数の <span class="math inline">\(t\)</span> 値を調べるアプローチや, AICやBICなどの情報量基準を使って決定するアプローチなどがある.</p>
<p>例えば, パッケージ<strong>urca</strong>の関数<code>ur.df()</code>を使えば, AIC/BICによって <span class="math inline">\(p\)</span> の大きさを自動選択することができる.</p>
<p>ADF検定は, 標本サイズが十分大きいことを想定しているため, 小標本の時は結果の信頼性が保証されず注意が必要である.</p>
<p>以下では, Rを使って, ADF検定を幾つかのデータセットに対して実行する.</p>
<div id="パッケージfunitroots" class="section level3 unnumbered hasAnchor">
<h3>パッケージ<strong>fUnitRoots</strong><a href="確率的トレンドと単位根検定.html#パッケージfunitroots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>まず, ADF検定を行う二つのR関数<code>unitrootTest()</code>, <code>adfTest()</code>の実行例を示す.</p>
<pre><code>adfTest(): Banerjee&#39;s et al.(93)による検定統計量の計算
unitrootTest(): McKinnons(96) のアプローチによる検定統計量の計算
用法:
adfTest(x, lags = 1, type = c(&quot;nc&quot;, &quot;c&quot;, &quot;ct&quot;), title = NULL, 
    description = NULL)
unitrootTest(x, lags = 1, type = c(&quot;nc&quot;, &quot;c&quot;, &quot;ct&quot;), title = NULL, 
    description = NULL)
引数:
- type: &quot;nc&quot;(定数項・時間トレンド項共なし), &quot;c&quot;(定数項のみ有), &quot;ct&quot;(定数項・時間トレンド項共有)
- lags: 誤差項の持つ最大ラグ数</code></pre>
<p>上記シミュレーションデータに対して, ADF検定を実行する.</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="確率的トレンドと単位根検定.html#cb348-1" tabindex="-1"></a><span class="fu">library</span>(fUnitRoots)</span>
<span id="cb348-2"><a href="確率的トレンドと単位根検定.html#cb348-2" tabindex="-1"></a><span class="fu">adfTest</span>(x, <span class="at">type =</span> <span class="st">&quot;nc&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: 0.282
##   P VALUE:
##     0.703 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="確率的トレンドと単位根検定.html#cb350-1" tabindex="-1"></a><span class="fu">unitrootTest</span>(x, <span class="at">type =</span> <span class="st">&quot;nc&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     DF: 0.282
##   P VALUE:
##     t: 0.7657 
##     n: 0.7506 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<!--
**自主課題**:
二つの関数の結果を比較せよ.
-->
<p>関数<code>unitrootTest()</code>には, 2つの統計量 “t”と“n” の<span class="math inline">\(p\)</span>値が出力されている.
“t”が<span class="math inline">\(\tau\)</span>検定, “n”が<span class="math inline">\(\rho\)</span>検定の結果にほかならない.</p>
<p><code>adfTest()</code>の結果と, <code>unitrootTest()</code>の結果を比較すると,
ADF検定統計量は同じ (0.282) 値を取っているものの,
<span class="math inline">\(p\)</span>値の大きさ (後者については “t” を参照) 異なったものとなっている
(それぞれ, 0.703, 0.7657). これは, 帰無分布の近似計算の方法,
すなわち<span class="math inline">\(p\)</span>値算出のアルゴリズムの違いを反映したものである.</p>
<pre><code>(参考)
- `unitrootTest()`: MacKinnon (1994, 1996), シミュレーション結果を多項式回帰（response surface）で近似し，連続的に p 値を計算する方法
- `adfTest()`: Banerjee et al. (1993), サンプルサイズとモデル仕様ごとにシミュレーションで表を作り，その間を補間する方法

MacKinnonの response surface に基づく近似は，EViews, Stataなどでも採用されている. より正確で標準的.

`fUnitRoots` の作者自身も，`unitrootTest()` を “the same (ADF) test based on McKinnon&#39;s statistics” と位置付けている (ADF の“改良版”に近い扱い).</code></pre>
<p>このデータセットに関しては, いずれの<span class="math inline">\(p\)</span>値をみても,
時系列<span class="math inline">\(x\)</span>に対して, 単位根帰無仮説は棄却されない.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="確率的トレンドと単位根検定.html#cb353-1" tabindex="-1"></a><span class="fu">adfTest</span>(y, <span class="at">type =</span> <span class="st">&quot;nc&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -0.7206
##   P VALUE:
##     0.3835 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="確率的トレンドと単位根検定.html#cb355-1" tabindex="-1"></a><span class="fu">unitrootTest</span>(y, <span class="at">type =</span> <span class="st">&quot;nc&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     DF: -0.7206
##   P VALUE:
##     t: 0.4021 
##     n: 0.522 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<p>→ いずれも, 帰無仮説 (<span class="math inline">\(\phi_1=1\)</span>) を棄却せず (単位根有り).</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="確率的トレンドと単位根検定.html#cb357-1" tabindex="-1"></a><span class="fu">adfTest</span>(x, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -1.4551
##   P VALUE:
##     0.5166 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="確率的トレンドと単位根検定.html#cb359-1" tabindex="-1"></a><span class="co"># unitrootTest(x, type = &quot;c&quot;, lags = 1)</span></span>
<span id="cb359-2"><a href="確率的トレンドと単位根検定.html#cb359-2" tabindex="-1"></a><span class="fu">adfTest</span>(y, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -1.0635
##   P VALUE:
##     0.6617 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="確率的トレンドと単位根検定.html#cb361-1" tabindex="-1"></a><span class="co"># unitrootTest(y, type = &quot;c&quot;, lags = 1)</span></span></code></pre></div>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="確率的トレンドと単位根検定.html#cb362-1" tabindex="-1"></a><span class="fu">adfTest</span>(x, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -1.4551
##   P VALUE:
##     0.5166 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="確率的トレンドと単位根検定.html#cb364-1" tabindex="-1"></a><span class="co"># unitrootTest(x, type = &quot;ct&quot;, lags = 1)</span></span>
<span id="cb364-2"><a href="確率的トレンドと単位根検定.html#cb364-2" tabindex="-1"></a><span class="fu">adfTest</span>(y, <span class="at">type =</span> <span class="st">&quot;c&quot;</span>, <span class="at">lags =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Title:
##  Augmented Dickey-Fuller Test
## 
## Test Results:
##   PARAMETER:
##     Lag Order: 1
##   STATISTIC:
##     Dickey-Fuller: -1.0635
##   P VALUE:
##     0.6617 
## 
## Description:
##  Tue Jan 20 13:16:46 2026 by user:</code></pre>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="確率的トレンドと単位根検定.html#cb366-1" tabindex="-1"></a><span class="co"># unitrootTest(y, type = &quot;ct&quot;, lags = 1)</span></span></code></pre></div>
</div>
<div id="パッケージtseries" class="section level3 unnumbered hasAnchor">
<h3>パッケージ<strong>tseries</strong><a href="確率的トレンドと単位根検定.html#パッケージtseries" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>次に, パッケージ<strong>tseries</strong>内の関数<code>adf.test()</code>の実行例を示す.</p>
<pre><code>用法:
adf.test(x, alternative = c(&quot;stationary&quot;, &quot;explosive&quot;),
    k = trunc((length(x)-1)^(1/3)))
引数:
- ラグ次数k: number of lags in the regression
  - デフォルト値: trunc((length(x)-1)^(1/3)): the suggested upper bound on the rate (to grow with the sample size for the general ARMA(p,q) setup)
- 対立仮説alternative: &quot;stationary&quot;(デフォルト) or &quot;explosive&quot;</code></pre>
<p>検定を行うデータセットは, パッケージ<strong>quantmod</strong>により取得する株価データ (みずほFG, 証券コード8411) である.
- 注) R/RStudioや<strong>quantmod</strong>のバージョンが更新されていないと, 動かないことがある.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="確率的トレンドと単位根検定.html#cb368-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&#39;quantmod&#39;</span>)</span></code></pre></div>
<pre><code>## Loading required package: xts</code></pre>
<pre><code>## Loading required package: TTR</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="確率的トレンドと単位根検定.html#cb372-1" tabindex="-1"></a>yj8411 <span class="ot">&lt;-</span> <span class="fu">getSymbols</span>(<span class="st">&#39;8411.T&#39;</span>,<span class="at">from =</span> <span class="st">&#39;2020-10-01&#39;</span>, </span>
<span id="cb372-2"><a href="確率的トレンドと単位根検定.html#cb372-2" tabindex="-1"></a>                     <span class="at">to =</span> <span class="st">&#39;2024-10-31&#39;</span>, <span class="at">src =</span> <span class="st">&quot;yahoo&quot;</span>, <span class="at">auto.assign =</span> <span class="cn">FALSE</span>) </span>
<span id="cb372-3"><a href="確率的トレンドと単位根検定.html#cb372-3" tabindex="-1"></a>p8411 <span class="ot">&lt;-</span> <span class="fu">Ad</span>(yj8411) <span class="co"># 調整後株価</span></span>
<span id="cb372-4"><a href="確率的トレンドと単位根検定.html#cb372-4" tabindex="-1"></a><span class="co"># lnp8411 &lt;- log(Ad(yj8411)) # 対数株価</span></span>
<span id="cb372-5"><a href="確率的トレンドと単位根検定.html#cb372-5" tabindex="-1"></a></span>
<span id="cb372-6"><a href="確率的トレンドと単位根検定.html#cb372-6" tabindex="-1"></a><span class="fu">plot</span>(p8411)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="確率的トレンドと単位根検定.html#cb373-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb373-2"><a href="確率的トレンドと単位根検定.html#cb373-2" tabindex="-1"></a><span class="fu">acf</span>(p8411)</span>
<span id="cb373-3"><a href="確率的トレンドと単位根検定.html#cb373-3" tabindex="-1"></a><span class="fu">pacf</span>(p8411)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="確率的トレンドと単位根検定.html#cb374-1" tabindex="-1"></a><span class="co"># acf(diff(p8411), na.action = na.omit)</span></span>
<span id="cb374-2"><a href="確率的トレンドと単位根検定.html#cb374-2" tabindex="-1"></a><span class="co"># pacf(diff(p8411),na.action = na.omit)</span></span></code></pre></div>
<p>得られた日次株価データに対してADF検定を実行する.
(帰無仮説<span class="math inline">\(H_0\)</span>: <span class="math inline">\({X_t}\)</span>は単位根を持つ)</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="確率的トレンドと単位根検定.html#cb375-1" tabindex="-1"></a><span class="co"># ADF検定 (Augmentd Dicky-Fuller test)</span></span>
<span id="cb375-2"><a href="確率的トレンドと単位根検定.html#cb375-2" tabindex="-1"></a><span class="co"># (H0: x has unit root)</span></span>
<span id="cb375-3"><a href="確率的トレンドと単位根検定.html#cb375-3" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb375-4"><a href="確率的トレンドと単位根検定.html#cb375-4" tabindex="-1"></a><span class="fu">adf.test</span>(p8411)</span>
<span id="cb375-5"><a href="確率的トレンドと単位根検定.html#cb375-5" tabindex="-1"></a><span class="fu">adf.test</span>(p8411, <span class="at">k =</span> <span class="dv">1</span>)</span>
<span id="cb375-6"><a href="確率的トレンドと単位根検定.html#cb375-6" tabindex="-1"></a><span class="co"># ← adfTest(p8411, type =&quot;ct&quot;, lags = 1)と同一の結果</span></span>
<span id="cb375-7"><a href="確率的トレンドと単位根検定.html#cb375-7" tabindex="-1"></a><span class="fu">adf.test</span>(p8411, <span class="at">k =</span> <span class="dv">1</span>, <span class="at">alternative =</span> <span class="st">&quot;explosive&quot;</span>)</span>
<span id="cb375-8"><a href="確率的トレンドと単位根検定.html#cb375-8" tabindex="-1"></a><span class="co"># &lt;-- H0 と H1を入替 (→ 同一のDF値. 上行のp値 = 1-下行のp値)</span></span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  p8411
## Dickey-Fuller = -1.8768, Lag order = 9, p-value = 0.6305
## alternative hypothesis: stationary
## 
## 
##  Augmented Dickey-Fuller Test
## 
## data:  p8411
## Dickey-Fuller = -2.7501, Lag order = 1, p-value = 0.2608
## alternative hypothesis: stationary
## 
## 
##  Augmented Dickey-Fuller Test
## 
## data:  p8411
## Dickey-Fuller = -2.7501, Lag order = 1, p-value = 0.7392
## alternative hypothesis: explosive</code></pre>
</div>
<div id="パッケージurca" class="section level3 unnumbered hasAnchor">
<h3>パッケージ<strong>urca</strong><a href="確率的トレンドと単位根検定.html#パッケージurca" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>次に, パッケージ<strong>urca</strong>内の関数<code>ur.df()</code>の実行例を示す.</p>
<p>本格的な時系列分析の実務や研究においては, <code>ur.df()</code> は, 以下に示すように, 高機能で, より推奨されるツールとして扱われることも多い.</p>
<pre><code>用法:
ur.df(y, type = c(&quot;none&quot;, &quot;drift&quot;, &quot;trend&quot;), lags = 1,
      selectlags = c(&quot;Fixed&quot;, &quot;AIC&quot;, &quot;BIC&quot;)) </code></pre>
<p>データセットは, パッケージ<strong>expsmooth</strong>に収納されているbondsを使用する.</p>
<pre><code>データセット: bonds {expsmooth}
- 米国10年債利回り(年率) , 1994.1〜2004.5, 月次
- データ出所 (オリジナル): Hyndman, R.J., Koehler, A.B., Ord, J.K., and Snyder, R.D., (2008), Forecasting with exponential smoothing: the state space approach, Springer.</code></pre>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="確率的トレンドと単位根検定.html#cb379-1" tabindex="-1"></a><span class="co"># library(&quot;forecast&quot;)</span></span>
<span id="cb379-2"><a href="確率的トレンドと単位根検定.html#cb379-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;expsmooth&quot;</span>) <span class="co"># required for the data</span></span></code></pre></div>
<pre><code>## Loading required package: forecast</code></pre>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="確率的トレンドと単位根検定.html#cb381-1" tabindex="-1"></a><span class="fu">plot</span>(bonds)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="確率的トレンドと単位根検定.html#cb382-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb382-2"><a href="確率的トレンドと単位根検定.html#cb382-2" tabindex="-1"></a><span class="fu">acf</span>(bonds)</span>
<span id="cb382-3"><a href="確率的トレンドと単位根検定.html#cb382-3" tabindex="-1"></a><span class="fu">pacf</span>(bonds)</span></code></pre></div>
<p><img src="042-unitroot_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<p>まず, ラグ次数 (引数<code>lags</code>) を1に固定した場合 (デフォルト) を実行する.
トレンドの指定 (引数<code>type</code>) は, なし (“none”), 定数項のみ (“drift”), 定数項+傾き (“trend”)
の3通りの結果を比較してみる.</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="確率的トレンドと単位根検定.html#cb383-1" tabindex="-1"></a><span class="fu">library</span>(urca)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;urca&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:fUnitRoots&#39;:
## 
##     punitroot, qunitroot, unitrootTable</code></pre>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="確率的トレンドと単位根検定.html#cb386-1" tabindex="-1"></a><span class="co"># ラグ次数固定</span></span>
<span id="cb386-2"><a href="確率的トレンドと単位根検定.html#cb386-2" tabindex="-1"></a><span class="co"># selectlags = &quot;fixed&quot; (デフォルト)</span></span>
<span id="cb386-3"><a href="確率的トレンドと単位根検定.html#cb386-3" tabindex="-1"></a><span class="co"># lags = 1 (デフォルト)</span></span></code></pre></div>
<ul>
<li>トレンドなし (<code>type="none"</code>)</li>
</ul>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="確率的トレンドと単位根検定.html#cb387-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.49498 -0.18042 -0.02486  0.18454  0.68176 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## z.lag.1    -0.002436   0.003747  -0.650  0.51690   
## z.diff.lag  0.265314   0.088063   3.013  0.00315 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2408 on 121 degrees of freedom
## Multiple R-squared:  0.07345,    Adjusted R-squared:  0.05813 
## F-statistic: 4.796 on 2 and 121 DF,  p-value: 0.0099
## 
## 
## Value of test-statistic is: -0.65 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<ul>
<li>定数項のみモデル (<code>type="drift"</code>)</li>
</ul>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="確率的トレンドと単位根検定.html#cb389-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">type =</span> <span class="st">&quot;drift&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.50712 -0.18094 -0.04008  0.17625  0.61088 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  0.17260    0.11527   1.497  0.13692   
## z.lag.1     -0.03166    0.01987  -1.593  0.11371   
## z.diff.lag   0.28483    0.08858   3.216  0.00167 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2395 on 120 degrees of freedom
## Multiple R-squared:  0.08863,    Adjusted R-squared:  0.07344 
## F-statistic: 5.835 on 2 and 120 DF,  p-value: 0.003816
## 
## 
## Value of test-statistic is: -1.5934 1.3345 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.46 -2.88 -2.57
## phi1  6.52  4.63  3.81</code></pre>
<ul>
<li>定数項+傾きモデル (<code>type="trend"</code>)</li>
</ul>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="確率的トレンドと単位根検定.html#cb391-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">type =</span> <span class="st">&quot;trend&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression trend 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.56296 -0.15468 -0.01879  0.16003  0.60493 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.059755   0.289261   3.664 0.000373 ***
## z.lag.1     -0.143763   0.038789  -3.706 0.000321 ***
## tt          -0.003952   0.001190  -3.320 0.001196 ** 
## z.diff.lag   0.314505   0.085564   3.676 0.000357 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2301 on 119 degrees of freedom
## Multiple R-squared:  0.1659, Adjusted R-squared:  0.1449 
## F-statistic: 7.889 on 3 and 119 DF,  p-value: 7.626e-05
## 
## 
## Value of test-statistic is: -3.7062 4.6378 6.8862 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau3 -3.99 -3.43 -3.13
## phi2  6.22  4.75  4.07
## phi3  8.43  6.49  5.47</code></pre>
<pre><code>**Rコーディング上のヒント**: 
`ur.df()`は単体では検定結果を表示しないことから, ここでは,
`tidyverse`流コーディングにより, パイプ演算子(`%&gt;%`)を`summary()`と
組合せて, `ur.df()`の結果を`summary()`に流し込んで, 
一気に出力するようにした.</code></pre>
<p><code>ur.df()</code>を実行すると, ADF回帰式の各係数の推定結果も表示される.
今回データセット<code>bonds</code>に対して, 実行された回帰式 (Rのformula表記) は,</p>
<ul>
<li>トレンドなしモデル (<code>type="none"</code>): z.diff ~ z.lag.1 - 1 + z.diff.lag</li>
<li>定数項のみモデル (<code>type="drift"</code>): z.diff ~ z.lag.1 + 1 + z.diff.lag</li>
<li>定数項+傾きモデル (<code>type="trend"</code>): z.diff ~ z.lag.1 + 1 + tt + z.diff.lag</li>
</ul>
<p>である.</p>
<p>すなわち, 先述の回帰式の記号によれば,</p>
<ul>
<li>“z.diff”: <span class="math inline">\(\Delta X_{t}\)</span></li>
<li>“z.lag.1”: <span class="math inline">\(X_{t-1}\)</span></li>
<li>“z.diff.lag”: <span class="math inline">\(\Delta X_{t-j}, \,j=1,...,p-1\)</span> (まとめて表記)</li>
</ul>
<p>に対応する. また, 3番目のformula内の“tt”は, 時間に対応する変数であり,
この回帰係数が線形トレンドの傾きを表す.</p>
<p>また, formula内の“-1”は定数項なし (“+1”はあり) を表す.</p>
<p>次に ラグ次数 (引数<code>lags</code>) を0に固定した場合 (DF検定に対応) を実行する.
これはモデル式において, z.diff.lag項がないケースである.</p>
<ul>
<li>トレンドなし (<code>type="none"</code>)</li>
</ul>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="確率的トレンドと単位根検定.html#cb394-1" tabindex="-1"></a><span class="co"># ラグ次数固定</span></span>
<span id="cb394-2"><a href="確率的トレンドと単位根検定.html#cb394-2" tabindex="-1"></a><span class="co"># lags = 0 (DF検定の場合) ← z.diff.lag項なし</span></span>
<span id="cb394-3"><a href="確率的トレンドと単位根検定.html#cb394-3" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">lags =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.52732 -0.19639 -0.03244  0.21610  0.61778 
## 
## Coefficients:
##          Estimate Std. Error t value Pr(&gt;|t|)
## z.lag.1 -0.002344   0.003852  -0.609    0.544
## 
## Residual standard error: 0.2486 on 123 degrees of freedom
## Multiple R-squared:  0.003001,   Adjusted R-squared:  -0.005104 
## F-statistic: 0.3703 on 1 and 123 DF,  p-value: 0.544
## 
## 
## Value of test-statistic is: -0.6085 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<ul>
<li>定数項のみモデル (<code>type="drift"</code>)</li>
</ul>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="確率的トレンドと単位根検定.html#cb396-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">type =</span> <span class="st">&quot;drift&quot;</span>, <span class="at">lags =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.53720 -0.19521 -0.04203  0.21914  0.56585 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  0.11873    0.11831   1.004    0.318
## z.lag.1     -0.02246    0.02042  -1.100    0.273
## 
## Residual standard error: 0.2486 on 122 degrees of freedom
## Multiple R-squared:  0.009827,   Adjusted R-squared:  0.001711 
## F-statistic: 1.211 on 1 and 122 DF,  p-value: 0.2733
## 
## 
## Value of test-statistic is: -1.1004 0.6887 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.46 -2.88 -2.57
## phi1  6.52  4.63  3.81</code></pre>
<ul>
<li><ul>
<li>定数項+傾きモデル (<code>type="trend"</code>)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="確率的トレンドと単位根検定.html#cb398-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">type =</span> <span class="st">&quot;trend&quot;</span>, <span class="at">lags =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression trend 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + tt)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.58842 -0.17011 -0.01825  0.16278  0.51496 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  0.910594   0.288463   3.157  0.00201 **
## z.lag.1     -0.122593   0.038880  -3.153  0.00204 **
## tt          -0.003553   0.001188  -2.991  0.00337 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2408 on 121 degrees of freedom
## Multiple R-squared:  0.07801,    Adjusted R-squared:  0.06278 
## F-statistic: 5.119 on 2 and 121 DF,  p-value: 0.007342
## 
## 
## Value of test-statistic is: -3.1531 3.472 5.1193 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau3 -3.99 -3.43 -3.13
## phi2  6.22  4.75  4.07
## phi3  8.43  6.49  5.47</code></pre>
<p>以上, 引数<code>type</code>について3通りの結果を示したが,
先に取り上げた, <strong>fUnitRoots</strong>の<code>adfTest()</code>や<code>unitrootTest()</code>,
<strong>tseries</strong>の<code>adf.test()</code>よりも出力が多く,
使いこなすには補足説明が必要であろう.</p>
<p><code>ur.df()</code>においては, Dicky and Fuller (79,81) にならい,
次のような統計量を用いた検定結果を (同時に) 表示する：
#次のような統計量に関して, 複数の検定結果を表示する：</p>
<ul>
<li>“none”タイプ: tau1</li>
<li>“drift”タイプ: tau2, phi1</li>
<li>“trend”タイプ: tau3, phi2, phi3</li>
</ul>
<p>ここで, トレンドなしモデル (“none”タイプ) では, <span class="math inline">\(\tau_1\)</span> (tau1) は仮説<span class="math inline">\(\kappa=0\)</span> (単位根あり) を検定する“<span class="math inline">\(t\)</span>統計量”である.</p>
<p>次に, 定数項のみモデル (“drift”タイプ) では, <span class="math inline">\(\tau_2\)</span> (tau2) は仮説<span class="math inline">\(\kappa=0\)</span> (単位根あり) を検定する“<span class="math inline">\(t\)</span>統計量”, <span class="math inline">\(\phi_1\)</span> (phi1) は 同時仮説<span class="math inline">\(a=\kappa=0\)</span> (単位根あり, かつ定数項はない) を検定するための“<span class="math inline">\(F\)</span>統計量”である.</p>
<p>一方, 定数項+傾きモデル (“trend”タイプ) では, <span class="math inline">\(\tau_3\)</span> (tau3) は, 仮説<span class="math inline">\(\kappa=0\)</span> (単位根あり) を検定する“<span class="math inline">\(t\)</span>統計量”, <span class="math inline">\(\phi_2\)</span> (phi2) は同時仮説<span class="math inline">\(a=b=\kappa=0\)</span> (単位根あり, かつ定数項も傾きもない) を検定するための“<span class="math inline">\(F\)</span>統計量”, <span class="math inline">\(\phi_3\)</span> (phi3) は, 同時仮説<span class="math inline">\(b=\kappa=0\)</span> (単位根あり, 定数項のみあり) を検定するための“<span class="math inline">\(F\)</span>統計量”である.</p>
<!--
phi3では, $H_0: \kappa= \beta_2 =0$ (単位根で傾きなし, ただし\beta_1$は制限なし). これは傾き を単位根の下で省略できるかどうかを検定する. 
phi2は, $H_0: \kappa=0, \beta_1=0, \beta_2=0$ (定数項と傾きなし). これにより, 定数項と傾きの両方を省略できるかを確認する.
-->
<!---- 作成中: 112825 -->
<p>以上整理すると, 次のような“(A)DF戦略”で単位根検定をすることが考えられる.</p>
<ol style="list-style-type: decimal">
<li>いちばん一般的な <strong>trend モデル</strong>から始める：
<span class="math display">\[    
\Delta X_t = a + b t + \kappa X_{t-1} + \cdots
\]</span><br />
</li>
<li>まず <span class="math inline">\(\tau_3\)</span>で「単位根の有無」を調べる.</li>
<li>単位根を棄却できない場合（<span class="math inline">\(\kappa=0\)</span> を棄却できない場合）は, <span class="math inline">\(\phi_3,\phi_2\)</span>を使って「トレンドやドリフトを落としてよいか」を検討する.</li>
</ol>
<ul>
<li><span class="math inline">\(\phi_3\)</span> を棄却できなければ「トレンドは不要」→ <code>type="drift"</code>へ</li>
<li>さらに <span class="math inline">\(\phi_2\)</span> も棄却できなければ「切片も不要」→ <code>type="none"</code>へ.</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>最終的に妥当だと判断した仕様の <span class="math inline">\(\tau\)</span> 統計量（<span class="math inline">\(\tau_1,\tau_2,\tau_3\)</span>) で単位根の有無を判断する</li>
</ol>
<p>引数<code>type = "trend"</code>を与えた時の<code>ur.df()</code> の出力はちょうどこの戦略のフローを反映しており：</p>
<ul>
<li><strong>1つ目の統計量</strong> (<span class="math inline">\(\tau_3\)</span>) が「単位根の有無」</li>
<li><strong>2つ目・3つ目</strong> (<span class="math inline">\(\phi_2,\phi_3\)</span>) が「ドリフト・トレンドの必要性」</li>
</ul>
<p>を同時に表示している.</p>
<p><strong>ラグ次数の自動選択</strong></p>
<p>つぎに, ラグ次数 (引数<code>lags</code>) を自動選択した場合を実行する.
引数<code>selectlags="AIC"</code>に設定すればAIC基準で,
<code>selectlags="BIC"</code>とすればBIC基準で次数選択が行われる.
デフォルトは, 上で示したように固定 (<code>selectlags="fixed"</code>) である.</p>
<ul>
<li>トレンドなし (<code>type="none"</code>)</li>
</ul>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="確率的トレンドと単位根検定.html#cb400-1" tabindex="-1"></a><span class="co"># ラグ次数をAIC基準により自動選択</span></span>
<span id="cb400-2"><a href="確率的トレンドと単位根検定.html#cb400-2" tabindex="-1"></a><span class="co"># selectlags = &quot;AIC&quot;</span></span>
<span id="cb400-3"><a href="確率的トレンドと単位根検定.html#cb400-3" tabindex="-1"></a><span class="co"># サーチするラグ次数の最大値lags=10</span></span>
<span id="cb400-4"><a href="確率的トレンドと単位根検定.html#cb400-4" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">selectlags =</span> <span class="st">&quot;AIC&quot;</span>, <span class="at">lags =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.46513 -0.13370 -0.02074  0.14663  0.60725 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## z.lag.1     -0.006504   0.003876  -1.678   0.0962 .
## z.diff.lag1  0.239620   0.093240   2.570   0.0115 *
## z.diff.lag2 -0.138994   0.098096  -1.417   0.1594  
## z.diff.lag3  0.135671   0.098201   1.382   0.1700  
## z.diff.lag4  0.003777   0.098249   0.038   0.9694  
## z.diff.lag5 -0.227444   0.095012  -2.394   0.0184 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2305 on 108 degrees of freedom
## Multiple R-squared:  0.1504, Adjusted R-squared:  0.1032 
## F-statistic: 3.185 on 6 and 108 DF,  p-value: 0.006444
## 
## 
## Value of test-statistic is: -1.6781 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<p>出力結果によれば, 確定的トレンドなし (<span class="math inline">\(a=0,b=0\)</span>) のケースにおいては,1回差分 <span class="math inline">\(\{\Delta X_t\}\)</span> に対する
上記ADF検定の回帰式における <span class="math inline">\(\{\Delta X_t\}\)</span> のラグ次数 (<span class="math inline">\(p-1\)</span>) として,
5が, AIC基準の下で自動選択された. 二つのADF検定統計量tau2, phi1いずれも
有意でない (10%水準に達していない), すなわち, 単位根仮説は棄却されない.</p>
<ul>
<li>定数項のみモデル (<code>type="drift"</code>)</li>
</ul>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="確率的トレンドと単位根検定.html#cb402-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">type =</span> <span class="st">&quot;drift&quot;</span>, <span class="at">selectlags =</span> <span class="st">&quot;AIC&quot;</span>, <span class="at">lags =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.47654 -0.15143 -0.01987  0.14226  0.55707 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  0.23568    0.12153   1.939  0.05510 . 
## z.lag.1     -0.04696    0.02121  -2.214  0.02894 * 
## z.diff.lag1  0.24669    0.09214   2.677  0.00859 **
## z.diff.lag2 -0.11712    0.09752  -1.201  0.23241   
## z.diff.lag3  0.15712    0.09760   1.610  0.11038   
## z.diff.lag4  0.02585    0.09768   0.265  0.79182   
## z.diff.lag5 -0.19839    0.09501  -2.088  0.03917 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2276 on 107 degrees of freedom
## Multiple R-squared:  0.1665, Adjusted R-squared:  0.1198 
## F-statistic: 3.563 on 6 and 107 DF,  p-value: 0.002947
## 
## 
## Value of test-statistic is: -2.2141 3.3245 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.46 -2.88 -2.57
## phi1  6.52  4.63  3.81</code></pre>
<p>このケースでは, 定数項 (<span class="math inline">\(a\)</span>) が回帰式に含まれており, 出力結果には”(Interecept)“として推定値や
標準誤差等が表示されている (ただし, <span class="math inline">\(b=0\)</span>).
ADF検定統計量tau1は
10%有意ではあるが, 5%有意ではない. すなわち, 有意水準を10%に設定した場合には,
単位根仮説は棄却される.</p>
<ul>
<li>定数項+傾きモデル (<code>type="trend"</code>)</li>
</ul>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="確率的トレンドと単位根検定.html#cb404-1" tabindex="-1"></a><span class="fu">ur.df</span>(bonds, <span class="at">type =</span> <span class="st">&quot;trend&quot;</span>, <span class="at">selectlags =</span> <span class="st">&quot;AIC&quot;</span>, <span class="at">lags =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression trend 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.52136 -0.16195 -0.03909  0.14174  0.61941 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.081602   0.323598   3.342 0.001142 ** 
## z.lag.1     -0.154046   0.042816  -3.598 0.000486 ***
## tt          -0.003555   0.001339  -2.655 0.009129 ** 
## z.diff.lag1  0.300752   0.091537   3.286 0.001373 ** 
## z.diff.lag2 -0.099373   0.095099  -1.045 0.298386    
## z.diff.lag3  0.244475   0.094637   2.583 0.011123 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2239 on 108 degrees of freedom
## Multiple R-squared:  0.1853, Adjusted R-squared:  0.1476 
## F-statistic: 4.914 on 5 and 108 DF,  p-value: 0.0004322
## 
## 
## Value of test-statistic is: -3.5979 5.095 7.0366 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau3 -3.99 -3.43 -3.13
## phi2  6.22  4.75  4.07
## phi3  8.43  6.49  5.47</code></pre>
<p>線形トレンドあり (<code>type = "trend"</code>) のケースは, それ以外の2ケースと異なり,
<code>tau3</code>検定統計量では5%, <code>phi2</code>では10%, <code>phi3</code>では5%の有意水準で,
帰無仮説 (単位根なし) が棄却された. すなわち,
最後の結果は, このデータ期間においては,
確定的な線形トレンド (傾きが一定) に定常ノイズが加わっているモデルで
表現できる可能性 (長期間に渡っての債券利回り=長期金利の低下傾向) を示唆している.
企業成長に従って際限なく増加する可能性のある株価とは異なり, そもそも, 金利は上がっては下がり, 下がっては上がるという
平均回帰的 (mean reversion) な特性を持っている.
さらに, 金利市場はマクロ経済環境だけでなく,
金融当局の政策の影響を受け,
しかも, 金融政策は一貫性を保つようある程度長期に渡って
維持されることが期待されるものである
(頻繁には変更されないものである) から,
このような「線形トレンド+定常ノイズ」のモデルによるデータの記述は説得力を持つようにも見えるし,
予測への利用可能性も期待できそうである.</p>
<p>しかしながら, もとより, 金融市場データにおいては,
確定的トレンドが長い期間, とりわけ将来にわたって続くことは考えにくいことから,
このような推定結果に関する評価や, 将来予測への使用には注意が必要なのは当然である.</p>
<p>以上の例で示した通り, 分析対象の時系列データによっては,
確定トレンドの仮定に依存して, 単位根の有無に関する結論が逆転する可能性がある.
金融市場等, そのデータを生成しているメカニズムや,
外部環境に関する専門知識や経験をフルに活用したモデリングや
分析が求められる.</p>
<p><strong>自主課題</strong>:
引数<code>type</code>の3つのケースについて, トレンドなし → 定数項有 → 定数項+傾き有, の順に結果を出力したが, アプローチを変え, 今度は, 先の“(A)DF戦略”に沿って<code>bonds</code>データの単位根検定を行うとどうなるか考えてみよう.</p>
</div>
</div>
<div id="adf検定以外の検定法" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> ADF検定以外の検定法<a href="確率的トレンドと単位根検定.html#adf検定以外の検定法" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Phillips-Perron (PP) 検定, KPSS検定について,
先に使用したみずほFGの日次株価データ (8411) に対して実行する.
上で得られたADF検定の結果と比較してみよう.</p>
<p>PP検定やKPSS検定においては, 確定的トレンドは,
(i) 定数項のみ, (ii) 線形トレンド (定数項+傾き), の2つのケースがあり (注: ADF検定では3つのケースがあった), 実行に際してどちらかを指定して行う.
<!-- GPT o1-previewの回答:
Reason for Two Types: In the KPSS framework, the model without a constant term (no deterministic component) is not meaningful. The test is designed to detect departures from stationarity due to a unit root, assuming the series is stationary around a level or trend under the null hypothesis. Testing for stationarity around zero (without a constant) is rarely practical because most economic time series have non-zero means.
While the PP test can, in theory, be specified without a constant, it's uncommon in practice. The absence of a constant term is less relevant because economic time series often exhibit mean levels that should be accounted for in the model.
--></p>
<div id="phillips-perron-pp-検定" class="section level3 unnumbered hasAnchor">
<h3>Phillips-Perron (PP) 検定<a href="確率的トレンドと単位根検定.html#phillips-perron-pp-検定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>PP検定では, 確定的トレンドに加わる誤差項として一般の線形過程を用いる.
すなわち, ADF検定のような誤差項のモデル化 (AR(<span class="math inline">\(p\)</span>)モデルによるラグ構造の特定)
をする必要がない. しかし, 標本数が十分大きくない状況では,
PP検定も結果の信頼性の点で問題があることから, モデルに関する事前の情報を
使える場合には, ADF検定の方が望ましいと言える.
<!-- 加筆111524: 田中, p.253 --></p>
<div id="パッケージtseries内-関数pp.test" class="section level4 hasAnchor" number="5.4.0.1">
<h4><span class="header-section-number">5.4.0.1</span> パッケージ<strong>tseries</strong>内, 関数<code>pp.test()</code><a href="確率的トレンドと単位根検定.html#パッケージtseries内-関数pp.test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>用法:
pp.test(x, alternative = c(&quot;stationary&quot;, &quot;explosive&quot;),
        type = c(&quot;Z(alpha)&quot;, &quot;Z(t_alpha)&quot;), lshort = TRUE)
主要な引数:
- 対立仮説alternative: &quot;stationary&quot;, &quot;explosive&quot;
- 検定の種類type: &quot;Z(alpha)&quot;, &quot;Z(t_alpha)&quot;
- ラグ次数の打ち切りlshort: T (→ 4(T/100)^(1/4)), F (→ 12(T/100)^(1/4))
※ 確定的トレンドの仮定は, 線形トレンド (定数項+傾き)</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="確率的トレンドと単位根検定.html#cb407-1" tabindex="-1"></a><span class="co">#library(tseries)</span></span>
<span id="cb407-2"><a href="確率的トレンドと単位根検定.html#cb407-2" tabindex="-1"></a><span class="fu">pp.test</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z(alpha)&quot;</span>, <span class="at">lshort =</span> T)   <span class="co"># デフォルト</span></span></code></pre></div>
<pre><code>## 
##  Phillips-Perron Unit Root Test
## 
## data:  p8411
## Dickey-Fuller Z(alpha) = -10.768, Truncation lag parameter = 7, p-value
## = 0.5091
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="確率的トレンドと単位根検定.html#cb409-1" tabindex="-1"></a><span class="fu">pp.test</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z(alpha)&quot;</span>, <span class="at">lshort =</span> F)</span></code></pre></div>
<pre><code>## 
##  Phillips-Perron Unit Root Test
## 
## data:  p8411
## Dickey-Fuller Z(alpha) = -8.9384, Truncation lag parameter = 21,
## p-value = 0.6111
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="確率的トレンドと単位根検定.html#cb411-1" tabindex="-1"></a><span class="fu">pp.test</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z(t_alpha)&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Phillips-Perron Unit Root Test
## 
## data:  p8411
## Dickey-Fuller Z(t_alpha) = -2.3096, Truncation lag parameter = 7,
## p-value = 0.4472
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="確率的トレンドと単位根検定.html#cb413-1" tabindex="-1"></a><span class="co">#pp.test(p8411, alternative = &quot;explosive&quot;)</span></span></code></pre></div>
</div>
<div id="パッケージurca内-関数ur.pp" class="section level4 unnumbered hasAnchor">
<h4>パッケージ<strong>urca</strong>内, 関数<code>ur.pp()</code><a href="確率的トレンドと単位根検定.html#パッケージurca内-関数ur.pp" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>用法:
ur.pp(x, type = c(&quot;Z-alpha&quot;, &quot;Z-tau&quot;), model = c(&quot;constant&quot;, &quot;trend&quot;),
        lags = c(&quot;short&quot;, &quot;long&quot;), use.lag = NULL)
主要な引数:
- 確定的トレンドの種類model: &quot;constant&quot; (定数項), &quot;trend&quot; (線形トレンド)
- 検定の種類type: &quot;Z-alpha&quot;, &quot;Z-tau&quot;
- 誤差修正項のラグ長lag: &quot;short&quot;, &quot;long&quot;</code></pre>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="確率的トレンドと単位根検定.html#cb415-1" tabindex="-1"></a><span class="fu">library</span>(urca)</span>
<span id="cb415-2"><a href="確率的トレンドと単位根検定.html#cb415-2" tabindex="-1"></a><span class="co">#lags: ラグの長さの指定. 4(T/100)^(1/4) or 12(T/100)^(1/4)</span></span>
<span id="cb415-3"><a href="確率的トレンドと単位根検定.html#cb415-3" tabindex="-1"></a><span class="co">#model: トレンドを持つ(&quot;trend&quot;), 定数項を持つ(&quot;constant&quot;)</span></span></code></pre></div>
<ul>
<li><span class="math inline">\(Z_{\alpha}\)</span>検定 &amp; 線形トレンドあり</li>
</ul>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="確率的トレンドと単位根検定.html#cb416-1" tabindex="-1"></a><span class="fu">ur.pp</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z-alpha&quot;</span>, <span class="at">model =</span> <span class="st">&quot;trend&quot;</span>, <span class="at">lags =</span> <span class="st">&quot;short&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ################################## 
## # Phillips-Perron Unit Root Test # 
## ################################## 
## 
## Test regression with intercept and trend 
## 
## 
## Call:
## lm(formula = y ~ y.l1 + trend)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -571.21  -13.94   -1.14   14.96  203.75 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.908414   9.184759   2.712  0.00680 ** 
## y.l1         0.987289   0.005062 195.048  &lt; 2e-16 ***
## trend        0.029106   0.011051   2.634  0.00857 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38.44 on 997 degrees of freedom
## Multiple R-squared:  0.9963, Adjusted R-squared:  0.9963 
## F-statistic: 1.343e+05 on 2 and 997 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic, type: Z-alpha  is: -10.7685 
## 
##            aux. Z statistics
## Z-tau-mu              3.3589
## Z-tau-beta            2.4723</code></pre>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="確率的トレンドと単位根検定.html#cb418-1" tabindex="-1"></a><span class="fu">ur.pp</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z-alpha&quot;</span>, <span class="at">model =</span> <span class="st">&quot;trend&quot;</span>, <span class="at">lags =</span> <span class="st">&quot;long&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ################################## 
## # Phillips-Perron Unit Root Test # 
## ################################## 
## 
## Test regression with intercept and trend 
## 
## 
## Call:
## lm(formula = y ~ y.l1 + trend)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -571.21  -13.94   -1.14   14.96  203.75 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.908414   9.184759   2.712  0.00680 ** 
## y.l1         0.987289   0.005062 195.048  &lt; 2e-16 ***
## trend        0.029106   0.011051   2.634  0.00857 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38.44 on 997 degrees of freedom
## Multiple R-squared:  0.9963, Adjusted R-squared:  0.9963 
## F-statistic: 1.343e+05 on 2 and 997 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic, type: Z-alpha  is: -8.9395 
## 
##            aux. Z statistics
## Z-tau-mu              4.1119
## Z-tau-beta            2.3111</code></pre>
<ul>
<li><span class="math inline">\(Z_{\tau}\)</span>検定 &amp; 線形トレンドあり</li>
</ul>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="確率的トレンドと単位根検定.html#cb420-1" tabindex="-1"></a><span class="fu">ur.pp</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z-tau&quot;</span>, <span class="at">model =</span> <span class="st">&quot;trend&quot;</span>, <span class="at">lags =</span> <span class="st">&quot;long&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ################################## 
## # Phillips-Perron Unit Root Test # 
## ################################## 
## 
## Test regression with intercept and trend 
## 
## 
## Call:
## lm(formula = y ~ y.l1 + trend)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -571.21  -13.94   -1.14   14.96  203.75 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.908414   9.184759   2.712  0.00680 ** 
## y.l1         0.987289   0.005062 195.048  &lt; 2e-16 ***
## trend        0.029106   0.011051   2.634  0.00857 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38.44 on 997 degrees of freedom
## Multiple R-squared:  0.9963, Adjusted R-squared:  0.9963 
## F-statistic: 1.343e+05 on 2 and 997 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic, type: Z-tau  is: -2.1024 
## 
##            aux. Z statistics
## Z-tau-mu              4.1119
## Z-tau-beta            2.3111
## 
## Critical values for Z statistics: 
##                    1pct      5pct     10pct
## critical values -3.9722 -3.416657 -3.130326</code></pre>
<ul>
<li><span class="math inline">\(Z_{\tau}\)</span>検定 &amp; 定数項あり</li>
</ul>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="確率的トレンドと単位根検定.html#cb422-1" tabindex="-1"></a><span class="fu">ur.pp</span>(p8411, <span class="at">type =</span> <span class="st">&quot;Z-tau&quot;</span>, <span class="at">model =</span> <span class="st">&quot;constant&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ################################## 
## # Phillips-Perron Unit Root Test # 
## ################################## 
## 
## Test regression with intercept 
## 
## 
## Call:
## lm(formula = y ~ y.l1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -571.86  -14.33   -1.27   15.17  208.49 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.740814   3.688286   0.743    0.458    
## y.l1        0.999615   0.001934 516.776   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38.55 on 998 degrees of freedom
## Multiple R-squared:  0.9963, Adjusted R-squared:  0.9963 
## F-statistic: 2.671e+05 on 1 and 998 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic, type: Z-tau  is: -0.0185 
## 
##          aux. Z statistics
## Z-tau-mu            0.6342
## 
## Critical values for Z statistics: 
##                      1pct      5pct     10pct
## critical values -3.439528 -2.864846 -2.568542</code></pre>
</div>
</div>
<div id="kwiatkowski-phillips-schmidt-shin-kpss-検定" class="section level3 unnumbered hasAnchor">
<h3>Kwiatkowski-Phillips-Schmidt-Shin (KPSS) 検定<a href="確率的トレンドと単位根検定.html#kwiatkowski-phillips-schmidt-shin-kpss-検定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>KPSS検定は, ADF検定やPP検定とは, 帰無仮説・対立仮説が入れ替わる:</p>
<ul>
<li><span class="math inline">\(H_{0}\)</span>: 確定的トレンド付き定常過程 vs <span class="math inline">\(H_{1}\)</span>: 単位根過程</li>
</ul>
<p>すなわち, <span class="math inline">\(H_0\)</span> を棄却しない場合は, <strong>確定的トレンド付き定常過程 (トレンド定常性)</strong>
を結論として得ることに注意が必要である.</p>
<p>観測過程が <span class="math inline">\(\{X_{t}\}=\)</span>確定的トレンド + ランダムウォーク + 定常過程,</p>
<p>すなわち,
<span class="math display">\[
X_{t} = \alpha+\beta \cdot t + \sum_{s=1}^{t}Z_{s} + \epsilon_{t}, \, \{Z_t\}\sim IID(0,\sigma_Z^2)
\]</span>
として生成されていると仮定, ランダムウォーク項の有無の検定を<span class="math inline">\(Z_t\)</span>の分散が0か否かを調べることで行う.</p>
<ul>
<li><span class="math inline">\(H_{0}:\,\sigma_{Z}^{2}=0\)</span> (トレンド定常過程) vs <span class="math inline">\(H_{1}:\,\sigma_{Z}^{2}\ne0\)</span> (単位根過程)</li>
</ul>
<p>具体的には, 確定的トレンド (<span class="math inline">\(\alpha+\beta t\)</span>) を説明変数とする最小二乗回帰によって得られる残差部分和の大きさを使って検定を行う.</p>
<div id="パッケージurca内-関数ur.kpss" class="section level4 unnumbered hasAnchor">
<h4>パッケージ<strong>urca</strong>内, 関数<code>ur.kpss()</code><a href="確率的トレンドと単位根検定.html#パッケージurca内-関数ur.kpss" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>用法:
ur.kpss(y, type = c(&quot;mu&quot;, &quot;tau&quot;), lags = c(&quot;short&quot;, &quot;long&quot;, &quot;nil&quot;),
        use.lag = NULL)
主要な引数:
- 確定的トレンドの種類type: &quot;mu&quot; (定数項), &quot;tau&quot; (線形トレンド)
- 誤差修正項のラグ長lags: &quot;short&quot;=4(T/100)^(1/4), &quot;long&quot;=12(T/100)^(1/4)</code></pre>
<ul>
<li>定数項あり</li>
</ul>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="確率的トレンドと単位根検定.html#cb425-1" tabindex="-1"></a><span class="fu">ur.kpss</span>(p8411, <span class="at">type =</span> <span class="st">&quot;mu&quot;</span>, <span class="at">lags =</span> <span class="st">&quot;long&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ####################### 
## # KPSS Unit Root Test # 
## ####################### 
## 
## Test is of type: mu with 21 lags. 
## 
## Value of test-statistic is: 4.156 
## 
## Critical value for a significance level of: 
##                 10pct  5pct 2.5pct  1pct
## critical values 0.347 0.463  0.574 0.739</code></pre>
<ul>
<li>線形トレンドあり</li>
</ul>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="確率的トレンドと単位根検定.html#cb427-1" tabindex="-1"></a><span class="fu">ur.kpss</span>(p8411, <span class="at">type =</span> <span class="st">&quot;tau&quot;</span>, <span class="at">lags =</span> <span class="st">&quot;long&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## ####################### 
## # KPSS Unit Root Test # 
## ####################### 
## 
## Test is of type: tau with 21 lags. 
## 
## Value of test-statistic is: 0.9797 
## 
## Critical value for a significance level of: 
##                 10pct  5pct 2.5pct  1pct
## critical values 0.119 0.146  0.176 0.216</code></pre>
<p>ちなみに, <strong>forecast</strong>パッケージの関数<code>ndiff()</code>は, 時系列データが定常になるのに必要な差分操作の回数を求める関数で,
内部で単位根検定を繰り返し実行する.</p>
<pre><code>用法:
ndiffs(x, alpha = 0.05, test = c(&quot;kpss&quot;, &quot;adf&quot;, &quot;pp&quot;),
       type = c(&quot;level&quot;, &quot;trend&quot;), max.d = 2, ...)
- 単位根検定の種類test: KPSS (デフォルト)/ADF/PP
- 確定的トレンドの種類type: &quot;level&quot;(定数項のみ)/&quot;trend&quot;(定数項+線形トレンド)</code></pre>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="arimasarimaモデル.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="長期記憶過程.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
